### DISCUSSION TITLE
Renaming secrets before using it

### DISCUSSION THREAD

**Discussion by MikeChongCan** [basecamp/kamal#1011] [Ideas]
Sometimes we need to define a different secret name for the same env var, like `POSTGRES_PASSWORD` for production data db and solid cache db, respectively.

It would be nice if we could have something like

```yaml
accessories:
  job_cache_db:
    image: postgres:17-alpine
    # ....
    env:
      clear:
        POSTGRES_DB: db_name
        POSTGRES_USER: user_name
      secret:
        - POSTGRES_PASSWORD=$JOB_CACHE_PG_PASWORD
    directories:
      - data:/var/lib/postgresql/data
```
