### DISCUSSION TITLE
Extracting Rails credentials as ENV vars for accessories?

### DISCUSSION THREAD

**Discussion by northeastprince** [basecamp/kamal#1115] [Q&A] [answered]
I'm running Litestream as an accessory and would like to be able to use the existing S3 credentials encrypted with RAILS_MASTER_KEY and set them as environment variables - any idea how I could go about this?

**Comment by tuladhar** [comment]
You can set the secrets environment variable for accessory, like this:
```
# Use accessory services (secrets come from .kamal/secrets)
accessories:
  litestream:
    env:
      secret:
        - S3_CREDENTIAL_A
        - S3_CREDENTIAL_B
```
