### DISCUSSION TITLE
Accessory reboot with fresh image

### DISCUSSION THREAD

**Discussion by miharekar** [basecamp/kamal#1168] [Ideas]
`kamal accessory reboot [name]` currently stops, prunes, and re-runs the image.

The only way to update the image is to log in to server and do a `docker pull [image-name]:latest` followed by `kamal accessory reboot [name]` and that will run the newest version of the container image.

It would be great if we could pass an option to reboot - like `--pull` or something, or have a new command to refresh the accessory container image.

WDYT?

**Comment by hundredwatt** [comment]
I added an alias to make it more convenient to pull the latest image, but agree this should be a configuration option or command for the accessory 

```yaml
aliases:
  pull-<accessory>: server exec docker pull <image>:latest
```

Then I can do:
```bash
kamal pull-<accessory>
kamal accessory reboot <accessory>
```

**Reply by steinbrueckri** [reply]
Nice but what also works ... `pull: always`, see below. Then you only need to run `kamal accessory reboot all`

```
  kv:
    image: valkey/valkey:7.2
    options:
      pull: always
    host: *host
    port: 127.0.0.1:6379:6379
    volumes:
      - /var/lib/valkey/data:/data
```
