### DISCUSSION TITLE
Kamal Proxy logs: "level":"INFO","msg":"http: TLS handshake error from <myip>:: no server name provided"

### DISCUSSION THREAD

**Discussion by orbanbotond** [basecamp/kamal#1171] [Q&A]
Hi,

I have this `deploy.yml` file:

```
# Deploy to these servers.
servers:
  - <ip of the cloud server>
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode 
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption. 
proxy: 
  ssl: true
  host: <ip of the cloud server, same as above>
  # kamal-proxy connects to your container over port 80, use `app_port` to specify a different port.
  app_port: 3000
```

Then as I turned the ssl to true, the web app no longer responds, I checked the `kamal proxy log`:
"level":"INFO","msg":"http: TLS handshake error from <my home ip>:47524: no server name provided"

Any solutions?
thx in advance
