### DISCUSSION TITLE
Google Cloud Registry Credential Helper

### DISCUSSION THREAD

**Discussion by emerson-argueta** [basecamp/kamal#1213] [Q&A]
Currently in the documentation, to authenticate with google cloud docker registry, you need to use a service account key. 
However, generally I'd authenticate the registry using the credential helper using 
``` bash
gcloud auth configure-docker <registry name>
````
With this I wouldn't need to authenticate with a service account key. 
If I omit the username and password for the registry section in the deploy.yml would kamal fail?

**Comment by tuladhar** [comment]
Yes, username and password for registry is mandatory. If you omit it, Kamal will fail. Also, you can use following command to verify if registry login works with credential helper:
```
kamal registry login
```

Alternatively, you can use [AWS ECR as example](https://kamal-deploy.org/docs/configuration/docker-registry/#using-aws-ecr-as-the-container-registry) to see if this works for Google Cloud.
```
registry:
  server: <region>-docker.pkg.dev
  username: oauth2accesstoken
  password: $(gcloud auth print-access-token)
```
