### DISCUSSION TITLE
does kamal support websockets/socket.io?

### DISCUSSION THREAD

**Discussion by Cytla24** [basecamp/kamal#1215] [Q&A]
hello, 

i deployed a next.js application via kamal to a digital ocean droplet. everything works fine, except the application fails to establish a websocket connection - 308, then 404 status. I looked through kamal-proxy docs, because i wasn't sure if it supported socket.io, but i found nothing. 

I also tried adding traefik as an accessory, so maybe it could handle it but no luck. any thoughts?

this is my deploy.yaml

```
<%
require "dotenv"
Dotenv.load(".env.local")
%>

# Name of your application. Used to uniquely configure containers.
service: turtlevsrabbit

# Name of the container image.
image: ojuba2013/turtlevsrabbit

# Deploy to these servers.
servers:
    web:
        - 157.230.189.61
    # job:
    #   hosts:
    #     - 192.168.0.1
    #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption.
proxy:
    ssl: true
    host: turtlevsrabbit.com
    healthcheck:
        path: /
        interval: 3
        timeout: 3
    # kamal-proxy connects to your container over port 80, use `app_port` to specify a different port.
    app_port: 3000

# Credentials for your image host.
registry:
    # Specify the registry server, if you're not using Docker Hub
    # server: registry.digitalocean.com / ghcr.io / ...
    username: ojuba2013

    # Always use an access token rather than real password (pulled from .kamal/secrets).
    password:
        - KAMAL_REGISTRY_PASSWORD

    server: registry.hub.docker.com

# Configure builder setup.
builder:
    arch: amd64
    context: .
    secrets:
        - NEXT_PUBLIC_SUPABASE_URL
        - NEXT_PUBLIC_SUPABASE_ANON_KEY
        - SUPABASE_SERVICE_ROLE_KEY
        - STRIPE_PUBLIC_KEY
        - STRIPE_SECRET_KEY
        - STRIPE_WEBHOOK_SECRET
        - EMAIL_SERVER
        - MAILGUN_API_KEY
        - NEXT_PUBLIC_SOCKET_URL
        - NODE_ENV
# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
env:
    clear:
        PORT: 3000
        NODE_ENV: production
        NEXT_PUBLIC_SOCKET_URL: https://turtlevsrabbit.com
        NEXT_PUBLIC_SITE_URL: https://turtlevsrabbit.com
    #     DB_HOST: 192.168.0.2
    secret:
        - NEXT_PUBLIC_SUPABASE_URL
        - NEXT_PUBLIC_SUPABASE_ANON_KEY
        - SUPABASE_SERVICE_ROLE_KEY
        - STRIPE_PUBLIC_KEY
        - STRIPE_SECRET_KEY
        - STRIPE_WEBHOOK_SECRET
        - EMAIL_SERVER
        - MAILGUN_API_KEY
# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
#
# aliases:
#   shell: app exec --interactive --reuse "bash"

# Use a different ssh user than root
#
# ssh:
#     user: app
# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
# asset_path: /app/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Use accessory services (secrets come from .kamal/secrets).
#
# accessories:
#   db:
#     image: mysql:8.0
#     host: 192.168.0.2
#     port: 3306
#     env:
#       clear:
#         MYSQL_ROOT_HOST: '%'
#       secret:
#         - MYSQL_ROOT_PASSWORD
#     files:
#       - config/mysql/production.cnf:/etc/mysql/my.cnf
#       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
#     directories:
#       - data:/var/lib/mysql
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data
accessories:
  traefik:
    image: traefik:v2.10
    port: 8080
    cmd: >
      --providers.docker
      --entrypoints.web.address=:8080
      --entrypoints.websecure.address=:8443
      --certificatesresolvers.myresolver.acme.httpchallenge=true
      --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      --certificatesresolvers.myresolver.acme.email=your@email.com
      --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    options:
      volume:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "letsencrypt:/letsencrypt"
      publish:
        - "8443:8443"
    roles:
      - web

labels:
  traefik.http.routers.turtlevsrabbit.rule: "Host(`turtlevsrabbit.com`)"
  traefik.http.routers.turtlevsrabbit.entrypoints: "websecure"
  traefik.http.routers.turtlevsrabbit.tls.certresolver: "myresolver"
  traefik.http.services.turtlevsrabbit.loadbalancer.server.port: "3000"
  traefik.http.middlewares.sio.headers.customrequestheaders.X-Forwarded-Proto: "https"
  traefik.http.routers.turtlevsrabbit.middlewares: "sio@docker"
```
