### DISCUSSION TITLE
Media file serving

### DISCUSSION THREAD

**Discussion by mintyPT** [basecamp/kamal#1216] [General]
Django does not provide file serving out of the box. It's easy to solve this for static files (using whitenoise), but that leaves us lacking for serving media files. In the past, I used a nginx container alongside django, to serve those files. 

Issue is: I'm not sure how to replicate the same behavior with kamal. 

I was thinking of using nginx as an acessory, but how do I then route all requests to `{{host}}/media` to nginx and not django? Or better yet, is this the way to go? (I'm not looking into using S3-like services, would prefer to keep media files on the server)

**Comment by tuladhar** [comment]
Since, Kamal doesn't support path-based virtual hosting, consider hosting it on different subdomain such as `assets.` or `media.` to serve your media files and use Nginx in the container to serve them.

**Comment by michjnich** [comment]
@mintyPT 

I've had the same struggle and have "solved" it (OK, a little hacky, but it's working) with an nginx accessory in my `deploy.yaml` running on a different port, then I set the static URL if I'm running in docker. 
```
STATIC_URL = f"http://{SERVER_IP}:8081/static/" if DOCKER_CONTAINER else "static/"
```
`DOCKER_CONTAINER` is just a hardcoded ENV var in the Dockerfile to indicate that's what's in use.

**Reply by shahid-0** [reply]
Can you elaborate it little bit, I am new to both nginx and kamal. I have deployed my app using kamal 2 but it's not loading the static files

**Reply by michjnich** [reply]
I'm sorry, this was ages ago now. I abandoned kamal becasue it was just too hacky for django projects. I'm sure it's great for rails stuff, but I was just fighting it every step of the way. So I just gave up and wrote my own scripts :)

**Reply by shahid-0** [reply]
So, can I also abandon Kamal for Django projects? Because I also tried a lot lol.

**Reply by michjnich** [reply]
Entirely up to you. That's what I did :)

**Comment by atziallas** [comment]
@shahid-0 

I managed to use an nginx accessory to serve static files for Django, by having it listen on port 81 but exposed properly on kamal-proxy with https on a different subdomain. 

```
accessories:
   nginx:
      image: you/nginx-static
      host: www.yourhost.com
      port: "81:81"
      files:
        - ./custom.conf:/etc/nginx/conf.d/custom.conf
      volumes:
        - /home/app-static/static:/usr/share/nginx/html
      proxy:
        ssl: true
        ssl_redirect: true
        app_port: 81
        host: static.yourhost.com
  ```
 To make nginx listen on port 81, my custom.conf contains this:
  ```
  server {
    listen       81;
    server_name  localhost;
    ...
}
 ```
 
 I guess I could just have done `port: "81:80"` on the accessory? Feel free to try it out 😀

I also managed to serve user uploaded media files that will be "public" (open for everyone to see). I had a **host directory** act as a volume in **both** the django and nginx containers: `/home/app-static/`

Django container just syncs the `/media` path of the `/home/app-static/static` folder:
  
  ```
  volumes:
    - /home/app-static/static/media:/var/www/your-app/media
 ```
 
Django settings would look like this:
```
STATIC_URL = "https://static.yourhost.gr/"
MEDIA_URL = "https://static.yourhost.gr/media/"   
MEDIA_ROOT = "/var/www/your-app/media"
```

Mind you, this solution is only for using "public" media files, so no authentication/authorization involved. For such features you should probably use Django file storage, or implement custom and authorized views for specific file system access.

Have to admit Kamal functions as advertised.  It's for container deployment. There is a lack of examples in the documentation, but you could deploy any web server/framework combination if you set it up properly.

**Reply by henrysingleton** [reply]
Thanks for the detailed writeup [atziallas](https://github.com/atziallas), really helped me along. I think its a good solution.

My project is on an extremely tight budget so paying an additional bill for S3 is out of the question, and why should I when there is a perfectly good VPS sitting there with a bunch of unused disk and bandwidth.

You're right about not needing it on a custom port - you just need to make sure it maps to a non-conflicting port on the host. This way no custom nginx config is required at all: 
```yml
  nginx:
    image: nginx:alpine
    host: www.yourhost.com
    port: "127.0.0.1:81:80"  # Use port 81 to avoid conflicts with the web container.
    volumes:
      - /home/app-static/static:/usr/share/nginx/html
    proxy:
      ssl: true
      app_port: 80  # Uses port 80 not 81 for the health check
      host: static.yourhost.com
```

But the proxy and its health check uses the non-mapped port (80), which I found a bit confusing. Also `ssl_redirect` defaults to true so not required. I like how simple this is overall.
