### DISCUSSION TITLE
How can I run a couple of jobs on the same server?

### DISCUSSION THREAD

**Discussion by ChristianPavilonis** [basecamp/kamal#1293] [Q&A]
I have a laravel app deployed using kamal, I need to add a queue job and a schedule job.

However the containers seem to exit when deploying, but when running them locally using:
 ```
docker run myimage php artisan queue:work --tries=3 --backoff=3 --env=production
```
It works as expected.

All the ips are the same in my config.

```yaml
servers:
  web:
    - <IP>
  queue:
    hosts:
      - <IP>
    cmd: "php artisan queue:work --tries=3 --backoff=3 --env=production"
  schedule:
    hosts:
      - <IP>
    cmd: "php artisan schedule:work --env=production"
```

Also `kamal app logs` doesn't have anything for the services.
`kamal app containers` shows queue exits code 0 as soon as it starts.
I'm not sure if there's a separate place to check for errors.
