### DISCUSSION TITLE
Can you reference an `env` var in your role's `cmd`?

### DISCUSSION THREAD

**Discussion by rahearn** [basecamp/kamal#1323] [Q&A] [answered]
I was hoping to use this simple setup:

```
servers:
  web:
    - *primary_host
  worker:
    hosts:
      - *primary_host
    cmd: bundle exec sidekiq -c $SIDEKIQ_CONCURRENCY -q mailers -q default
    env:
      clear:
        SIDEKIQ_CONCURRENCY: 5
```

But it looks like `$SIDEKIQ_CONCURRENCY` is being inserted on the host (where it is unset) rather than inside the container, where it is 5 as it should be. Is there a way to escape it so that it actually gets the value inside the container? I tried `\$SIDEKIQ_CONCURRENCY` but that resulted in it never getting replaced with 5
