### DISCUSSION TITLE
Use secrets in erb-evaluated accessory `files`

### DISCUSSION THREAD

**Discussion by cmatheson** [basecamp/kamal#1324] [Q&A]
Given an accessory defined like:

```
accessories:
  myservice:
    image: some/image
    files:
      - config/needs.secrets.conf.erb:/service.conf
 ```
and a corresponding needs.secrets.conf.erb:

```
# i want to populate this secret value from my kamal secrets
secret = <%= ENV['secret'] %>
```

unfortunately, it seems that the secrets aren't available at erb-evaluation time. adding the needed secrets to the `env` config for the accessory doesn't affect the files/erb-evaluation stage either. is there any way to do what i'm trying to accomplish?

**Comment by nickhammond** [comment]
@cmatheson I think you just need a list of secrets for your accessory. The list of secrets specified will then get written to an env file on the server and used when the accessory is booted.

```
accessories:
  myservice:
    image: some/image
    env:
      secret:
        - secret
        - another_super_secret_thing
    files:
      - config/needs.secrets.conf.erb:/service.conf
```

And then you'll need to set the secret in `.kamal/secrets` however you'd like, static(don't commit to git) or from a password vault(commit to git).
