### DISCUSSION TITLE
How to alias environment variables?

### DISCUSSION THREAD

**Discussion by guillaumebriday** [basecamp/kamal#1337] [Q&A]
The documentation specifies that tags can be used to assign additional variables to particular hosts: https://kamal-deploy.org/docs/configuration/environment-variables/.

However, I need to use a specific name for my environment variable because the PostgreSQL container requires it—in my case, `POSTGRES_PASSWORD`.

I intend to deploy two PostgreSQL instances, each with a different password, while keeping the environment variable name consistent.

Below is a simplified version of my deployment configuration file:

```yml
accessories:
  db:
    image: postgres:16
    host: 192.168.0.1
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_DB
        - POSTGRES_PASSWORD

  db-replica:
    image: postgres:16
    host: 192.168.0.2
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_DB
        - POSTGRES_PASSWORD
        # I want to map REPLICA_POSTGRES_PASSWORD to `POSTGRES_PASSWORD` here
        # - REPLICA_POSTGRES_PASSWORD
```

Do you know if it possible?

**Comment by mhenrixon** [comment]
You do that with tags at the top level:

```yaml
env:
  clear:
    MYSQL_USER: app
  secret:
    - MYSQL_PASSWORD
  tags:
    monitoring:
      MYSQL_USER: monitoring
    replica:
      clear:
        MYSQL_USER: readonly
      secret:
        - READONLY_PASSWORD
```


https://kamal-deploy.org/docs/configuration/environment-variables/#example-configuration

**Reply by frenkel** [reply]
That makes READONLY_PASSWORD available under that name, not MYSQL_PASSWORD, right? Or how does it know what name to pick for the content of READONLY_PASSWORD?

**Reply by mhenrixon** [reply]
You are right! This is how the environment variable redirection is done:

```yaml
  db-replica:
    image: postgres:16
    host: 192.168.0.2
    env:
      secret:
        - POSTGRES_USER:MY_SOURCE_POSTGRES_USER
        - POSTGRES_DB:MY_SOURCE_POSTGRES_DB
        - POSTGRES_PASSWORD:MY_SOURCE_POSTGRES_PASSWORD        
```

The above instructs kamal to give the container secret environmnent variable of `POSTGRES_USER` and by reading the value from the environment variable `MY_SOURCE_POSTGRES_USER`
