### DISCUSSION TITLE
Passing custom options to docker run via Kamal 2

### DISCUSSION THREAD

**Discussion by MatthewLaFalce** [basecamp/kamal#1339] [Q&A] [answered]
I am trying to integrate an OpenVPN client instance with my Rails 8 app using Kamal to deploy. In other containerized Rails apps that I've deploy I have had to pass the options to `docker run` in order to properly configure the container to allow OpenVPN to start up properly. Is there a way to specify these options in my deploy.yml file?

```bash
--dns custom_dns_address \
--cap-add=NET_ADMIN \
--device=/dev/net/tun 
```

**Comment by nickhammond** [comment, marked as answer]
@MatthewLaFalce You'd just put that under options for your role or accessory https://kamal-deploy.org/docs/configuration/roles/#custom-role-configuration

**Reply by MatthewLaFalce** [reply]
@nickhammond Thank you, that did the trick!

For posterity, I modified my role as such:

```yaml
# Deploy to these servers.
servers:
  web:
    hosts:
      - <custom_server_domain>
    options:
      dns:
        - <custom_dns_address>
        - 8.8.8.8
      cap-add:
        - NET_ADMIN
      device:
        - /dev/net/tun

```
