### DISCUSSION TITLE
Using external managed database

### DISCUSSION THREAD

**Discussion by dipth** [basecamp/kamal#1351] [General]
I'm having some trouble getting Kamal to deploy an app that is using an external managed postgres database.
Even though I've configured `database.yml` and Kamal to set the database connection correctly to the external service, it seems like Rails is trying to connect to Postgres locally in the docker container:

```
2025-01-10T23:08:45.918129437Z ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory (ActiveRecord::ConnectionNotEstablished)
2025-01-10T23:08:45.918137157Z 	Is the server running locally and accepting connections on that socket?
2025-01-10T23:08:45.918901195Z 
2025-01-10T23:08:45.918922274Z 
2025-01-10T23:08:45.918928154Z Caused by:
2025-01-10T23:08:45.918932994Z PG::ConnectionBad: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory (PG::ConnectionBad)
2025-01-10T23:08:45.918989594Z 	Is the server running locally and accepting connections on that socket?
2025-01-10T23:08:45.919094434Z 
2025-01-10T23:08:45.919105994Z Tasks: TOP => db:prepare
2025-01-10T23:08:45.919460433Z (See full trace by running task with --trace)
2025-01-10T23:08:47.447250341Z bin/rails aborted!
```

Here are my relevant config files:

## config/deploy.yml

```yaml
<% require "dotenv"; Dotenv.load(".env") %>

service: my_app
image: my_org/my_app
servers:
  web:
    - <%= ENV["WEB_01_IP"] %>
proxy:
  ssl: true
  host: my_app.com
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
  clear:
    SOLID_QUEUE_IN_PUMA: true
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "my_app_storage:/rails/storage"
asset_path: /rails/public/assets
builder:
  arch: arm64

```

## .kamal/secrets

```
SECRETS=$(kamal secrets fetch --adapter 1password --account MYACCOUNT --from org/vault KAMAL_REGISTRY_USERNAME KAMAL_REGISTRY_PASSWORD RAILS_MASTER_KEY DATABASE_URL)
KAMAL_REGISTRY_USERNAME=$(kamal secrets extract KAMAL_REGISTRY_USERNAME ${SECRETS})
KAMAL_REGISTRY_PASSWORD=$(kamal secrets extract KAMAL_REGISTRY_PASSWORD ${SECRETS})
RAILS_MASTER_KEY=$(kamal secrets extract RAILS_MASTER_KEY ${SECRETS})
DATABASE_URL=$(kamal secrets extract DATABASE_URL ${SECRETS})
```

## config/database.yml

```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
  <% end %>

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  primary: &primary_production
    <<: *default
    database: my_app_production
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: my_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_app_production_cable
    migrations_paths: db/cable_migrate
```

With this setup Kamal should be pulling the `DATABASE_URL` value from 1Password and inject it as an environment variable in the container, which should then be used by `database.yml`, however it seems to be completely ignores.
I've checked and double-checked that the `DATABASE_URL` entry is correct in 1Password.
