### DISCUSSION TITLE
How to access an accessory web interface other than the default port

### DISCUSSION THREAD

**Discussion by oaltun** [basecamp/kamal#1430] [Q&A]
Hi,

I installed postgres+adminer as accessories.

```
accessories:
  postgres:
    image: postgres:15
    host: ip
    port: 5432
    env:
      clear:
        POSTGRES_DB: domain_db
        POSTGRES_USER: domain_user
      secret:
        - POSTGRES_PASSWORD
    directories:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    host: adminer.domain.com
    port: 8080
```
Now, i can access adminer web ui from port 8080, but i want to close that port. I want to reach to adminer through port 80.

I have been trying following in `accessories/adminer` but that does not work:
```
port: "80:8080"
```
What should i do?
