### DISCUSSION TITLE
How to access one app from another in the same network?

### DISCUSSION THREAD

**Discussion by k0va1** [basecamp/kamal#1483] [Q&A] [answered]
Hi! I have a classic Rails app that is deployed with kamal. I'd like to deploy another Python app on the same machine and i'd like to make it internal(only accessible in the kamal network and not outside). The problem is that I want to send API requests from Rails app to Python app with http. I managed to deploy an app without proxy

```yaml
servers:
  web:
    hosts:
      - "ip"
    options:
      memory: 512M
    proxy: false
```

But I don't know how to access it from Rails app. I usually do it with container name like `http://container_name:4000` but it always changes and contains commit hash. Is there any way to solve this?

**Comment by k0va1** [comment, marked as answer]
I found a solution. It's possible to override container's hostname and after that it's accessible with http://your_beautiful_hostname:PORT from other containers inside the same network. 

```yaml
servers:
  web:
    hosts:
      - "45.138.74.20"
    options:
      memory: 512M
      hostname: your_beautiful_hostname
    proxy: false
```
