### DISCUSSION TITLE
How to connect deployed rails app to a database which already installed on a vps?

### DISCUSSION THREAD

**Discussion by o-200** [basecamp/kamal#1525] [Q&A] [answered]
I have a server that has PostgreSQL installed locally. On this server I need to upload a project and connect to this locally installed PostgreSQL, and I am stuck at the point where the rails are trying to connect to PostgreSQL.

database.yml:
```
production:
  primary: &primary_production
    <<: *default
    database: <%= ENV['DB_NAME'] %>
    username: <%= ENV['DB_USER'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: <%= ENV['DB_HOST'] %>
    port: 5432
```

deploy.yml:
```
service: ...
image: ...

ssh:
  user: ....
  port: ....

servers:
  web:
    - .....

registry:
  username: .....
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - DB_NAME
    - DB_USER
    - DB_PASSWORD
    - DB_HOST
  clear:
    RAILS_ENV: production
    SECRET_KEY_BASE: RAILS_MASTER_KEY

    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "....:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
```

error message:
```
2025-04-23T09:37:27.280486519Z Caused by:
2025-04-23T09:37:27.280694289Z PG::ConnectionBad: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory (PG::ConnectionBad)
2025-04-23T09:37:27.280712209Z  Is the server running locally and accepting connections on that socket?
```

I don't know what I'm doing wrong. Please help me to provide a connection between dockerized rails app and already installed DB on a server.

**Comment by o-200** [comment, marked as answer]
solved:

Docker containers cannot to connect to host using unix socket (https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container). To solve this need to use an internal address to database for connecting.

i've added:
```
servers:
  web:
    hosts:
      - myhostname.net
    options:
      add-host: "host.docker.internal:172.17.0.1" 
```
172.17.0.1 is a default gateway for docker-bridge network, you can try "host.docker.internal:host-gateway"


Before that also pg_hba and postgresconf must be configured for accepting connections. You can also test connectivity using connect inside of container
