### DISCUSSION TITLE
Kamal 2 not making certificates

### DISCUSSION THREAD

**Discussion by shahid-0** [basecamp/kamal#1534] [Q&A]
I want to deploy django application my server already has nginx running with ports 80 and 443 so I have changed the kamal proxy ports to 8888 and 8445.

Kamal Configuration:
```
proxy:
  ssl: true
  # forward_headers: true
  host: app.domain.tld
  # Proxy connects to your container on port 80 by default.
  # app_port: 8000
  healthcheck:
    path: /healthz/
    interval: 2
    timeout: 2
```

Kamal proxy logs
```
{"time":"2025-05-04T07:24:45.05428067Z","level":"INFO","msg":"Healthcheck succeeded"}
{"time":"2025-05-04T07:24:45.054370511Z","level":"INFO","msg":"Target health updated","target":"65e01e2c7085:80","success":true,"state":"healthy"}
{"time":"2025-05-04T07:24:45.054418431Z","level":"INFO","msg":"Deployed","service":"app-web","hosts":["app.domain.tld"],"target":"65e01e2c7085:80"}
```

when I open link in browser with http it shows the Nginx page but on https it gives me ssl handshake error with status code 525
