### DISCUSSION TITLE
compression=zstd

### DISCUSSION THREAD

**Discussion by mustafa0x** [basecamp/kamal#1549] [Q&A]
How can I use zstd compression? Uploading is quite slow. And research indicated that compressing with zstd at build time would improve.

This didn't work
```
builder:
  arch: arm64
  driver: docker
  compression: zstd
  compression-level: 1
```

Edit: fixed; needs to be in `cache:`
