### DISCUSSION TITLE
Preview deployments

### DISCUSSION THREAD

**Discussion by airtonix** [basecamp/kamal#1591] [Q&A]
Deployment to static named environments (dev/stg/prod) I can understand since the configuration used for those would probably be separate kamal config files.

but what about dynamic named environments (aka preview environments), like the kind of thing you'd trigger from a PR ? 

1. Is anyone doing this? 
2. Are people just generating a kamal config file before deploying? or can kamal interpolate the host name from environment variables?

Example

`config/deploy.previewyml`

```yml
service: hey
image: 37s/hey
servers:
  - 192.168.0.1
registry:
  username: registry-user-name
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64

host: pr-$PREVIEW_ID.dev.example.com

env:
  secret:
    - RAILS_MASTER_KEY
```

Then in github actions
```
env:
  PREVIEW_ID="${{ github.event.pull_request.number }}"
run: kamal deploy -d preview
```

I'm curious to know how people are thinking about approaching this scenario
