### DISCUSSION TITLE
Disable traefik?

### DISCUSSION THREAD

**Discussion by danthegoodman1** [basecamp/kamal#345] [Q&A]
I would like to use mrsk to manage deployment of long running workers that have no inbound (they fetch jobs from a queue). Is there any way I can disable traefik so that it does not run, and health checks are via whether the container is running instead?

**Comment by yoelcabo** [comment]
We are also using Kamal exclusively to deploy long-running workers. Our webserver lives somewhere else because we are not ready to fully migrate yet. I found a very simple workaround to deploy it:

```
servers:
  web: # We are not using the webserver, but we need to define it for Kamal to work. We are reusing one of the workers below.
    hosts:
      - my_ip_1
    cmd: bundle exec puma -C config/puma.rb
  workers:
    hosts:
      - my_ip_1
      - my_ip_2
      - my_ip_3
    cmd: bundle exec sidekiq -q my_queue
```
    
 This way, one of the workers also runs a copy of the webserver. That webserver won't receive any other request than Traefik's.

**Reply by sharshenov** [reply]
There is an answer in https://github.com/basecamp/kamal/issues/191
> Yeah, you must have a web role. MRSK is specifically for deploying web apps. 

I have a similar case: A small ruby app (not Rails) that has no web component at all. I enjoy working with Kamal :heart:  and I'd like to use it for non-web apps as well. Having a way to opt-out from traefik would be very convinient.

**Reply by yoelcabo** [reply]
I've submitted a PR: https://github.com/basecamp/kamal/pull/580

**Comment by yoelcabo** [comment]
https://github.com/basecamp/kamal/pull/580 is merged!

From the next version of Kamal (1.3) a configuration like this one would work:

```
servers:
  workers:
    hosts:
      - REDACTED
    cmd: run_worker
    traefik: false

primary_role: workers 
```
