### DISCUSSION TITLE
Limit CPU/Memory usage for accessories?

### DISCUSSION THREAD

**Discussion by Fire-Dragon-DoL** [basecamp/kamal#370] [Q&A] [answered]
Is it possible to configure max memory and cpu usage for app and accessories?

I have background jobs running as accessory, but they take all the cpu when running (very low cost deployment, just 1 small server). I don't care for these jobs to run fast, they could just run at max 20% cpu, even if nobody is using the remaining 80%, it's more important that the web apo stays reactive.

Any suggestions?

**Comment by basiszwo** [comment, marked as answer]
Hopefully you already solved your issue ... 
If anyone comes across this issue, you can add options to define the memory. 

```
options:
  memory: 250m
```

Full example for a redis accessory: 

```
redis:
    image: redis:7.0
    host: 10.0.1.10
    port: 6379:6379
    cmd: --maxmemory 200m --maxmemory-policy allkeys-lru
    volumes:
      - /var/redis/data:/data
    options:
      memory: 250m
```
