### DISCUSSION TITLE
How can I configure Mrsk to not ask for a passphrase every time?

### DISCUSSION THREAD

**Discussion by milushov** [basecamp/kamal#383] [Q&A] [answered]
Every time I run any Mrsk command that establishes a connection with the server, it requests a passphrase:

```
╰─$ mrsk details 
  INFO [f9b706ca] Running docker ps --filter name=^traefik$ on 209.38.*.*
  INFO [2d0fc16a] Running docker ps --filter name=^traefik$ on 178.128.*.*
Enter passphrase for /root/.ssh/id_rsa:Enter passphrase for /root/.ssh/id_rsa:
```

But I can ssh into the machine with no entering passphrase:

```
╰─$ ssh 'root@209.38.*.*' -- date
Thu Jul 13 22:05:32 UTC 2023
```

 
  ```
  ╰─$ mrsk version
0.14.0
  
  ╰─$ which mrsk
mrsk: aliased to docker run --rm -it -v $HOME/.ssh:/root/.ssh -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}/:/workdir  ghcr.io/mrsked/mrsk
```

My `config/deploy.yml`
```
service: awesome

image: milushov/awesome

servers:
  - 209.38.*.*
  - 178.128.*.*

registry:
  server: registry.gitlab.com
  username: milushov

  password:
    - MRSK_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

builder:
  dockerfile: Dockerfile.production
```

<details>
<summary>mrsk config</summary>
<pre><code>
---
:roles:
- web
:hosts:
- 209.38.*.*
- 178.128.*.*
:primary_host: 209.38.*.*
:version: 728d2e0fcc179bb991388d13f10ddb6f464ebae1_uncommitted_bc72ae5d7afddfff
:repository: registry.gitlab.com/milushov/awesome
:absolute_image: registry.gitlab.com/milushov/awesome:728d2e0fcc179bb991388d13f10ddb6f464ebae1_uncommitted_bc72ae5d7afddfff
:service_with_version: awesome-728d2e0fcc179bb991388d13f10ddb6f464ebae1_uncommitted_bc72ae5d7afddfff
:env_args:
- "-e"
- RAILS_MASTER_KEY=[REDACTED]
:volume_args: []
:ssh_options:
  :user: root
  :auth_methods:
  - publickey
:builder:
  dockerfile: Dockerfile.production
:logging:
- "--log-opt"
- max-size="10m"
:healthcheck:
  path: "/up"
  port: 3000
  max_attempts: 7
</code></pre>
  </details>
