### DISCUSSION TITLE
Traefik configuration for two projects

### DISCUSSION THREAD

**Discussion by milushov** [basecamp/kamal#408] [Q&A] [answered]
How do I configure the Mrsk deployment with the classic DHH example that uses one load balancer for two projects?

I'm using DigitalOcean: I have one load balancer and two droplets for two different projects.

---

I can do this without a load balancer, but I don't want to manage SSL myself for each project.

**Comment by nickhammond** [comment, marked as answer]
```
servers:
  web:
    hosts: 867.530.9
    labels:
      traefik.http.routers.hey-web.rule: Host(`example.com`)
  otherweb:
    traefik: true
    hosts: 867.530.8
    labels:
      traefik.http.routers.hey-otherweb.rule: Host(`other.com`)
```
