### DISCUSSION TITLE
Configuring to use main tag

### DISCUSSION THREAD

**Discussion by antarr** [basecamp/kamal#429] [Q&A]
When trying to deploy it's failing with `Error response from daemon: manifest unknown`.  It appears to be related to `Running docker pull ghcr.io/myproect-project/image:fed144f837be160b5ee291a5269854e66876a7b3 `. I think it should be trying to do `Running docker pull ghcr.io/myproect-project/image:main`. Is it possible to force this to happen?

```
    "org.opencontainers.image.revision": "fed144f837be160b5ee291a5269854e66876a7b3",
```
appears under labels, but there is no version with that value on the tag.

***deploy.yml***
```
service: rails-application-mrsk

# Name of the container image.
image: myproject-project/image

# Deploy to these servers.
servers:
  - myserver.com

# Credentials for your image host.
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
env:
  secret:
    - RAILS_ENV
    - RAILS_MASTER_KEY

# Use a different ssh user than root
ssh:
  user: ubuntu
  log_level: debug
```
