### DISCUSSION TITLE
Running Kamal via Docker with Colima

### DISCUSSION THREAD

**Discussion by Antvirf** [basecamp/kamal#433] [Ideas]
Most people are probably on Docker for Mac, but for those of us on [Colima](https://github.com/abiosoft/colima), the alias command provided in Kamal docs doesn't work as the sockets that should be mounted on the container are different. I've also ran into some other issues that I wanted to mention here. My target machine is an x86 Ubuntu box on the local network.

## Troubleshooting SSH connection

With the default alias command, I could not connect to the target machine at all. Using the debug log level, I discovered an issue connecting to ssh-agent. Colima's SSH agent is in a different place so the path of the ssh agent needed to be updated as follows in the alias definition:

```bash
alias kamal='docker run -it --rm \
    -v "$(pwd):/workdir" \
    -v "$(colima ssh eval "echo \$SSH_AUTH_SOCK"):/ssh-agent" \
    -v "/var/run/docker.sock:/var/run/docker.sock" \
    -e SSH_AUTH_SOCK=/ssh-agent ghcr.io/basecamp/kamal:latest'
```

This allowed me to connect to the target machines, though `kamal setup` would fail at the build stage.

## Local builder config - works fine

After trial and error, I foudn this config to work to at least get me past the stage of building the container:

```yaml
# .config/deploy.yml
...
builder:
  multiarch: false
  local:
    arch: arm64
    host: unix:///Users/myusername/.colima/default/docker.sock
```

## Remote builder config - fails

However my target machine is `amd64` and hence in actuality I need to use multiarch, which I have not yet been able to get to work. This is the attempted config:

```yaml
# .config/deploy.yml
builder:
  multiarch: true
  local:
    arch: arm64
    host: unix:///Users/myusername/.colima/default/docker.sock
  remote:
    arch: amd64
    host: ssh://myusername@192.168.0.0
```

And it errors out with the following message:

```
  ERROR (SSHKit::Command::Failed): docker exit status: 256
...
Successfully created context "kamal-app-multiarch-remote-amd64"
ERROR: failed to initialize builder kamal-app-core-multiarch-remote (kamal-app-multiarch-remote0): Cannot connect to the Docker daemon at unix:///Users/myusername/.colima/default/docker.sock. Is the docker daemon running?
```

The target machine is standard ubuntu, so the socket it should use is the default `unix:///var/run/docker.sock`.

Env:
- kamal version v0.16.1
- colima version 0.5.5
