### DISCUSSION TITLE
How to deploy to a non 22 port ssh server

### DISCUSSION THREAD

**Discussion by Code-Farmer-Ming** [basecamp/kamal#493] [Q&A]
I get `docker stderr: docker: open .kamal/env/accessories/my-app-db.env: no such file or directory.` 
when I run `kamal env push    && kamal deploy   `

My deploy.yml file look like:

```yml
# Name of your application. Used to uniquely configure containers.
service: my-app

# Name of the container image.
image: me/my-app

# Deploy to these servers.
servers:
  web:
    - 1.1.1.1:1234

registry:
  username: my_user_name

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD
# Inject ENV variables into containers (secrets come from .env).
env:
  clear:
    DB_HOST: KAMAL_DB_HOST
  secret:
    - RAILS_MASTER_KEY
    - KAMAL_POSTGRES_PASSWORD

accessories:
  db:
    image: postgres:14
    host: 1.1.1.1:1234
    port: 5432
    env:
      clear:
        POSTGRES_USER: KAMAL_POSTGRES_USER
        POSTGRES_DB: KAMAL_POSTGRES_DB
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    host: 1.1.1.1:1234
    port: 6379
    directories:
      - data:/data
```
