### DISCUSSION TITLE
Does Kamal see my ~/.ssh/config?

### DISCUSSION THREAD

**Discussion by milushov** [basecamp/kamal#542] [Q&A]
I want to avoid typing `yes` when viewing logs with the command: `kamal accessory logs elasticsearch -f`

It prompts me to confirm the connection every time

```
$ kamal accessory logs elasticsearch -f
  INFO Following logs on ["answers.wheres.me"]...
  INFO ssh -t root@answers.wheres.me 'docker logs answers-elasticsearch --timestamps --tail 10 --follow 2>&1'
The authenticity of host 'answers.wheres.me (178.120.200.108)' can't be established.
ED25519 key fingerprint is SHA256:477tzorEBJE2JUn7L28BronYdBv/1OwNHbEmQFsCL58.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? <-- I want to avoid this
```

When I run the ssh command directly, it recognizes my ssh config and doesn't request confirmation:

```
$ ssh -t root@answers.wheres.me 'docker logs answers-elasticsearch --timestamps --tail 10 --follow 2>&1'                                                                    
Warning: Permanently added 'answers.wheres.me' (ED25519) to the list of known hosts.
2023-10-22T05:24:55.898740210Z {"@timestamp":"2023-10-22T05:24:55.895Z", "log.level": "INFO", "message":"loaded module [search-business-rules]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.plugins.PluginsService","elasticsearch.node.name":"c8453f03796b","elasticsearch.cluster.name":"elasticsearch"}
```

**Question is:** How to tell Kamal to `StrictHostKeyChecking no` or how to make Kamal recognize my `~/.ssh/config`?

My ssh config` ~/.ssh/config`:

```
Host *
  AddKeysToAgent yes
  Compression yes
  ControlMaster no
  ControlPath /tmp/%r@%h:%p
  ControlPersist yes
  ForwardAgent yes
  ServerAliveInterval 120
  StrictHostKeyChecking no <---- this allows to not confirm the connection every time
  TCPKeepAlive yes
  UseKeychain yes
  UserKnownHostsFile /dev/null%
```

My kamal config:
```
service: answers

image: milushov/answers

volumes:
  - rails_storage:/rails/storage

ssh:
  log_level: info

# Before initial Traefik setup:
# https://github.com/mrsked/mrsk/discussions/112#discussioncomment-5332424
# mkdir -p /letsencrypt && touch /letsencrypt/acme.json && chmod 600 /letsencrypt/acme.json
traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls: true
    entrypoints.websecure.http.tls.domains[0].main: "answers.wheres.me"
    certificatesResolvers.letsencrypt.acme.email: "milushov.r@gmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
    accesslog: true
    log.level: INFO

servers:
  web:
    hosts:
      - answers.wheres.me
    labels:
      traefik.http.routers.answers.rule: Host(`answers.wheres.me`)
      traefik.http.routers.answers_secure.entrypoints: websecure
      traefik.http.routers.answers_secure.rule: Host(`answers.wheres.me`)
      traefik.http.routers.answers_secure.tls: true
      traefik.http.routers.answers_secure.tls.certresolver: letsencrypt

  job:
    hosts:
      - answers.wheres.me
    cmd: bundle exec sidekiq -C config/sidekiq.yml

registry:
  server: registry.gitlab.com
  username: milushov
  password:
    - KAMAL_REGISTRY_PASSWORD

# These ENVs required for runtime
env:
  clear:
  secret:
    - SECRET_KEY_BASE
    - RAILS_MASTER_KEY
    - REDIS_URL

builder:
  dockerfile: Dockerfile.production
  multiarch: false
  secrets:
    - SECRET_KEY_BASE
    - RAILS_MASTER_KEY

# NOTICE: after updating envs, don't forget to run `kamal setup`
accessories:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    roles:
      - web
    port: 9200
    files:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    directories:
      - ./esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    roles:
      - web
    files:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    port: 5601

  redis:
    image: redis:7.2.0-alpine
    roles:
      - web
    port: 6379
    cmd: redis-server /etc/redis.conf --save 300 1 --requirepass <%= URI.parse(ENV['REDIS_URL']).password %>
    directories:
      - ./redis:/data
    files:
      - ./config/redis.conf:/etc/redis.conf
```
