### DISCUSSION TITLE
Question: Should I use docker restart: "no" for running migrations?

### DISCUSSION THREAD

**Discussion by nuschk** [basecamp/kamal#568] [Ideas]
Hey all

I've seen the discussions about migrations, basically recommending to run it as a separate `kamal app exec` command after the deploy went through, and then use feature flags to make both versions work against both schemas. Fine and all, yet a bit... cumbersome, especially for small teams.

Yet, as another idea, is there something stopping me doing it like so:

```yaml
servers:
  web:
    hosts:
    cmd: python gunicorn <wsgi_app>
  migrate:
    cmd: python ./manage.py migrate
    options:
      restart: "no"
```

It's a bit weird in that the resulting docker command has now both restart option (`--restart unless-stopped --restart "no"`), but the latter one seems to win, yay.

The upside is, I think, migrations are applied at the start of the deployment cycle. This makes it easier overall, since you don't *have* to have feature flags, you just have to make sure old versions work with the new schema. That is easily done, as long as you're not removing fields from the schema.

Any thoughts?
