### DISCUSSION TITLE
Traefik request buffering

### DISCUSSION THREAD

**Discussion by nuschk** [basecamp/kamal#571] [Q&A] [answered]
I'm using django with gunicorn, which requires request buffering, so as to not be susceptible to Slowloris and other attacks. I would think that rails/unicorn has the same requirement.

I managed to get it working with the following entries in deploy.yml:

```yaml
traefik:
  args:
    entryPoints.http.address: ":80"
    entryPoints.http.http.middlewares: buffering-mw

servers:
  web:
    hosts:
    cmd: python gunicorn <my_app> --bind=3000 # ...
    labels:
      traefik.http.middlewares.buffering-mw.buffering.maxRequestBodyBytes: 5000000
      traefik.http.middlewares.buffering-mw.buffering.memRequestBodyBytes: 5000000
      traefik.http.middlewares.buffering-mw.buffering.maxResponseBodyBytes: 5000000
      traefik.http.middlewares.buffering-mw.buffering.memResponseBodyBytes: 5000000
```

I have the following questions:

- Does this seem right to you? It certainly works...
- Does it seem fine, architecturally to do it in Traefik? Where do you guys buffer requests?
- Would it be a good idea to bake request buffering into Kamal? 

Thanks!
