### DISCUSSION TITLE
How to use local sqlite database?

### DISCUSSION THREAD

**Discussion by sedubois** [basecamp/kamal#596] [Q&A] [answered]
I want to deploy a demo Rails app to a single VPS using SQLite (DHH [wrote](https://github.com/basecamp/kamal/issues/3#issuecomment-1375485282) that for a project _"which is going to be deployed to a single server, you should just use sqlite"_). However I didn't find details on how to configure Kamal with sqlite (`config/deploy.yml` and `config/database.yml`). Any hints? The setup I tried resulted in `kamal setup` throwing `bind: address already in use`.

**Comment by sedubois** [comment, marked as answer]
`address already in use` was because nginx was already running on the server and blocking port 80.

For anyone interested, the setup below allowed me to deploy a Rails app with SQLite to a single server. The `volumes` part is to persist the DB between deploys.

config/deploy.yml:
```yml
service: ...
image: ...
servers:
  - <ip address>
registry:
  username: ...
  password:
    - KAMAL_REGISTRY_PASSWORD
volumes:
  - "storage:/rails/storage"
env:
  secret:
    - RAILS_MASTER_KEY
```

config/database.yml (default - left untouched):
```yml
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  database: storage/production.sqlite3
```
