### DISCUSSION TITLE
Deploy django project and flower

### DISCUSSION THREAD

**Discussion by Hamza-abughazaleh** [basecamp/kamal#610] [General]
## trying to deploy a Django project with Flower each one on a separate server 

**deploy.yml** 
```
# Name of your application. Used to uniquely configure containers.
service: backend

# Name of the container image.
image: backend

env:
  secret:
   all secrets


# Deploy to these servers.
servers:
  web:
    hosts:
      - <first IP>
    cmd: ./start.sh web
    healthcheck:
      path: health
      port: 8000
      interval: 5s
    labels:
      traefik.enable: true
      traefik.http.routers.djangobase-web.rule: 'Host(`domain name`)'
  worker:
    hosts:
      - <first IP>
    cmd: ./start.sh worker
  scheduler:
    hosts:
      - <first IP>
    cmd: ./start.sh scheduler
  flower:
    labels:
      traefik.enable: true
      traefik.http.routers.flower-web.rule: 'Host(`domain name`)'
    hosts:
      - <second IP>
    cmd: ./start.sh flower
    healthcheck:
      path: /
      port: 8000
      interval: 5s

# Credentials for your image host.
registry:
  digital ocean
  username:
    - API-TOKEN 
  password:
    -API-TOKEN 


# Use a different ssh user than root
ssh:
  user: user-name


traefik:
  # Expose traefik on 8080
  host_port: 8080
``` 

**docker file**
```
# Use an official Python runtime as a parent image
FROM python:3.11-slim

# create the app user
RUN addgroup --system app && adduser --system --group app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=app.settings

# Set the working directory in the container
WORKDIR /app
RUN mkdir /app/staticfiles /app/uploadedfiles

RUN apt update && apt upgrade -y

RUN apt update \
  && apt install -y --no-install-recommends build-essential libpq-dev pkg-config\
  && rm -rf /var/lib/apt/lists/*

RUN apt update && apt install -y --no-install-recommends curl && apt clean && rm -rf /var/lib/apt/lists/*

RUN apt update && apt install -y --no-install-recommends default-libmysqlclient-dev && rm -rf /var/lib/apt/lists/*
RUN apt update && apt install -y --no-install-recommends postgresql-client && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container at /app/
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app/
COPY code files

# Copy start script into the container
COPY bin/start.sh /app/start.sh

# Make the start script executable
RUN chmod +x /app/start.sh

RUN chown -R app:app /app
# change to the app user
USER app

EXPOSE 8000

CMD ["/app/start.sh", "web"]
``` 
**start.sh file**
```
#!/bin/bash

if [ "$1" == "web" ]; then
  # Wait for PostgreSQL to become available
  while ! pg_isready -h "${POSTGRES_DB_HOST}" -p "${POSTGRES_DB_PORT}" -U "${POSTGRES_DB_USER}"; do
      echo "Retrying pg_isready"
      sleep 1
  done
  set +x
  echo "PostgreSQL started."

  python manage.py collectstatic --noinput

  # Apply database migrations
  echo "Applying database migrations..."
  python manage.py migrate

  # Start the Django development server
  echo "Starting Django development server..."
  gunicorn --bind 0.0.0.0:8000 --timeout 120 app.wsgi:application

elif [ "$1" == "worker" ]; then
  shift
  celery -A app worker -E -l WARNING -n appCelery

elif [ "$1" == "scheduler" ]; then
  shift
  celery -A app beat -l WARNING

elif [ "$1" == "flower" ]; then
  shift
  celery -A app flower --port=8000
fi
``` 
The Django and Flower works on port 8000
when I access the first IP with port 8080 it's working fine but when I access the second IP with port 8080 it's not running the flower UI
Does anyone know how I can fix this issue?
