### DISCUSSION TITLE
Map web mount to same parent dir like accessories

### DISCUSSION THREAD

**Discussion by bitsmyth** [basecamp/kamal#623] [Show and tell]
Using `directories` on accessories is creating folders in the current users path and mounts them later to the their docker containers. I liked this structure but was annoyed why I can't achieve the same with the web role. After a little bit of tinkering I wanted to share my approach.

```
service: my_app
servers:
  web:
    hosts:
      - 200.10.10.200
      
volumes:
  - $PWD/my_app-rails/data:/rails/storage
```
