### DISCUSSION TITLE
How to deploy a wordpress site?

### DISCUSSION THREAD

**Discussion by kishaningithub** [basecamp/kamal#625] [Q&A] [answered]
It would be great to have an example which explains how to deploy a wordpress site just like the below one which explains the same using docker compose. 

https://github.com/docker/awesome-compose/tree/master/official-documentation-samples/wordpress/

Thanks in advance! 😊

**Comment by kishaningithub** [comment]
I feel the Kamal documentation should contain a cookbook section which in addition to the example requested above should contain tips, caveats and best practices when using kamal

**Comment by kishaningithub** [comment]
I tried doing this but ended up with the following error

```bash
ERROR (Kamal::Commands::Builder::Base::BuilderError): Missing Dockerfile
```

and there seems to be no option (unless i am missing something) to disable this builder thing because in my case i only want to pull wordpress image and not build and push something.

**Reply by aka47** [reply, marked as answer]
This is a very board question, usally you create a project with a Dockerfile. Here is the one I am using. You should have a look at the Wordpress Docker documentation, it is worth reading.

I use hetzner with a volume mounted under /mnt/volume-wordpress-data where all uploads and static files are stored.

```
FROM wordpress:latest

### Dependency Installation
RUN apt update && \
    apt upgrade -y && \
    apt install -y python3 vim less && \
### WP-CLI Installation
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/bin/wp-cli && \
    chmod 755 /usr/bin/wp-cli && \
    a2enmod headers && 
    
### Cleanup
    rm -rf /var/cache/apt/*

# Copying Themes and Plugins into the wordpress image
COPY ["themes","/usr/src/wordpress/wp-content/themes"]
COPY ["plugins","/usr/src/wordpress/wp-content/plugins"]

# Applying the execution right on the folders for apache
COPY entrypoint-child.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint-child.sh

# Updating the configuration of wordpress image with our own
COPY ./config/uploads.ini /usr/local/etc/php/conf.d/uploads.ini
COPY ./config/docker-apache.conf /etc/apache2/conf-enabled/docker-apache.conf

EXPOSE 8080

ENTRYPOINT ["entrypoint-child.sh"]
CMD ["apache2-foreground"]
```
my deploy.yaml looks like this, I have a wp multisite so it is a bit more complex. Some parts have I move into a traefik.yaml file 

```
# Name of your application. Used to uniquely configure containers.
service: wordpresses

# Name of the container image.
image: githubusername/wordpresses

# Deploy to these servers.
servers:
  web:
    hosts:
      - xxx.xxx.xxx.xxx
    labels:
      traefik.http.routers.wp.rule: "Host(`xxxx.com`) || Host(`xxx.de`)"
      traefik.http.routers.wp_secure.entrypoints: websecure
      traefik.http.routers.wp_secure.rule: "Host(`xxxx.com`) || Host(`xxxx.de`)"
      traefik.http.routers.wp_secure.tls: true
      traefik.http.routers.wp_secure.tls.certresolver: letsencrypt

volumes:
  - "/mnt/volume-wordpress-data/wordpress-data:/var/www/html"

  - config/apache/:/tmp/apache3/
# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: xxxx

  # Always use an access token rather than real password when possible.
  password:
    - GITHUB_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    WORDPRESS_DB_HOST: xxx.xxx.xxx.xxx
    WORDPRESS_DB_NAME: wordpresses

  secret:
    - WORDPRESS_DB_USER
    - WORDPRESS_DB_PASSWORD
    - WORDPRESS_DB_NAME

accessories:
  db:
    image: mariadb:lts
    host: xxx.xxx.xxx.xxx
    port: 3306
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
      secret:
        - MARIADB_ROOT_PASSWORD
    files:
      - db/wordpress-backup-290224.sql:/docker-entrypoint-initdb.d/setup.sql
    volumes:
      - "/mnt/volume-wordpress-data/mysql-data:/var/lib/mysql"

traefik:
  options:
    publish:
      - "443:443"
  files:
    - config/traefik.yaml:/etc/traefik/traefik.yaml
  directories:
    - config/apache/:/tmp/apache/
  volumes:
    - "/config/apache:/tmp/apache2/"
    - "/mnt/volume-wordpress-data/letsencrypt/acme.json:/letsencrypt/acme.json"
  

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /
  port: 8080
```
