### DISCUSSION TITLE
Seeking Advice on Automated Backups

### DISCUSSION THREAD

**Discussion by jspooner** [basecamp/kamal#654] [Q&A]
Hello,

I am currently in the process of deploying a Rails application using Kamal. The app is structured with three Docker images: Rails, Redis, and PostgreSQL. As I prepare for production, my main concern is to set up automated backups.

While I am technically equipped to implement this, I wonder if there's a specific "Kamal way" to handle interactions with accessories like backups.  Can I write custom kamal commands like `kamal accessory db backup`?

I'm particularly interested in methods that avoid the need to manually provision the server with cron jobs and backup scripts. How are others in the community approaching this?  Are you deployed with Docker and managing your own backups, or are you using a service like RDS?

I'm curious to learn about the different strategies and would greatly appreciate your insights.

Thank you!

**Comment by acidtib** [comment]
I run an accessory that handle the automatic backup and uploads it to an S3 bucket 

```

accessories:
  # ...
  
  s3_backup:
    image: eeshugerman/postgres-backup-s3:16
    host: 192.168.0.1
    env:
      clear:
        SCHEDULE: '@daily'
        BACKUP_KEEP_DAYS: 30
        S3_REGION: your-s3-region
        S3_BUCKET: your-s3-bucket
        S3_PREFIX: backups
        S3_ENDPOINT: https://your-s3-endpoint
        POSTGRES_HOST: my_awesome_app-db
        POSTGRES_DATABASE: my_awesome_app_production
        POSTGRES_USER: my_awesome_app
      secret:
        - POSTGRES_PASSWORD
        - S3_ACCESS_KEY_ID
        - S3_SECRET_ACCESS_KEY

```

Here's a post talking about it https://www.botzenhart.io/articles/how-to-deal-with-postgresql-backups-using-kamal
