### DISCUSSION TITLE
Setting up vector via accessories

### DISCUSSION THREAD

**Discussion by morgoth** [basecamp/kamal#670] [Show and tell]
Setting up [vector](https://vector.dev/) via accessories can be done like this:
```yaml
accessories:
  vector:
    image: timberio/vector:0.35.0-debian
    cmd:
    hosts:
      - <host-1-ip>
      - <host-2-ip>
    port: "8686:8686"
    volumes:
      - /root/vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
```
where one have to setup `/root/vector.yaml` on the root host.

My usecase was to integrate https://betterstack.com/ and the config for it (after registering and setting up account) can be fetched via `curl https://logs.betterstack.com/vector-yaml/docker/<VECTOR_TOKEN> -o /root/vector.yaml`

**Comment by morgoth** [comment]
Simplified setup of vector service:

```yml
accessories:
  vector:
    image: timberio/vector:0.37.1-alpine
    hosts:
      - <host-1-ip>
      - <host-2-ip>
    env:
      secret:
        - VECTOR_TOKEN
    port: "8686:8686"
    files:
      - config/vector.yaml:/etc/vector/vector.yaml:ro
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

This way you can keep `config/vector.yaml` file locally in repo and have full control over it. The VECTOR_TOKEN is passed as secret env variable.
