### DISCUSSION TITLE
referencing accessories by container name?

### DISCUSSION THREAD

**Discussion by gammons** [basecamp/kamal#673] [Q&A] [answered]
Hi there,

What's the best way to reference accessories?  As far as I understand it, the only option to reference an accessory is by its internal, docker-based ip address.  That isn't ideal for a lot of reasons.  Does (or could) kamal create a bridge network so that running containers can reference accessories by their container name?  Or am I not understanding something?  Thanks!

**Comment by acidtib** [comment, marked as answer]
@gammons This can be achieved if you run the web app and accessory on the same server, create a docker network on the server, then define the network on `deploy.yml`

create a network on the server
`docker network create -d bridge private`

set server and accessory network config
```
servers:
  web:
    hosts:
      - xx.xx.xx.xx
    options:
      network: "private"
```


```
accessories:
  db:
    image: mariadb:latest
    host: xx.xx.xx.xx
    port: 3306
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
      secret:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
    options:
      network: "private"
    directories:
      - data:/var/lib/mysql
```

**Reply by gammons** [reply]
That's perfect @acidtib .  Thank you!

**Reply by corvuszero** [reply]
As stated [here](https://github.com/basecamp/kamal/issues/1091): If you have a host and need to call an accessory: Deploy the accessory to that same host and set its `options.network-alias` in `deploy.yml`, this way you can call it using that same network alias in the main app. I have an accessory that only a specific role needs so this was very useful.

**Comment by geetotes** [comment]
As an alternative to setting up a docker network, you could also use the service param in the accessory definition 

```
accessories:
  tika:
    host: xx.xx.xx.xx
    service: tika
    image: apache/tika:latest
    port: "127.0.0.1:9998:9998"
 ```

Assuming that this accessory is on the same host as the main "web" application, assigning the string `tika` to the `service` param allows me to access it from my rails app with `http://tika:9998" 

(if you omit the `service` param, the networking will default to `<service-name>-<accessory>`  as defined [here](https://kamal-deploy.org/docs/configuration/accessories/#service-name)

**Reply by charnould** [reply]
Hello,
I tried to use your solution to serve `Ollama` (I want to be able to `fetch('http://localhost:11434/api` from my app):

```
accessories:
  ollama:
    service: ollama
    image: ollama/ollama
    host: 157.90.xxx.xxx (my IP)
    port: '127.0.0.1:11434:11434'
```

Then `kamal accessory boot ollama`

But I got this error:

`ERROR (SSHKit::Command::Failed): Exception while executing on host 157.90.xxx.xxx: docker exit status: 125
docker stdout: Nothing written
docker stderr: flag needs an argument: 'p' in -p`

The message doesn't give clues...
Any idea?
Thanks.

**Reply by geetotes** [reply]
Are you missing `:latest` when you define the ollama image?

i.e.
`image: ollama/ollama:latest`

**Reply by charnould** [reply]
Thanks. I think it was `port`.  
This works:
```
accessories:
  ollama:
    service: ollama
    image: ollama/ollama
    host: your-ip
```
