### DISCUSSION TITLE
How to get target server IP address during multi-host accessory deployment?

### DISCUSSION THREAD

**Discussion by sulo1337** [basecamp/kamal#686] [Q&A]
I'm trying to bind ports only to tailscale IP. However, publish will bind ports to 0.0.0.0.
How can I access IP `100.64.1.1` or `100.64.1.2` based on what server the accessory is being deployed on?
Example:

```yaml
servers:
  roleA:
    hosts:
      - 100.64.1.1
      - 100.64.1.2

accessories:
  accessory1:
    image: some/image:latest
    roles:
      - roleA
    options:
      publish:
        - "$TAILSCALE_IP:80:80" # how can i set this $TAILSCALE_IP based on the host where kamal is deploying the accessory?
        - "`tailscale ip | head -n 1`:443:443" # i tried this but kamal escapes all shell characters like $, \ and `
        - "<%= '' =>:80:80" # any ruby templates I use runs on the kamal controller but not the target
```

Any way I can run arbitrary command in the target host before deploying accessory to set a variable which I can use during the runtime ? Or is there any way I can grab on to the target host currently being worked on by kamal?
