### DISCUSSION TITLE
Adding pre-command hook

### DISCUSSION THREAD

**Discussion by morgoth** [basecamp/kamal#713] [Ideas]
I would like to ask for a feedback if the hook that is run before executing any of the kamal command would be useful to more people?

My usecase is to set up AWS config, so the AWS services are reachable. Currently I'm doing it like this:
```yml
# my config/deploy.yml
<% ENV["AWS_PROFILE"] = "kamal-servers" unless ENV["CI"] %>

registry:
  server: xxx.amazonaws.com
  username: AWS
  password: <%= %x(aws ecr get-login-password) %>
```

Here, locally I'm having few AWS profiles, and based on the app/destination I want to choose the proper one.
On the CI, where the CD is implemented I don't need any profiles switching.

With the pre-command hook this could be done transaprently to the final `config/deploy.yml`

What do you think?

**Comment by eduardoyutaka** [comment]
Hey @morgoth!

If I understood correctly, you can set up a different profile just by editing the command that generates the temporary password

```yaml
# my config/deploy.yml
<% ENV["AWS_PROFILE"] = "kamal-servers" unless ENV["CI"] %>

registry:
  server: xxx.amazonaws.com
  username: AWS
  password: <%= %x(aws ecr get-login-password --profile YOUR_PROFILE) %> # change this line
  ```
