### DISCUSSION TITLE
no implicit conversion of Array into String

### DISCUSSION THREAD

**Discussion by netng** [basecamp/kamal#763] [Q&A]
Hi everyone,

I've just started using Kamal and encountered an error like this:

```
hellodev@DESKTOP-767E2RC:~/dev/blog$ kamal setup
Acquiring the deploy lock...
  INFO [8ecdd9aa] Running docker -v on 192.168.100.10
  INFO [8ecdd9aa] Finished in 0.835 seconds with exit status 0 (successful).
  INFO [fd924348] Running /usr/bin/env mkdir -p $PWD/blog-db/data on 192.168.100.10
  INFO [fd924348] Finished in 0.833 seconds with exit status 0 (successful).
Releasing the deploy lock...
  Finished all in 5.8 seconds
  ERROR (TypeError): Exception while executing on host 192.168.100.10: no implicit conversion of Array into String
```

`deploy.yml`

```
# Name of your application. Used to uniquely configure containers.
service: blog

# Name of the container image.
image: mydockhub/blog

# Deploy to these servers.
servers:
  - 192.168.100.10

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: mydockhub

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
env:
  clear:
    DB_HOST: 192.168.100.10
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  volumes:
    - storage:/rails/storage

# Use a different ssh user than root
ssh:
  user: ubuntu

# Configure builder setup.
# builder:
#   args:
#     RUBY_VERSION: 3.2.0
#   secrets:
#     - GITHUB_TOKEN
#   remote:
#     arch: amd64
#     host: ssh://app@192.168.0.1

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: postgres:16.2
    host: 192.168.100.10
    port: 5432
    env:
      # clear:
        # MYSQL_ROOT_HOST: '%'
      secret:
        - POSTGRES_PASSWORD
    files:
      # - config/mysql/production.cnf:/etc/mysql/my.cnf
      - db/production.sql.erb:/docker-entrypoint-initdb.d/setup.sql
    directories:
      # - data:/var/lib/mysql
      - data:/var/lib/postgresql
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data

# Configure custom arguments for Traefik
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
# healthcheck:
#   path: /healthz
#   port: 4000

```

How can I fix it? I couldn't find any clues on the internet regarding this error. Thank you.
