### DISCUSSION TITLE
Allow different Logging Configuration per Accessory, different that  Application or the default one

### DISCUSSION THREAD

**Discussion by joaquindiez** [basecamp/kamal#781] [Ideas]
I can setup the loggin driver, but is apply to all the containers that I am starting, Traefick, web, db,. ( all the accessories)

I think will be more powerful to being able to setup the logging drive to each container, independly

like this

```
service: my_app

image: image

servers:
   web:
     hosts:
      - aaa.bbb.ccc.ddd
     options:
        network: "private" # This is important!

registry:
  username: user
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DATASOURCES_DEFAULT_USERNAME: "postgres"
    DATASOURCES_DEFAULT_URL: "jdbc:postgresql://my_app-db:5432/my_awesome_app_production"
  secret:
    - DATASOURCES_DEFAULT_PASSWORD

accessories:
  db:
    image: postgres:16
    host: aaa.bbb.ccc.ddd
    env:
      clear:
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "my_awesome_app_production" # The database will be created automatically on first boot.
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    options:
      network: "private" # This is important!
     logging:
   driver: syslog
      options:
        syslog-address: "tcp+tls://other_server.com"
        tag: "my.app.kamal.db:"

traefik:
  options:
    network: "private"
  logging:
    driver: syslog
    options:
      syslog-address: "tcp+tls://xxxxxx.com"
      tag: "my.app.kamal.traefik:"

logging:
  driver: syslog
  options:
    syslog-address: "tcp+tls://xxxxxx.com"
    tag: "my.app.kamal.app:"
```
