### DISCUSSION TITLE
GitHub/Gitlab container registries?

### DISCUSSION THREAD

**Discussion by hrstoyanov** [basecamp/kamal#793] [Q&A] [answered]
The documentation describes how to use Docker, AWS, Google container image registries, but what about GitHub/Gitlab - they also provide such services?

Thanks.

**Comment by morgoth** [comment, marked as answer]
It's possible.
For GH it looks like this:
```yml
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_TOKEN
```

Where KAMAL_REGISTRY_USERNAME is your GH username and KAMAL_REGISTRY_TOKEN is your personal access token.

Probably similar config is needed for Gitlab, but I never used it.
