### DISCUSSION TITLE
Uploading image to Digital Ocean's Registry throws an error

### DISCUSSION THREAD

**Discussion by bntzio** [basecamp/kamal#804] [General]
I'm trying to deploy a rails app with kamal by pushing the app image to the digital ocean registry instead of the default registry (which is docker hub) but I'm getting an authentication error:

```
ERROR: failed to solve: failed to push registry.digitalocean.com/<my_registry>/<my_repo>:<my_tag>: failed to do request: Head "https://sfo3.digitaloceanspaces.com/[REDACTED]": dial tcp: lookup sfo3.digitaloceanspaces.com on <my_server_ip>: no such host
```

Using:

```yml
# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  server: registry.digitalocean.com
  username:
    - KAMAL_REGISTRY_PASSWORD

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD
```

### Steps to reproduce:

1. Create a DO droplet and configures firewall (outbound requests are fully open)
2. Create a DO container image registry
3. Install `kamal` and modify the `deploy.yml` config file to set up hosts, traefik, volumes, and registry
4. Set `KAMAL_REGISTRY_PASSWORD` in the `.env` file, along with `RAILS_MASTER_KEY`
5. Run `kamal setup`

My `KAMAL_REGISTRY_PASSWORD` is a Digital Ocean personal access token with scopes `registry (4): create, read, update, delete` (I've also tried with a full access scope and the same error is thrown).

Seems that Digital Ocean stores the image layers in Digital Ocean Spaces which in turn requires its own Spaces Key to access, that's my guess.

**Comment by mguidetti** [comment]
I believe for Digital Ocean specifically you must use your registered account email address as the registry username

**Reply by bntzio** [reply]
Ok I'll try it later today, thank you! :)

**Reply by bntzio** [reply]
Didn't work.

**Comment by igor-alexandrov** [comment]
@bntzio for DigitalOcean you should add account name to the server address. Below is the config that works in one of my deploys.

```
# Credentials for your image host.
registry:
  server: registry.digitalocean.com/jetrockets

  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
```

**Reply by bntzio** [reply]
Ah makes sense, thank you very much!

I'll try it later today to see if it works :)

**Reply by misterhtmlcss** [reply]
@bntzio so did it work? I am in a similar pickle and I'd like to know if you because unstuck or not. :)

**Reply by bntzio** [reply]
@misterhtmlcss Oops, I forgot to try it, I can do it in 30 min.

**Reply by bntzio** [reply]
Sorry for the delay @misterhtmlcss but nope, it didn't work, I don't know what's happening but for the time being I'm not using Digital Ocean for my registry, using GitHub Packages at the moment, that works.

**Reply by fabriciocarboni** [reply]
@bntzio Could you please share your conf for ghcr.io? Im having a problem pushing to ghcr.io as described [here](https://github.com/basecamp/kamal/discussions/1389#discussioncomment-12096550). Id like to know if im missing something in my conf.

Thank you!

**Comment by leegeng** [comment]
@bntzio
I got the same error, and I tried changing the registry.server value without the account name (e.g., registry.digitalocean.com). My image name is xxx/yyy (where xxx is the registry name and yyy is the repository name).

**Comment by mooktakim** [comment]
Not sure who needs this, but this worked for me:
```yaml
# Name of the container image.
image: registryname/app_name

# Credentials for your image host.
registry:
  server: registry.digitalocean.com
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
```

and my `.env`:
```
KAMAL_REGISTRY_USERNAME="do@example.com"
KAMAL_REGISTRY_PASSWORD="API_KEY_123"
```
