### DISCUSSION TITLE
How to configure traefik to proxy to the port used by the backend

### DISCUSSION THREAD

**Discussion by defp** [basecamp/kamal#875] [General]
The app container expose two port 22 and 30000
<img width="2492" alt="image" src="https://github.com/basecamp/kamal/assets/612381/01581bfc-701d-4b6f-9960-546bf1633098">

traefik send request to 22,  but the web server listen 30000, traefik should proxy request to 30000 port

```
2024-07-05T10:45:27.314162524Z time="2024-07-05T10:45:27Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 172.17.0.4:22: connect: connection refused"
```

the request should be forward to 30000 port 

I add `EXPOSE 30000` to Dockerfile， but not work

<img width="643" alt="image" src="https://github.com/basecamp/kamal/assets/612381/15702583-12b7-451e-baae-def5a6f30ad4">

**Comment by acidtib** [comment]
hi @defp can you share your deploy.yml config

**Reply by defp** [reply]
@acidtib 

```
# Name of your application. Used to uniquely configure containers.
service: dataengine-ai

# Name of the container image.
image: kamal/dataengine-ai

# Deploy to these servers.
servers:
  web:
    hosts:
      # - 10.3.56.150
      - 10.3.56.132
      # - 10.3.56.151
    options:
      gpus: all

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  server: registry.domain
  username: user

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD
# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    MODELS_PATH: /root/models
    SENTRY_ENV: dev
  secret:
    - DATABASE_HOST
    - DATABASE_NAME
    - DATABASE_USER
    - DATABASE_PORT
    - DATABASE_PASSWORD
    - ES_ADDRESS
    - ES_USERNAME
    - ES_PASSWORD
    - ES_DRUG_APPROVAL_NUMBER_BUSINESS_INDEX
    - REDIS_HOST
    - REDIS_PORT
    - REDIS_DB
    - REDIS_USERNAME
    - REDIS_PASSWORD

# Use a different ssh user than root
# ssh:
#   user: app

# Configure builder setup.
# builder:
#   args:
#     RUBY_VERSION: 3.2.0
#   secrets:
#     - GITHUB_TOKEN
#   remote:
#     arch: amd64
#     host: ssh://app@192.168.0.1

builder:
  remote:
    arch: amd64
    host: ssh://root@10.3.56.160
# Use accessory services (secrets come from .env).
# accessories:
#   db:
#     image: mysql:8.0
#     host: 192.168.0.2
#     port: 3306
#     env:
#       clear:
#         MYSQL_ROOT_HOST: '%'
#       secret:
#         - MYSQL_ROOT_PASSWORD
#     files:
#       - config/mysql/production.cnf:/etc/mysql/my.cnf
#       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
#     directories:
#       - data:/var/lib/mysql
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data

# Configure custom arguments for Traefik. Be sure to reboot traefik when you modify it.
traefik:
  image: uhub.service.ucloud.cn/nocode-mirrors/traefik:v2.10
  host_port: 10086
  args:
    accesslog: true
    accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /health
  port: 30000
  max_attempts: 15

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
# If your app is using the Sprockets gem, ensure it sets `config.assets.manifest`.
# See https://github.com/basecamp/kamal/issues/626 for details
#
# asset_path: /rails/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Configure the role used to determine the primary_host. This host takes
# deploy locks, runs health checks during the deploy, and follow logs, etc.
#
# Caution: there's no support for role renaming yet, so be careful to cleanup
#          the previous role on the deployed hosts.
# primary_role: web

# Controls if we abort when see a role with no hosts. Disabling this may be
# useful for more complex deploy configurations.
#
# allow_empty_roles: false

volumes:
  - /root/models/:/root/models/
  - /root/.paddleocr:/root/.paddleocr

```
