### DISCUSSION TITLE
Access .env variables in Dockerfile

### DISCUSSION THREAD

**Discussion by sevab** [basecamp/kamal#888] [Q&A] [answered]
I'm trying to access `.env` variables as part of my Docker build process in the `Dockerfile`, e.g.

 in .env I have
```
AWS_ACCESS_KEY_ID=...
AWS_SECRET_ACCESS_KEY=...
```

As per the documentation, I then expose them to the builder like so in `deploy.yml`:
```
builder:
  cache:
    type: registry
  secrets:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
```

but when I try to access them in the Dockerfile:
```
ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
RUN aws s3 sync ....
```

They aren't accessible (in my case `aws s3 sync` breaks with `fatal error: Unable to locate credentials`).

Anybody can point out how to access `.env` vars in Dockerfile?
