### DISCUSSION TITLE
Custom SSL cert path config

### DISCUSSION THREAD

**Discussion by randohinn** [basecamp/kamal#893] [Q&A]
What config keys should I use to pass traefik a custom cert, instead of having it use LE?

**Comment by kpumuk** [comment]
Not very relevant now that Kamal 2 will include kamal-proxy instead of traefik, but in case you (or anybody else) is looking for an answer, the solution is:

1. Put certificates somewhere on the disk, like `/data/cert`
2. Create a yml configuration `/data/cert/tls.yml`:
   ```yaml
   tls:
     certificates:
       - certFile: /certs/app.example.com.cert
         keyFile: /certs/app.example.com.key
   ```
3. Mount the volume to traefix and set the `providers.file.filename` argument:
   ```yaml
   traefik:
     options:
       volume:
         - "/data/certs:/certs"
       network: private
     args:
       providers.file.filename: "/certs/tls.yml"
   ```
