### DISCUSSION TITLE
Docker authorization failed on kamal deploy

### DISCUSSION THREAD

**Discussion by csalmeida** [basecamp/kamal#896] [Q&A]
Hi everyone, I have been managing to deploy an app with Kamal with these Docker credentials for a few days with no issues but now I am getting the following error and I'm unsure as to why that might be happening.

The image is available in the registry and just to see if the token was bad I created a new one, added it to `.env` and ran `kamal env push` before trying again but I still got the same error just like below, has anyone experienced this one?

```bash
------
 > exporting to image:
------
ERROR: failed to solve: failed to push dockerusername/service-name:4z484256423y7c90x2409efb385aa447df33b2fa: push access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

> [!NOTE]  
> I run Kamal using the following alias (not the gem install):
> `alias kamal='docker run -it --rm -v "${PWD}:/workdir" -v "${HOME}/.ssh:/root/.ssh" -v "/run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock" -e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/basecamp/kamal:latest'`

**Comment by Briscoooe** [comment]
I am also getting this. My config section for this is

```yml
# Credentials for your image host.
registry:
  username: myusername

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

```

where `KAMAL_REGISTRY_PASSWORD` is in my `.env` file. It is a Dockerhub access token with the following permissions.

<img width="693" alt="image" src="https://github.com/user-attachments/assets/72b20c01-f974-408b-a70c-d5ebfe01d0ab">

What am I missing?

Here's the output of `kamal registry login`
```
  INFO [e99f5161] Running docker login -u [REDACTED] -p [REDACTED] on localhost
  INFO [e99f5161] Finished in 1.498 seconds with exit status 0 (successful).
  INFO [a933d128] Running docker login -u [REDACTED] -p [REDACTED] on ec2-[...].eu-west-1.compute.amazonaws.com
  INFO [a933d128] Finished in 1.396 seconds with exit status 0 (successful).
```

**Reply by r3cha** [reply]
@Briscoooe it happens with me while I update registry username kamal uses buildx and its caching
for me helps `docker buildx rm kamal-local-docker-container` or check `docker buildx ls` what you have

**Reply by f19ps** [reply]
> @Briscoooe it happens with me while I update registry username kamal uses buildx and its caching for me helps `docker buildx rm kamal-local-docker-container` or check `docker buildx ls` what you have

This solved my issue after switching DockerHub users

**Reply by viktorianer** [reply]
Solved for me too.

But, this sounds like a bug? Should be solved or is there some limitation?

**Reply by tillcarlos** [reply]
Oh, what a relief! This just took me hours to debug. Thanks @r3cha !

**Reply by tillcarlos** [reply]
Now I also have this problem on my CI (gitlab selfhosted + external runner, amd64).

- First logins are okay
- it fails when pushing the image
- locally it works, my token has "read_repository, read_registry, write_registry, read_package_registry, write_package_registry"
- there is no  builder to remove: `no builder "kamal-local-docker-container" found`

I guess it's the same issue. Any idea how to get rid of the credentials cache?

**Reply by fesilvajacquier** [reply]
Thank you @r3cha  :raised_hands: 
After changing *Docker Hub* accounts I started encountering this error. Rming the containers solved it.

**Reply by vickodin** [reply]
@r3cha Thank you, bro!

**Reply by jordan-brough** [reply]
I created a github issue for this: https://github.com/basecamp/kamal/issues/1383

**Reply by enochtamulonis** [reply]
This just happened to me after using another dockerhub account for work and then trying to deploy my own website with my credentials I was so confused but thank you so much! Hopefully this gets resolved soon

**Comment by yaKashif** [comment]
Has anyone solved this?

**Reply by jlenriquez** [reply]
Hi @yaKashif  can you check the name of the image container (prior the forward slash / ) and registry username if it's the same? If the image container name is not same with the registry name this might be the possible cause of the issue.

**Reply by yaKashif** [reply]
It is same.

**Reply by yaKashif** [reply]
adding `server: registry.hub.docker.com` in deploy.yml worked

I though it would default to that.

**Comment by jlenriquez** [comment]
On my end I didn’t need to add the server as I also have the same
understanding that it would be the default.

**Comment by stefatkins** [comment]
Hi everyone,

I’m encountering an issue with kamal and my GitHub Actions workflow during deployment. On my local environment, both kamal deploy and kamal redeploy work without any issues. However, when I use kamal redeploy in the GitHub Actions workflow, the deployment fails. Strangely, if I switch it to kamal deploy in the workflow, it works perfectly. I'm using a Read, Write, Delete docker acess token.

error is :` push access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`

Has anyone else faced this problem or have any insights on why kamal redeploy might be failing in the GitHub Actions environment but works fine locally?

```
name: Deploy
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/basecamp/kamal:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Disable Git safe directory check
        run: git config --global --add safe.directory '*'
      - name: Deploy Application
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          kamal lock release && kamal redeploy
```
