### DISCUSSION TITLE
How do we expose additional TCP ports from a container in Kamal 2 using kamal-proxy?

### DISCUSSION THREAD

**Discussion by navinpeiris** [basecamp/kamal#962] [Q&A]
Hi all!

I've got a case where I need to expose some additional TCP ports from the container. It's an elixir app that needs to expose two ports for EPMD so that we can connect all the nodes in the cluster.

Currently, using Kamal 1.x, I'm able to do this using traefik labels, but going through Kamal 2 and kamal-proxy code, it wasn't clear if it was possible.

Cheers!

**Comment by geek411** [comment]
To expose additional TCP ports for EPMD in Kamal 2, you can use the `accessories` feature along with Traefik as a TCP proxy. Here's how to modify your `config/deploy.yml`:

- Add a Traefik container as an accessory to handle TCP routing.
- Configure Traefik to expose the necessary ports (4369 for EPMD and a range like 9000-9100 for node distribution).
- Add Traefik labels to your main service to enable TCP routing.

For example:
```yml
service: your_app_name
image: your_docker_image:tag

servers:
  web:
    hosts:
      - your_server_ip_or_hostname

health_check:
  path: /healthz
  port: 4000

env:
  clear:
    PORT: 4000

accessories:
  tcp_proxy:
    image: traefik:v2.5
    roles: [web]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.epmd.address=:4369
      - --entrypoints.distribution.address=:9000-9100
    ports:
      - 80:80
      - 4369:4369
      - 9000-9100:9000-9100

traefik_labels: &traefik_labels
  - traefik.enable=true
  - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAINS}`)
  - traefik.http.routers.${SERVICE_NAME}.entrypoints=web
  - traefik.tcp.routers.epmd.rule=HostSNI(`*`)
  - traefik.tcp.routers.epmd.entrypoints=epmd
  - traefik.tcp.routers.epmd.service=epmd
  - traefik.tcp.services.epmd.loadbalancer.server.port=4369
  - traefik.tcp.routers.distribution.rule=HostSNI(`*`)
  - traefik.tcp.routers.distribution.entrypoints=distribution
  - traefik.tcp.routers.distribution.service=distribution
  - traefik.tcp.services.distribution.loadbalancer.server.port=9000-9100

labels:
  <<: *traefik_labels
  ```

I hope that helps.

**Comment by navinpeiris** [comment]
Thanks for that @geek411!

In case it helps anyone else, this is the config that ended up working for me:

```yaml
accessories:
  traefik:
    service: traefik
    image: traefik:v3.1
    roles:
      - web
    options:
      publish:
        - 4369:4369
        - 9100:9100
    cmd: "--providers.docker --providers.docker.exposedByDefault=false --entryPoints.epmd.address=:4369 --entryPoints.beam.address=:9100 --log.level=INFO"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

labels:
  traefik.enable: true
  traefik.tcp.routers.epmd.rule: "ClientIP(`0.0.0.0/0`)"
  traefik.tcp.routers.epmd.priority: 5
  traefik.tcp.routers.epmd.entryPoints: epmd
  traefik.tcp.routers.epmd.service: epmd
  traefik.tcp.services.epmd.loadBalancer.server.port: 4369
  traefik.tcp.routers.beam.rule: "ClientIP(`0.0.0.0/0`)"
  traefik.tcp.routers.beam.priority: 5
  traefik.tcp.routers.beam.entryPoints: beam
  traefik.tcp.routers.beam.service: beam
  traefik.tcp.services.beam.loadBalancer.server.port: 9100
```

**Reply by sebastian** [reply]
This worked well for me too. Thank you for the setup!

It does however seem a bit unfortunate to have to run a separate service just to expose a TCP port that docker could easily have exposed straight out of the box... I wonder if there shoudn't be a way to instruct Kamal to pass custom settings straight to docker instead?

**Reply by sebastian** [reply]
Actually, on looking at the source code, it turns out you can pass custom config in Kamal 2.0.

```
servers:
  web:
    hosts:
      - 1.2.3.4
    options:
      publish: "8001:8001"
```

`8001` being the port I have configured my nodes to listen to for incoming connections (and I am running without epmd). However this prevents the system from doing zero-downtime deployes as it cannot start the next version of the app while a previous container binds to the port... so I guess all this is to say: never mind... The traefik option still seems the way to go.

**Reply by konung** [reply]
Our app gets 99.99% for the traffic during “business hours”. We just need to expose ports, and do deployment overnight or on the weekends anyway. This will work well enough for us. 

Thank you

**Reply by schrockwell** [reply]
Please note that you may also have to run `kamal accessory start traefik` to get it started.

**Reply by PJUllrich** [reply]
Just to elaborate: The `traefik` accessory above does not replace Kamal's `kamal-proxy` accessory (which also runs Traefik). It merely adds another Docker container running Traefik, which binds to the provided ports and forwards the requests to your Elixir application. So, you'll have two Traefik instances running, one binding to 80 and 443, and one binding to e.g. 4369 and 9000-9100. 

It would be nice if the Ports provided in `servers.web.options.publish` would be set on the `kamal-proxy` and handle proper zero-downtime deployments, but this workaround is also okay.

**Reply by PJUllrich** [reply]
FYI 2: There's also an option to disable EPMD and only expose a single port. I found this easier to set up e.g. my remote IEx session script: https://samrat.me/elixir-clustering-on-a-kamal-hetzner-deployment/

**Reply by jakeprem** [reply]
@PJUllrich How did you get IEx working with that setup?

I followed the blog post and got clustering working (albeit using libcluster_postgres strategy, still using Hetzner private network though), but for the life of me I can't figure out how to get my IEx working again. So far I've mainly tried this alias `iex: app exec --interactive --reuse --primary "./bin/bpc remote"` and editing `rel/remote.vm.args.eex`. It seems like I'm missing something simple but not sure what.

**Reply by PJUllrich** [reply]
Did you open the port in your firewall? Your droplets need to allow this port for incoming TCP traffic but you can be restrictive on the source of the traffic (e.g. only your apps can talk to each other)

**Reply by jakeprem** [reply]
My `kamal iex` alias is setup to just run `./bin/app remote` from within one of my deployment containers. I think the problem is that the node is named `app@10.0.2.1` which is the VM's private IP, but inside the container can't really view the `10.0.2.1`. When I run it the error is  `Could not connect to 'app@10.0.2.1'`.

I haven't tried connecting a remote shell yet so I don't think firewall ports should be the issue. If I go that way I'll have to rearrange things a bit since I'm currently using Hetzner private network IPs.

https://gist.github.com/jakeprem/0e11055610df1b306ca5e7e82ca1a332

---
Based on further research I think it's just a Docker/bridge networking issue. I can `curl 10.0.5.1/up` from inside the container (on 10.0.2.1), but `curl 10.0.2.1/up` hangs and then times out. So it seems the container can talk to other hosts via private IP, but doesn't have the right loopback/hairpin to talk to itself that way.

I switched over to using Tailscale instead which seems to be working fine.
```
# env.sh.eex
export RELEASE_DISTRIBUTION="name"
export RELEASE_NODE="app@${KAMAL_HOST}.${TAILNET}"
```
(I deploy over Tailscale using just the hostname, but Erlang wants the fully qualified domain so adding the Tailnet back here).
```
 iex --name me@${HOST}.${TAILNET} --erl '-dist_listen false -erl_epmd_port 6789' --remsh app@${REMOTE_HOST}.${TAILNET} --cookie ${RELEASE_COOKIE}
 ```
This command then worked for me. For anyone else coming across this, don't forget to set appropriate ACL in your Tailnet for the port you're using (6789 in this case).

**Reply by navinpeiris** [reply]
To access `iex` and `remote` on the server from my local, I use the following commands:

```
kamal app exec -h <my-server> --interactive "/app/bin/remote"
```

and

```
kamal app exec -h <my-server> --interactive "/app/bin/start_iex"
```

Among other things like disabling starting oban, my `start_iex` script also contains the following:

```sh
export RELEASE_DISTRIBUTION=sname
export RELEASE_NODE="app"
```

That way only my SSH port is exposed to the public, and EPMD, HTTP etc ports are only open to the internal network.

All my things are running on Hetzner and this works like a charm. Let me know if you need any more info @jakeprem

**Reply by jakeprem** [reply]
Thanks! Do you have multiple nodes clustering together? I started running into problems once I switched to `RELEASE_DISTRIBUTION=name` and setting the host portion of `RELEASE_NODE` to something other than `app@127.0.0.1`.

For my setup though I'm pretty sure it's just an IP/routing problem. Looking at the docs for Fly.io for example they have a routable IPv6 on every machine that they end up using in the node name. I'd guess they have proper loopback setup for that (or at least they benefit from being micro-VMs rather than containers in addition to just having Fly solving the routing problems)

**Reply by navinpeiris** [reply]
Yes, all my nodes are clustered together.

In case it helps:

Since the servers are on Hetzner and they are pretty static, I set a DNS record for the internal IP along the lines of `web-1.internal.xxx.dev` so that they can resolve each other's local IPs.

Then in the `env` section of `deploy.yml`, I pass all the hosts that need to be clustered, along with the `RELEASE_*` env variables like:

```yaml
env:
  clear:
    CLUSTER_HOSTS: "web-1,web-2,web-3,worker-1,worker-2"
    RELEASE_DISTRIBUTION: name
    RELEASE_NODE: "app@${HOSTNAME}.internal.xxx.dev"
    RELEASE_COOKIE: "<my-release-cookie>"
```

`RELEASE_COOKIE` should be in `secrets`, but put it in `clear` for the example above.

Then, in my `runtime.exs`, I parse the `CLUSTER_HOSTS` env variable and pass it through to my app config, like:

```elixir
cluster_hosts = "CLUSTER_HOSTS" |> System.fetch_env!() |> String.split(",") |> Enum.map(&String.trim/1)

config :my_app,
  cluster_hosts: cluster_hosts
```

I've then got a `ClusterConnect` module that I start via `Application.start`, which then manages the node connections:

```elixir
defmodule MyApp.Application do
  use Application

  def start(_type, _args) do
    children =
      [
       # ...
        {MyApp.ClusterConnect, [hosts: cluster_hosts()]},
       # ...
      ]
    # ...
  end

  defp cluster_hosts, do: Application.get_env(:my_app, :cluster_hosts, [])
end
```

The `ClusterConnect` module, which is based on `DNSCluster`. Looks like `DNSCluster` has been updated to take in any base name for the hosts since I set up my cluster, so might be better to use that instead, but leaving this here anyways:

```ex
defmodule MyApp.ClusterConnect do
  use GenServer

  require Logger

  @app_name "<my-app-name>"
  @domain_suffix ".internal.xxx.dev"

  @default_interval 5_000
  @default_connect_timeout 10_000

  def start_link(opts) do
    GenServer.start_link(__MODULE__, opts, name: Keyword.get(opts, :name, __MODULE__))
  end

  @impl GenServer
  def init(opts) do
    Process.flag(:trap_exit, true)

    case Keyword.get(opts, :hosts, []) do
      [] ->
        :ignore

      hosts ->
        state = %{
          hosts: hosts,
          interval: Keyword.get(opts, :interval, @default_interval),
          connect_timeout: Keyword.get(opts, :connect_timeout, @default_connect_timeout),
          timer: nil
        }

        {:ok, state, {:continue, :connect_nodes}}
    end
  end

  @impl GenServer
  def handle_continue(:connect_nodes, state), do: {:noreply, do_connect_nodes(state)}

  @impl GenServer
  def handle_info(:connect_nodes, state), do: {:noreply, do_connect_nodes(state)}

  @impl GenServer
  def terminate(reason, _state) do
    Logger.debug("[cluster_connect] terminating, reason: #{reason}")

    :ok
  end

  defp do_connect_nodes(state) do
    state
    |> connect_new_nodes()
    |> schedule_next_poll()
  end

  defp connect_new_nodes(state) do
    expected_nodes = state.hosts |> Enum.map(&:"#{@app_name}@#{&1}#{@domain_suffix}")

    connected_nodes = Node.list()
    current_node = Node.self()

    _ =
      expected_nodes
      |> Enum.reject(&(&1 == current_node || &1 in connected_nodes))
      |> Task.async_stream(
        fn node ->
          case Node.connect(node) do
            true ->
              Logger.info(
                "[cluster_connect] #{to_host_name()} connected to #{to_host_name(node)}"
              )

            false ->
              Logger.warning(
                "[cluster_connect] #{to_host_name()} failed to connected to #{to_host_name(node)}"
              )

            :ignored ->
              Logger.warning("[cluster_connect] #{to_host_name()} is not alive")
          end
        end,
        max_concurrency: max(1, length(expected_nodes)),
        timeout: state.connect_timeout
      )
      |> Enum.to_list()

    state
  end

  defp schedule_next_poll(state),
    do: %{state | timer: Process.send_after(self(), :connect_nodes, state.interval)}

  defp to_host_name(node \\ node()) do
    node
    |> Atom.to_string()
    |> String.trim_leading(@app_name <> "@")
    |> String.trim_trailing(@domain_suffix)
  end
end
```
