### ISSUE TITLE
host must be set when using TLS

### ISSUE THREAD

**Issue by bamnet** [basecamp/kamal#1037]
Trying to upgrade from Kamal 2.0.0 to 2.1.0 I'm getting an error running `kamal proxy reboot`:

```
docker stdout: Nothing written
docker stderr: Error: host must be set when using TLS
```

SSL is terminated upstream of Kamal, so my config looks like:
```
# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# Set ssl: false if using something like Cloudflare to terminate SSL (but keep host!).
proxy:
  ssl: false
  # host: app.example.com
  app_port: 3000  # https://github.com/basecamp/kamal/issues/987
```

Is `host` required even when the proxy isn't terminating SSL? It wasn't required in 2.0.0 at least.

I noticed that 2.1.0 changed the docker command adding `--tls="false"` which trips kamal-proxy's `cmd.Flags().Changed("tls")` validation [here](https://github.com/basecamp/kamal-proxy/blob/ba1d5499608c8ee40d2cee7c6621787e6b8865ff/internal/cmd/deploy.go#L89).

My limited understanding is that pflag's `Changed()` fires when the flag is set regardless of its value.  This should _probably_ be fixed over in kamal-proxy, but I'm opening it here in case my diagnosis is wrong.

```
# docker exec kamal-proxy kamal-proxy deploy app-web --target="6a37c269ff02:3000" --tls=false --deploy-timeout="30s" --drain-timeout="30s" --buffer
-requests --buffer-responses --log-request-header="Cache-Control" --log-request-header="Last-Modified" --log-request-header="User-Agent"
Error: host must be set when using TLS
```
vs
```
# docker exec kamal-proxy kamal-proxy deploy app-web --target="6a37c269ff02:3000" --deploy-timeout="30s" --drain-timeout="30s" --buffer-requests --
buffer-responses --log-request-header="Cache-Control" --log-request-header="Last-Modified" --log-request-header="User-Agent"
```
(no error)
