### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by antarr** [basecamp/kamal#1056]
I'm trying to get my app deployed on linode. From what I can tell everything is working and the server is healthy.
```
CONTAINER ID   IMAGE                                                                    COMMAND                  CREATED             STATUS                        PORTS                       NAMES
7c3645ab65e6   ghcr.io/wevote-project/wevote:latest                                     "./bin/thrust ./bin/…"   2 minutes ago       Up 2 minutes                  80/tcp, 443/tcp, 3000/tcp   wevote-web-latest
```

Proxy seems to succeed when booting the app
```
  INFO [8608fb59] Running docker exec kamal-proxy kamal-proxy deploy wevote-web --target "7c3645ab65e6:80" --host "kamal.wevoteproject.com" --tls --deploy-timeout "30s" --drain-timeout "30s" --buffer-requests --buffer-responses --log-request-header "Cache-Control" --log-request-header "Last-Modified" --log-request-header "User-Agent" on 72.14.189.58
  INFO [8608fb59] Finished in 13.033 seconds with exit status 0 (successful).
```

But when viewing in the browser I get a DNS error
```
ERR_NAME_NOT_RESOLVED
```

### deploy.yaml
```yml
# Name of your application. Used to uniquely configure containers.
service: wevote

# Name of the container image.
image: wevote-project/wevote

# Deploy to these servers.
servers:
  web:
    - 72.14.189.58
# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# Set ssl: false if using something like Cloudflare to terminate SSL (but keep host!).
proxy:
  # app_port: 3000
  ssl: true
  host: kamal.wevoteproject.com

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: antarr

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: x86_64
  local: false
  remote: ssh://deploy@72.14.189.58
  cache:
    type: registry
    options: mode=max,image-manifest=true,oci-mediatypes=true

# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
env:
  clear:
    ACTIVERECORD_POOL_SIZE: 5
    APPSIGNAL_ACTIVE: true
    AWS_REGION: us-east-1
    BLAZER_DB_URL: postgresql://wevote:xxxxxx@72.14.189.58:5432/wevote_production
    DATABASE_URL: postgresql://wevote:xxxxxx@72.14.189.58:5432/wevote_production
    ELASTICSEARCH_URL: http://72.14.189.58:9200
    MALLOC_ARENA_MAX: 2
    OPEN_AI_MODEL: gpt-3.5-turbo
    RAILS_ENV: production
    RAILS_LOG_LEVEL: debug
    RAILS_LOG_TO_STDOUT: 1
    RAILS_MAX_THREADS: 5
    RAILS_SERVE_STATIC_FILES: 1
    REDIS_URL: redis://:GvMSDA@redis:6379/0
    RUBY_YJIT_ENABLE: 1
    SIDEKIQ_CONCURRENCY: 5
    VOTER_DATA_URL: postgresql://wevote:xxxxxxxxxxxx@72.14.189.58:5432/wevote_voter_data
    LEGISCAN_DATABASE_URL: postgresql://wevote:xxxxxxxxx@72.14.189.58:5432/wevote_legiscan_data
    WEB_CONCURRENCY: 2
  secret:
    - RAILS_MASTER_KEY

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
#
aliases:
  console: app exec -r console --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Use a different ssh user than root
#
ssh:
  user: deploy

# Use a persistent storage volume.
#
volumes:
  - "data:/rails/data"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
# asset_path: /app/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Use accessory services (secrets come from .kamal/secrets).
#
accessories:
  db:
    image: postgres:14
    # host: 72.14.189.58
    roles:
      - web
    options:
      restart: always
    port: 5432
    env:
      clear:
        POSTGRES_USER: "wevote"
        POSTGRES_DB: "wevote_production"
        POSTGRES_HOST_AUTH_METHOD: "trust"
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/structure.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    cmd: redis-server --requirepass GvMSDA --replica-read-only no
    roles:
      - web
    port:  '6379:6379'
    directories:
      - data:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    roles:
      - web
    port: 9200
    options:
      restart: always
    directories:
      - data:/usr/share/elasticsearch/data
    env:
      clear:
        ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
        discovery.type: single-node

logging:
  driver: json-file
  options:
    max-size: 100m
```
