### ISSUE TITLE
Bootstrapping with `kamal server bootstrap` does not recognize accessory host

### ISSUE THREAD

**Issue by dihmeetree** [basecamp/kamal#1068]
I have a config like so
```YAML
service: web
image: example/web
builder:
  arch: amd64
  secrets:
    - AUTH_GITHUB_CLIENT_ID
    - AUTH_GITHUB_CLIENT_SECRET
    - DB_NAME
    - PRIMARY_DB_HOST
    - PRIMARY_DB_USERNAME
    - PRIMARY_DB_PASSWORD
    - REPLICA_DB_HOST
    - REPLICA_DB_USERNAME
    - REPLICA_DB_PASSWORD
servers:
  - 10.0.0.1 # us-east-1
  - 10.0.0.2 # us-east-2
proxy:
  app_port: 3000
  healthcheck:
    interval: 5
    path: /api/health
    timeout: 5
  host: example.com
  response_timeout: 10
asset_path: /app/build/client
registry:
  username:
    - DOCKER_HUB_USERNAME
  password:
    - DOCKER_HUB_PASSWORD
accessories:
  k6:
    image: grafana/k6
    host: 10.0.0.3 # k6
    port: '127.0.0.1:6565:6565'
    files:
      - ./k6/script.js:/script.js
    cmd: run /script.js
```
When I run `kamal server bootstrap`, it will only bootstrap the servers under the `servers` config for some reason. According to the source code for the bootstrap command, Docker should be installed on all servers (as well as accessory servers), but for some reason it is not. 

**Note**: If I add the server to the `servers` list, it does get bootstrapped just fine. However per the accessory page docs, it says `The hosts do not need to be defined in the Kamal servers configuration.`, so this command should work.

Also note that the accessory host is different than the servers defined in the `servers` section; not sure if that has something to do with it.
