### ISSUE TITLE
Unauthorized error while upgrading kamal-proxy

### ISSUE THREAD

**Issue by tobiasalmstrand** [basecamp/kamal#1090]
Upgrading kamal-proxy won't work when using `ghcr.io` registry:

```
Error response from daemon: Head "https://registry-1.docker.io/v2/basecamp/kamal-proxy/manifests/v0.8.1": unauthorized: incorrect username or password
```

My config:

```
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
```

When using the default registry (Docker Hub), it works as expected.
