### ISSUE TITLE
specify one of `host`, `hosts` or `roles` : is roles still a valid key for accessories?

### ISSUE THREAD

**Issue by adrienpoly** [basecamp/kamal#1162]
I was trying to make this configuration so that Meilisearch is available in the web and job network.

```
accessories:
  search:
    image: getmeili/meilisearch:v1.10
    roles:
      - web
      - job
    env:
      clear:
        MEILI_ENV: production
```

I am getting the error 

```
ERROR (Kamal::ConfigurationError): accessories/search: specify one of `host`, `hosts` or `roles`
```

Is roles deprecated in V2?
