### ISSUE TITLE
Kamal should complain if proxy host contains invalid value

### ISSUE THREAD

**Issue by a3kov** [basecamp/kamal#1169]
I am proxying multiple hosts in Kamal. I had the old format in the config file:
```
proxy:
  ssl: true
  host: host1,host2,...
```
Kamal was happy to apply this, and SSL termination in Kamal-proxy was broken.
After changing it to
```
proxy:
  ssl: true
  hosts:
    - host1
    - host2
```
SSL started to work.
Kamal version: 2.2.2
