### ISSUE TITLE
Multiple Instances of an application on a single server

### ISSUE THREAD

**Issue by SteffanPerry** [basecamp/kamal#1190]
Kamal configuration should allow to deploy multiple instances of an application on a server. adding container or instance count as an option in the config could allow it to create multiple containers.

Use case:
I have a worker that does pretty resource intensive work for one customer at a time. I have a 32 core / 64GB server that runs these workers. Each container instance should be deployed with 2 cpu / 4gb ram. 

Currently our config looks like this:
```
worker: &worker
    hosts:
      - 10.1.1.1
    cmd: "bundle exec my_job_command"
    proxy: false
    options:
      memory: 4g
      cpus: 2
  worker_a:
    <<: *worker
  worker_b:
    <<: *worker
   ...
```
 
 Ideally we can do:
```
worker:
    hosts:
      - 10.1.1.1
    cmd: "bundle exec my_job_command"
    proxy: false
    options:
      container_count: 16
      memory: 4g
      cpus: 2

```
