### ISSUE TITLE
Allow secrets expansion in commands and configurations

### ISSUE THREAD

**Issue by fidalgo** [basecamp/kamal#1197]
From what I've seen, Secrets and Environment Variables are not expanded/interpolated in options.

So in a config like this:
```
servers:
  web:
    hosts:
      - a.b.c.d
    logging:
      driver: loki
      options:
        loki-url: "${GRAFANA_LOKI_URL}"
        loki-batch-size: '400'
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: true
```

The `GRAFANA_LOKI_URL` will be empty, despite being present in the secrets.
In the Environment Variable section of the docs, we can see that only secret envs are interpolated, but what prevent us from interpolating all the variables as per:
 https://github.com/bkeepers/dotenv?tab=readme-ov-file#variable-substitution
 
 
 Edit: If we decide to increase the surface of variables expansion, this issue is related: https://github.com/basecamp/kamal/issues/1167
