### ISSUE TITLE
`Not a tty` error while logging into Docker registry

### ISSUE THREAD

**Issue by kczpl** [basecamp/kamal#1198]
Hi!
I'm facing an annoying issue that I've spent 4 hours trying to solve.
I'm deploying my app from GitLab CI/CD using the `kamal deploy` command, but it fails on the first step, which is `docker login`. I tried to debug it with the `kamal login` command:
```sh
kamal registry login -L -d staging -c .kamal/deploy.yml -v
INFO [4cc56c39] Running docker login git.registry:5050/app -u [REDACTED] -p [REDACTED] on app.domain.com
user@app.domain.com's password:  ERROR (Errno::ENOTTY): Exception while executing on host app.domain.com: Not a tty
```

It looks like it's missing either the password or username, so I dug deeper.
Normally, I use GitLab-provided variables like this:
```yml
registry:
  server: git.registry:5050/app
  username:
    - CI_REGISTRY_USER
  password:
    - CI_REGISTRY_PASSWORD
```

Long story short, I created a fixed GitLab token to pass, and I even hardcoded it for testing. I passed variables explicitly and tried many approaches, but since nothing worked, I decided to create this issue. Here's what I tried:
```yml
registry:
  server: git.registry:5050/app
  username: deploy
  password: somehardcodedpassword
```

Using this exact same configuration **on my local machine works just fine**. However, on the GitLab CI pipeline, it always errors because of TTY, which makes sense if no value is passed, but I can't even see the [REDACTED] values.

How is it possible that even hardcoded variables don't work, let alone environmental values? The `docker login` command works on the server, and `kamal login` works on my local machine
