### ISSUE TITLE
./bin/kamal dbc error "Couldn't find database client: sqlite3. Check your $PATH and try again."

### ISSUE THREAD

**Issue by pioz** [basecamp/kamal#1232]
When I run `./bin/kamal dbc` I get this error:
```
Get current version of running container...
  INFO [b3b5b899] Running /usr/bin/env sh -c 'docker ps --latest --format '\''{{.Names}}'\'' --filter label=service=xxx --filter label=role=web --filter status=running --filter status=restarting --filter ancestor=$(docker image ls --filter reference=pioz/xxx:latest --format '\''{{.ID}}'\'') ; docker ps --latest --format '\''{{.Names}}'\'' --filter label=service=xxx --filter label=role=web --filter status=running --filter status=restarting' | head -1 | while read line; do echo ${line#xxx-web-}; done on 1.1.1.1
  INFO [b3b5b899] Finished in 0.702 seconds with exit status 0 (successful).
Launching interactive command with version 9778ab421ec1437cd592eef9f6e2cdafe31159c0 via SSH from existing container on 1.1.1.1...
Couldn't find database client: sqlite3. Check your $PATH and try again.
Connection to 1.1.1.1 closed.
```

My Dockerfile is:
```
# syntax=docker/dockerfile:1
# check=error=true



# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.3.5
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

# Rails app lives here
WORKDIR /rails

# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips sqlite3 postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Set production environment
ENV RAILS_ENV="production" \
    NODE_ENV="production" \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="development"



# Throw-away build stage to reduce size of final image
FROM base AS build

# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install Node.js v20.17.0
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install --no-install-recommends -y nodejs && \
    npm install -g yarn@latest && \
    node -v && \
    yarn -v

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile --gemfile

# Copy application code
COPY . .

# Precompile bootsnap code for faster boot times
RUN bundle exec bootsnap precompile app/ lib/

# Install node modules
RUN yarn install && \
    yarn cache clean

# Precompiling assets for production without requiring secret RAILS_MASTER_KEY
RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile



# Final stage for app image
FROM base

# Copy built artifacts: gems, application
COPY --from=build "${BUNDLE_PATH}" "${BUNDLE_PATH}"
COPY --from=build /rails /rails

# Run and own only the runtime files as a non-root user for security
RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
    chown -R rails:rails db log storage tmp
USER 1000:1000

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Start server via Thruster by default, this can be overwritten at runtime
EXPOSE 8080
CMD ["./bin/thrust", "./bin/rails", "server"]
```

and my deploy.yml file is:
```
service: foo

image: pioz/foo

servers:
  web:
    - 1.1.1.1

proxy:
  ssl: true
  host: foo.bar.it
  app_port: 8080
  healthcheck:
    path: /up

registry:
  username: pioz
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    JOB_CONCURRENCY: 2
    WEB_CONCURRENCY: 10

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "xxx_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: arm64

ssh:
  user: ubuntu

deploy_timeout: 60
```

If I build and run the image locally with:
```
docker build -t xxx . 
docker run -d -p 80:80 -e RAILS_MASTER_KEY=$(cat config/master.key) --name xxx xxx
docker exec -it xxx bash   
```
The command `sqlite3` exists and works as expected.
