### ISSUE TITLE
Allow specifying separate port for health check

### ISSUE THREAD

**Issue by petromir** [basecamp/kamal#1234]
I have the following settings of the proxy `kamal.yaml` file
```yaml
proxy:
  app_port: 8080
  response_timeout: 10
  healthcheck:
    interval: 3
    path: /health
    timeout: 3
```
Usually, the "management" (a.k.a observability - health, metrics, prometheus etc.) endpoints are served on a different port not exposed to outside world, e.g. `8181`

Could you please add another property to specify different port for the health check, so we end up with
```yaml
proxy:
  app_port: 8080
  response_timeout: 10
  healthcheck:
    interval: 3
    path: /health
    port: 8181 # the new shiny property
    timeout: 3
```
