### ISSUE TITLE
ERROR (Kamal::ConfigurationError): unknown key: traefik

### ISSUE THREAD

**Issue by ghillahill** [basecamp/kamal#1244]
As the title says we are getting this error without making any changes to the code except for the gem update to 1.9.2

Thing is that in the Gemfile

`kamal version` command return: `2.3.0` is it normal?

We are unable to deploy and we don't want to switch to Kamal 2 for now.

Also `kamal downgrade` is not usable even if we are using Kamal 1.9.2, returning `ERROR (Kamal::ConfigurationError): unknown key: traefik` too

Do we need to apply kamal 2 changes to the Kamal 1.9.x too?

Gemfile
```
group :development do
  gem 'kamal', '~> 1.9.0'
end
```

Deploy.yml snippet
```
traefik:
  options:
    publish:
      - 443:443
      - 8080:8080
    volume:
      - "./acme_certs:/acme_certs"
  args:
    api.dashboard: true
    api.insecure: true
    providers.http.endpoint: http://xxxxxxxx/traefik/config
    providers.http.pollInterval: "5s"
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "xxxxxxx"
    certificatesResolvers.letsencrypt.acme.storage: "/acme_certs/acme.json"
    certificatesResolvers.letsencrypt.acme.caServer: "https://acme-v02.api.letsencrypt.org/directory"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
```

**Comment by igor-alexandrov** [comment]
@ghillahill you should either use a binstub `./bin/kamal` or bundle exec `bundle exec kamal`.

`kamal version` returns `2.3.0` because you didn't specify what exact installation of the Kamal you are launching.

**Comment by garlou** [comment]
I'm having the same problem with kamal 2.3.0

**Comment by igor-alexandrov** [comment]
Kamal 2.x replaced Traefik with kamal-proxy and so the `traefik` key in the config file is not valid anymore.

**Comment by garlou** [comment]
Thank you @igor-alexandrov 
It is very easy to add tls now. All it took me was setting the proxy:
```
proxy:
  ssl: true
  host: ecample.com
  app_port: 3000
```
My problem was the port 443 not being open in the hosting service.
