### ISSUE TITLE
can't set logging options for roles

### ISSUE THREAD

**Issue by cromega** [basecamp/kamal#1250]
In a multi-role configuration, global logging configuration hash doesn't work very well. eg: I can't specify role-specific log streams for the aws cloudwatch logger

The following configuration is not possible:

```
servers:
  web:
    logging:
      driver: awslogs
      options:
        awslogs-stream: app-web
  sidekiq:
    logging:
      driver: awslogs
      options:
        awslogs-stream: app-sidekiq
```

Without being able to set the stream name, awslogs falls back to the container id, which is not very useful.
