### ISSUE TITLE
ArgumentError, "Missing `secret_key_base` for '#{Rails.env}' environment

### ISSUE THREAD

**Issue by ghillahill** [basecamp/kamal#1273]
Hello everyone,
After some changes to my Rails app and upgrading from Kamal 1.3.1 to Kamal 1.9.2 when I try to deploy the app I get the following message:

```
/usr/local/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/application.rb:658:in `validate_secret_key_base': Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit` (ArgumentError)

        raise ArgumentError, "Missing `secret_key_base` for '#{Rails.env}' environment, set this string with `bin/rails credentials:edit`"
```

I have in my **.env** the following env variables ( snippet )
```
RAILS_MASTER_KEY=xxxxxxx
SECRET_KEY_BASE=xxxx
```

Then `kamal env push` as always

But then when i fire `kamal deploy` I got that message. But ofcourse seems not possibile to edit the credential file inside a docker container. Or I missing something?

How can I set up correctly the secrete_key_base?

Also I don’t know if this can help you understand based on my configuration but I also share the deploy file, although it always worked.

```
# Name of your application. Used to uniquely configure containers.
service: xxxxxx

# Name of the container image.
image: xxxxxx/xxxxxx

# Deploy to these servers.
servers:
  web:
    hosts:
      - xxxxxx
    labels:
      {}

# Credentials for your image host.
registry:
  server: ghcr.io
  username: xxxxxx

  # Always use an access token rather than real password when possible.
  password:
    - GITHUB_TOKEN
# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  secret:
    - DATABASE_URL
    - RAILS_MASTER_KEY

# Configure builder setup.
builder:
  args:
    RUBY_VERSION: 3.2.1
  secrets:
    - GITHUB_TOKEN
  remote:
    arch: amd64
#     host: ssh://root@xxxxxx

# Configure custom arguments for Traefik
traefik:
  options:
    publish:
      - 443:443
      - 8080:8080
    volume:
      - "./acme_certs:/acme_certs"
  args:
    api.dashboard: true
    api.insecure: true
    providers.http.endpoint: http://xxxxxx/traefik/config
    providers.http.pollInterval: "5s"
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "xxxx@xxx"
    certificatesResolvers.letsencrypt.acme.storage: "/acme_certs/acme.json" # Must match the path in `volume`
    certificatesResolvers.letsencrypt.acme.caServer: "https://acme-v02.api.letsencrypt.org/directory"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
# Configure a custom healthcheck (default is /up on port 3000)
# healthcheck:
#   path: /
#   port: 3000
```
