### ISSUE TITLE
Proxy doesn't support generic docker `options`

### ISSUE THREAD

**Issue by nickhammond** [basecamp/kamal#1274]
Roles and accessories both support a generic set of options that get passed to the `docker run` command, it'd be helpful to also have this option for the proxy. 

```
proxy:
  ssl: true
  host: example.com
  options:
    anything: true
```

```
$ kamal config
ERROR (Kamal::ConfigurationError): proxy: unknown key: options
```
