### ISSUE TITLE
feature request: Support Github Container Registry

### ISSUE THREAD

**Issue by stianlagstad** [basecamp/kamal#1276]
There are some other issues related to using a different container registry, or even self-hosting one:
- https://github.com/basecamp/kamal/issues/1166
- https://github.com/basecamp/kamal/issues/1058
- https://github.com/basecamp/kamal/issues/69

This issue (or feature request) is more narrow, and may be easier to add on to existing functionality: Support github container registry (https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

I just tried using it, naively thinking it would be supported, but I get authentication issues like:
```
$ kamal deploy
Log into image registry...
  INFO [eacef5c7] Running docker login -u [REDACTED] -p [REDACTED] on localhost
  Finished all in 0.9 seconds
  ERROR (SSHKit::Command::Failed): docker exit status: 256
docker stdout: Nothing written
docker stderr: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
```
even when my configuration states:
```
image: ghcr.io/stianlagstad/myapp
registry:
  username: stianlagstad
  password:
    - KAMAL_REGISTRY_PASSWORD
```
And https://kamal-deploy.org/docs/configuration/docker-registry/ does not mention github container registry, so my assumption now is that it's not supported yet.

**Comment by acidtib** [comment]
kamal does support github container registry, the error your getting is telling you the issue, you need to configure it in your deploy file, the registry options are passed to the local docker cli to authenticate against the registry server heres an example using it

using github registry
```
# Name of the container image.
image: my-user/my-app

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: your-user

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD
```

and here an example using a self hosted private registry
```
# Name of the container image.
image: my-user/my-app

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: private_registry:4443
  username: your-user
  password: your-pass
```
