### ISSUE TITLE
Cannot set custom kamal proxy error pages

### ISSUE THREAD

**Issue by ahmayou** [basecamp/kamal#1302]
Kamal Proxy allows setting custom error pages in: [Kamal Proxy PR #12](https://github.com/basecamp/kamal-proxy/pull/12)
However, when setting this in kamal deploy under proxy [as specified here](https://github.com/basecamp/kamal-proxy/blob/ecfc1ddf85bb67c84413ed41f0c0ba61d74facea/internal/server/service.go#L73) it throws an error:

```
proxy:
  ssl: true
  hosts: 
    - example.com
    - www.example.com
  error_pages_path: /usr/local/share/errors/myservice
```

`ERROR (Kamal::ConfigurationError): proxy: unknown key: error_page_path`
