### ISSUE TITLE
Aliases do not respect specified server roles

### ISSUE THREAD

**Issue by corvuszero** [basecamp/kamal#1316]
Following the documentation [here](https://kamal-deploy.org/docs/configuration/aliases/#configuring-aliases) and assuming a `deploy.yml` like this:
```
servers:
  admin:
    hosts:
      - admin-host.com
    proxy: true
  api:
    - api-host.com

aliases:
  admin_console: app exec -r admin --interactive --reuse "bin/rails console"
```

Using the `kamal admin_console` alias executes the command on the `api` server: `api-host.com`.

Calling `kamal admin_console -r admin` does execute the command on the `admin` role, same as not using the alias at all: `kamal app exec -r admin --interactive --reuse "bin/rails console"`.

### Additional details
I am using `kamal` dockerized: 
```
alias kamal='docker run -it --rm --env-file SECRET.env -v "${PWD}:/workdir" -v "${SSH_AUTH_SOCK}:/ssh-agent" -v /var/run/docker.sock:/var/run/docker.sock -e "SSH_AUTH_SOCK=/ssh-agent" ghcr.io/basecamp/kamal:latest'
```
