### ISSUE TITLE
TLS handshake error-Let's Encrypt

### ISSUE THREAD

**Issue by Jainam-17-18** [basecamp/kamal#1352]
### Discussed in https://github.com/basecamp/kamal/discussions/1347

<div type='discussions-op-text'>

<sup>Originally posted by **Jainam-17-18** January  9, 2025</sup>
I have deployed my application and it's fine when ```ssl: false ``` under proxy.

Now I have to do ```ssl: true```.

```
proxy:
  ssl: true
  host: subdomain.domain.com
  app_port: 8081
  response_timeout: 300
  healthcheck:
    interval: 3
    path: /healthcheck
    timeout: 3
```
But getting error:

```
{"time":"xxxx","level":"INFO","msg":"http: TLS handshake error from 103.136.75.230:61871: acme/autocert: unable to satisfy \"https://acme-v02.api.letsencrypt.org/acme/authz/xxxxxxxx/xxxxxxxx\" for domain \"mysubdomain.domain.com\": no viable challenge type found"}
{"time":"xxxx","level":"INFO","msg":"http: TLS handshake error from myServerIP:port: acme/autocert: missing certificate"}
{"time":"xxxx","level":"INFO","msg":"http: TLS handshake error from myServerIP:port: acme/autocert: missing certificate"}

```

Server Setup:
Have checked my server's both Port 80 and 443 is showing opened on https://portchecker.co/ .
Server transfer request to VM where the application had been deployed.

I have a server's port (abcd) which map with NAT to VM's port (443).
I also have another port (wxyz) which map with NAT to VM's port (80).</div>
