### ISSUE TITLE
kamal-proxy not using two different machines for

### ISSUE THREAD

**Issue by fidalgo** [basecamp/kamal#1384]
I have one machine for web/jobs and another for accessories.

I have a root proxy configuration:
```
proxy:
  ssl: true
  hosts:
    - example.net
    - www.example.net
```

and my accessories have:
```
    host: x.x.x.x
    port: 9000
    proxy:
      host: list.example.net
      app_port: 9000
      ssl: true
      forward_headers: true
      healthcheck:
        path: /
```
When I do a `kamal proxy boot` it only boots the proxy on my web machine, the docker command is not executed on the accessories machine.

When I boot my accessory, I have the error message:

`docker stderr: Error response from daemon: No such container: kamal-proxy`

So, is there a way to have the proxy also running on the accessories machine?
