### ISSUE TITLE
cron documentation is unclear

### ISSUE THREAD

**Issue by daliusd** [basecamp/kamal#1388]
I have tried to follow documentation https://kamal-deploy.org/docs/configuration/cron/ as I wanted to add cron job, but I have failed. If I do as written in documentation and do `kamal deploy` then I see `cron` container is created and it fails health check. That seems logical as I am overriding `cmd` and I assume that web server is not started anymore. Or am I wrong? Why is health check is run against cron job container?

Here is excerpt from my `deploy.yml` what looks the same like in documentation:

```yml
servers:
  web:
    - 195.201.143.78
  cron:
    hosts:
      - 195.201.143.78
    cmd: sh -c "(env && cat crontab) | crontab - && cron -f"
```

What I'm missing?

I have reverted now to use cronjob in web container directly as that works for me.

I have tried to search how others are doing this and have not found why it is not working for me, e.g. this one seems to be doing the same as in documentation, but I don't see what's different: https://github.com/datocms/astro-website/blob/bea07ff09e1c99d2b4edfba17efdead9a8fb3059/config/deploy.yml
