### ISSUE TITLE
Not possible to use different secret key values across multiple apps

### ISSUE THREAD

**Issue by zkrising** [basecamp/kamal#1417]
In short, I have two different apps that both expect `AWS_SECRET_ACCESS_KEY` as a secret. These apps **NEED** to have different values for this key. They are **NOT** destinations of eachother, they are completely separate apps.

At the moment both apps have to look like this:
```yaml
env:
  clear:
  secret:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
```
These apps both expect the same env key names -- `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` -- but it doesn't seem to be possible to have different values for the same key names.

I have `.kamal/secrets` setting the variables, but it doesn't appear to be possible to have a separate secrets file for each app, nor does it appear to be possible to bind the secrets to different secret names, i.e.:
```
env:
  clear:
  secret:
    - AWS_ACCESS_KEY_ID: APP1_AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY: APP1_AWS_SECRET_ACCESS_KEY
```

Am I missing something? I can't find anything for this functionality, but it seems pretty essential.
