### ISSUE TITLE
env/secret no longer merges when deploying to a destination.

### ISSUE THREAD

**Issue by orehmane** [basecamp/kamal#1468]
Hi there!

Thank you for all your hard work on this great tool. I believe I've come across a change in behavior. I don't know if it's intended or not.

Consider the following snippets:

`deploy.yml`:
```
accessories:
  db:
    env:
      secret:
        - PASSWORD
```

`deploy.staging.yml`:
```
accessories:
  db:
    env:
      secret:
        - SOMETHING
        - SOMETHING_ELSE
```

`secrets.staging` (note that none of the three env vars are defined in `secrets-common`):
```
PASSWORD=password
SOMETHING=something
SOMETHING_ELSE=else
```

Previously, when deploying to `staging`, I would get all three env vars (that is, `PASSWORD`, `SOMETHING`, and `SOMETHING_ELSE`). Now it seems that it's only including the ones in the destination file (that is, `SOMETHING` and `SOMETHING_ELSE`).

Am I mistaken that this behavior has changed? If I'm correct that it has changed, was that intentional?

Thank you for your help!
