### ISSUE TITLE
Kamal setup: ActiveRecord::ConnectionNotEstablished

### ISSUE THREAD

**Issue by victorhazbun** [basecamp/kamal#1482]
I'm using Kamal secrets to store `RAILS_MASTER_KEY` and Rails credentials to store `db_url`. 

When I run `kamal setup` and the Dockerfile attempts to run `RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile`, I get `ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory`.

~3 weeks ago I was able to deploy with the following setup, but today I could no longer deploy. Any ideas?

Dockerfile
```Dockerfile
# syntax=docker/dockerfile:1
# check=error=true

# For a containerized dev environment, see Dev Containers: https://guides.rubyonrails.org/getting_started_with_devcontainer.html

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.3.5
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

# Rails app lives here
WORKDIR /rails

# This is used by the app to show the commit HTML files
ARG COMMIT_SHA
ENV COMMIT_SHA=$COMMIT_SHA

# Set production environment
ENV RAILS_ENV="production" \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="development:test"

# Remove old bundler (any defaults shipeed with Ruby) versions
ARG BUNDLER_VERSION
# RUN gem update --system --no-document && \
RUN gem uninstall bundler -a -x && \
    gem install -N bundler -v $BUNDLER_VERSION

# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install JavaScript dependencies
ARG NODE_VERSION
ARG YARN_VERSION
ENV PATH=/usr/local/node/bin:$PATH
RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \
    /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node && \
    npm install -g yarn@$YARN_VERSION && \
    rm -rf /tmp/node-build-master

# Throw-away build stage to reduce size of final image
FROM base AS build

# Install packages needed to build gems and node modules
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev node-gyp pkg-config python-is-python3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install application gems
COPY Gemfile Gemfile.lock vendor ./
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile --gemfile

# Install node modules
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy application code
COPY . .

# Precompile bootsnap code for faster boot times
RUN bundle exec bootsnap precompile app/ lib/

RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile

RUN rm -rf node_modules

# Final stage for app image
FROM base

# Copy built artifacts: gems, application
COPY --from=build "${BUNDLE_PATH}" "${BUNDLE_PATH}"
COPY --from=build /rails /rails

# Run and own only the runtime files as a non-root user for security
RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
    chown -R rails:rails db log storage tmp
USER 1000:1000

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Start server via Thruster by default, this can be overwritten at runtime
EXPOSE 80
CMD ["./bin/thrust", "./bin/rails", "server"]
```

deploy.yml
```yml
service: my-service

image: user/my-service

servers:
  web:
    - 11.22.333.444
proxy:
  ssl: true
  host: my-service.my-domain.com

registry:
  username: my-user

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: DB_HOST
    RAILS_LOG_LEVEL: debug

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "my-service_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

  args:
    RUBY_VERSION: <%= `cat .ruby-version` %>
    NODE_VERSION: <%= `cat .node-version` %>
    YARN_VERSION: <%= `cat .yarn-version` %> # .yarn-version is not an official method
    BUNDLER_VERSION: <%= `cat .bundler-version` %> # .bundler-version is not an official method
    COMMIT_SHA: <%= `git rev-parse --short HEAD`.chomp %>
  cache:
    type: registry

ssh:
  user: my-user
  keys: [ "~/.ssh/deploy_key.pem" ]

```

database.yml

```yml
production:
  primary: &primary_production
    <<: *default
    database: service_production
    url: <%= Rails.application.credentials.db_url %>
```

secrets

```bash
SECRETS=$(kamal secrets fetch --adapter 1password --account 12345678 --from Company/Service KAMAL_REGISTRY_PASSWORD RAILS_MASTER_KEY DB_HOST)

KAMAL_REGISTRY_PASSWORD=$(kamal secrets extract KAMAL_REGISTRY_PASSWORD ${SECRETS})
RAILS_MASTER_KEY=$(kamal secrets extract RAILS_MASTER_KEY ${SECRETS}) # Value is equal to config/credentials/production.key
DB_HOST=$(kamal secrets extract DB_HOST ${SECRETS})

```
