### ISSUE TITLE
Add missing feature for mTLS (for everything or specific paths)

### ISSUE THREAD

**Issue by savar** [basecamp/kamal#1484]
I have the problem right now, that I need to be able to secure a specific path/endpoint with an mTLS certificate.

It would be nice if `kamal-proxy` would support something like that.

Not sure where/how to put the config though.

Maybe within the [host/hosts](https://kamal-deploy.org/docs/configuration/proxy/#hosts) setting or a new one like:

```yaml
mTLS:
  - hosts: # optional, if left out, apply for all hosts specified in the 'host/hosts' section which already exists
      - foo.example.com
    path: # optional, if left out, apply to all path's for 'hosts'
      - type: exact # can also be 'prefix' or 'regex'
        pattern: /webhooks/callback
    certificate: |
       .... certificate ...
``` 

**Disclaimer**: I am not sure if there are things in `kamal-proxy` I just don't know about or not well enough (like `roles` or other features) which would not fit well with this approach, but as I tried to stick to the `host/hosts` feature, I hope it somehow would fit/work.
