### ISSUE TITLE
Error when kamal setup on aws with ecr

### ISSUE THREAD

**Issue by mooktakim** [basecamp/kamal#1487]
Hi,

Here is my deploy config:
```yaml
# Name of your application. Used to uniquely configure containers.
service: appname

# Name of the container image.
image: appname/appname

# Deploy to these servers.
servers:
  web:
    hosts:
      - 123.123.123 # app01
  job:
    hosts:
      - 123.123.123 # app01
    cmd: "bundle exec sidekiq"

registry:
  server: 123.dkr.ecr.eu-west-2.amazonaws.com
  username: AWS
  password: <%= %x(aws ecr get-login-password --region eu-west-2 --profile appname) %>

builder:
  arch: amd64
  cache:
    type: registry
```

When I run `kamal setup`, I don't understand why I'm getting the following error:
```shell
#24 [build 4/7] COPY --from=node /usr/local/node /usr/local/node
#24 CACHED

#25 [node 3/3] RUN --mount=type=cache,id=bld-yarn-cache,target=/root/.yarn     YARN_CACHE_FOLDER=/root/.yarn yarn install --frozen-lockfile
#25 CACHED

#26 [stage-4 2/5] RUN pip3 install --no-cache-dir markitdown
#26 CACHED

#27 [node 2/3] COPY package.json yarn.lock ./
#27 CACHED

#28 [stage-4 3/5] COPY --from=build /usr/local/bundle /usr/local/bundle
#28 CACHED

#29 [stage-4 5/5] RUN groupadd -f -g 1000 rails &&     useradd -u 1000 -g 1000 rails --create-home --shell /bin/bash &&     chown -R rails:rails db log storage tmp
#29 CACHED

#30 exporting to image
#30 exporting layers done
#30 exporting manifest sha256:6b8567c9c2e4757f01b659768a38bf5910ebe3a529c50ddb9bfe9bf6ab342cdc done
#30 exporting config sha256:4b783bf35a4cff16c612c5a8c549206a578039dfa40fbbb9234d813c18eb4dd0 done
#30 exporting attestation manifest sha256:396883ba74bea80605af25977794ae2b6bd9ddf4658ab17af2e7617a247c1150 done
#30 exporting manifest list sha256:015d4c582f54328c6f1446653c6bb681243f9619671937a01f1a0219cea3aafa done
#30 pushing layers
#30 pushing layers 0.5s done
#30 pushing manifest for 123.dkr.ecr.eu-west-2.amazonaws.com/appname/appname:232c63ad68a5e26caa054a785b3e0708b56a04fc@sha256:015d4c582f54328c6f1446653c6bb681243f9619671937a01f1a0219cea3aafa
#30 pushing manifest for 123.dkr.ecr.eu-west-2.amazonaws.com/appname/appname:232c63ad68a5e26caa054a785b3e0708b56a04fc@sha256:015d4c582f54328c6f1446653c6bb681243f9619671937a01f1a0219cea3aafa 0.6s done
#30 pushing layers 0.2s done
#30 pushing manifest for 123.dkr.ecr.eu-west-2.amazonaws.com/appname/appname:latest-aws@sha256:015d4c582f54328c6f1446653c6bb681243f9619671937a01f1a0219cea3aafa
#30 pushing manifest for 123.dkr.ecr.eu-west-2.amazonaws.com/appname/appname:latest-aws@sha256:015d4c582f54328c6f1446653c6bb681243f9619671937a01f1a0219cea3aafa 0.4s done
#30 DONE 1.7s

#31 exporting cache to registry
#31 preparing build cache for export
#31 writing layer sha256:03a38ff6a645e43713fa369c8b5501472decbb21725dc68a6e8863ee457f36a2
#31 preparing build cache for export 16.7s done
#31 writing layer sha256:03a38ff6a645e43713fa369c8b5501472decbb21725dc68a6e8863ee457f36a2 0.2s done
#31 ERROR: error writing layer blob: unexpected status from POST request to https://123.dkr.ecr.eu-west-2.amazonaws.com/v2/kamal-app-build-cache/blobs/uploads/: 404 Not Found
------
 > importing cache manifest from 123.dkr.ecr.eu-west-2.amazonaws.com/kamal-app-build-cache:
------
------
 > exporting cache to registry:
------
ERROR: failed to solve: error writing layer blob: unexpected status from POST request to https://123.dkr.ecr.eu-west-2.amazonaws.com/v2/kamal-app-build-cache/blobs/uploads/: 404 Not Found

View build details: docker-desktop://dashboard/build/kamal-local-docker-container/kamal-local-docker-container0/6e749dj9d617s5kznt6jmlx7v
```

I have created `123.dkr.ecr.eu-west-2.amazonaws.com/appname/appname` and `123.dkr.ecr.eu-west-2.amazonaws.com/appname/appname-build-cache`

I don't understand why its not working.

**Comment by mooktakim** [comment]
I found a fix:
```yaml
builder:
  arch: amd64
  cache:
    type: registry
    options: image-manifest=true

```
