### ISSUE TITLE
Multi container deployments

### ISSUE THREAD

**Issue by duartemvix** [basecamp/kamal#1505]
I'm running a simple, Flask python script that's working locally, but by using Kamal 2 conventions I haven't been able to deploy and build an ephemeral container that the script uses for running a few asynchronous jobs. The container should work a job and shut down after each job.

Given the Kamal setup, I'm able to only run a unique Dockerfile for each deployment, but this application runs by using a `docker-compose.yml` configuration with `docker compose up -d --build`. I really like Kamal, and it seems better than Capistrano, for Ruby apps, but how do I actually deploy this app, not by building containers with `docker build` command.

The actual issue I'm runing into is when `kamal setup` asks me to choose a Dockerfile, but my app doens't have only 1 dockerfile. I build it with `docker compose build`

Would appreciate any tips, or inputs.

A few snippets:

```yml
# docker-compose.yml
services:
  listener:
    container_name: crawler-listener
    build:
      context: .
      dockerfile: Dockerfile.listener
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
    networks:
      - crawler-network
    env_file:
      - .env
    
  job:
    container_name: crawler-job
    build:
      context: .
      dockerfile: Dockerfile.job
    networks:
      - crawler-network
    deploy:
      replicas: 0 # This ensures it doesn't start automatically with `docker compose up`
    env_file:
      - .env

networks:
  crawler-network:
    name: crawler-network
    driver: bridge

```

Thank you!
