### ISSUE TITLE
can't run migrations with external databases

### ISSUE THREAD

**Issue by michelson** [basecamp/kamal#1513]
Hello, I have my Kamal deployment up and running on the server, but I'm having trouble running migrations or preparing the app. 

I am using an external database hosted on a managed server with Digital Ocean, and I have the following configuration set up:

```yaml

default_production: &default_production
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  primary: &primary_production
    <<: *default_production
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *primary_production
    url: <%= ENV['DATABASE_QUEUE_URL'] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    url: <%= ENV['DATABASE_CABLE_URL'] %>
    migrations_paths: db/cable_migrate
  cache:
    <<: *primary_production
    url: <%= ENV['DATABASE_CACHE_URL'] %>
    migrations_paths: db/cache_migrate
```
The issue I'm facing is that the app seems to attempt connecting to a local database when I run the commands `rails db:migrate` or `rails db:prepare`. However, the server operates normally. I can also access the Rails console without any problems. When I enter the console using bash and run `rails c`, everything works fine. Yet, when I execute `rails db:migrate`, I encounter an issue with the server.

```bash

➜  pullentity3 git:(main) kamal app exec -i bash

Get most recent version available as an image...
Launching interactive command with version latest via SSH from new container on 137.184.75.27...
>>>> RAILS_MASTER_KEY is: 8958fa2f9f58919e1f015e49574d24b5
>>>> DATABASE_URL is: postgresql://doadmin:cvuzos348t1cjjts@db-postgresql-nyc3-87365-do-user-132234-0.b.db.ondigitalocean.com:25060/defaultdb?sslmode=require

rails@c8a2834e78fe:/rails$ bundle exec rails db:migrate
bin/rails aborted!
ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory (ActiveRecord::ConnectionNotEstablished)
        Is the server running locally and accepting connections on that socket?


Caused by:
PG::ConnectionBad: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory (PG::ConnectionBad)
        Is the server running locally and accepting connections on that socket?

Tasks: TOP => db:migrate
(See full trace by running task with --trace)
rails@c8a2834e78fe:/rails$ rails c
bash: rails: command not found
```

THIS ON THE SAME SSH SESSION

```bash
rails@c8a2834e78fe:/rails$ bundle exec rails c
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/rails/app/services/github.rb:3: warning: /usr/local/lib/ruby/3.3.0/csv.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add csv to your Gemfile or gemspec to silence this warning.
Loading production environment (Rails 8.0.2)
pullentity(prod)> Site.first
=> 
#<Site:0x000077d6693661b0
 id: 1,
 user_id: 1,
 name: "michelsongs",
 custom_domain: "",
 subdomain: "michelsongs",
 slug: "michelsongs",
 password: nil,
 created_at: "2012-04-14 17:14:32.000000000 +0000",
 updated_at: "2025-04-21 01:28:33.530618000 +0000",
 description: "",
 keywords: "",
 analytics: "",
 activated: true,
 fb_app: nil,
 screenshot: "open-uri20180211-28876-1l2q4sz",
```

Super weird, what could be happening here?

**Comment by michelson** [comment]
> It's trying to connect to a local Postgres DB - maybe RAILS_ENV is not set correctly?
> 
> Does this work?
> 
> RAILS_ENV=production bundle exec rails db:migrate

RAILS_ENV is set correctly. As I mentioned, when I enter the Rails console, I can access ActiveRecord, but when I run the' rails db: migrate' command, I encounter an issue.

**Comment by jorgefgiron** [comment]
Try prefixing your commands with dotenv, I had a similar issue and this solved it.

`dotenv kamal app exec -i bash`

**Comment by michelson** [comment]
@jorgefgiron thanks but that does not work for me as I do not use .env file


look this example:

### ENTER CONSOLE:

`kamal app exec -i bash`

EXEC DB: COMMAND
**rails@07c79c748b0f:/rails$ bundle exec rails db:migrate**

FAILS 🔴 
```
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
bin/rails aborted!
ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory (ActiveRecord::ConnectionNotEstablished)
        Is the server running locally and accepting connections on that socket?


Caused by:
PG::ConnectionBad: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory (PG::ConnectionBad)
        Is the server running locally and accepting connections on that socket?
```

**### GET THE ENV** ✅ 

```
rails@07c79c748b0f:/rails$ echo $RAILS_ENV
production
```

**## ENTER CONSOLE** 

**rails@07c79c748b0f:/rails$ bundle exec rails c**

```
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/rails/app/services/github.rb:3: warning: /usr/local/lib/ruby/3.3.0/csv.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add csv to your Gemfile or gemspec to silence this warning.
Loading production environment (Rails 8.0.2)
pullentity(prod)> User.first
=> #<User id: 1, first_name: "Miguel", ....>

pullentity(prod)> SolidQueue::Job.last
=> 
#<SolidQueue::Job:0x00007bc925873038
 id: 88,
 ....
 created_at: "2025-04-26 01:37:31.268929000 +0000",
 updated_at: "2025-04-26 01:37:58.325551000 +0000">
```

**Comment by alec-c4** [comment]
hey! any update with this issue?

**Comment by jthornhill** [comment]
I'm encountering this too on a brand new small app generated from "rails new" with 8.0.2 using the postgres adapter, and I'm pretty confused. In my case I've got an accessory DB on the same host.

Some invocations of `bin/rails` that work as expected:

`bin/rails db -p`
`bin/rails s`

Some invocations that try to find a local database:

`bin/rails db:migrate`
`bin/rails db:create`
`bin/rails db:prepare`

Typical error:

```
$ bin/rails db:prepare --trace                                                                                                                                                               
** Invoke db:prepare (first_time)                                                                  
** Invoke db:load_config (first_time)                                                                                                                                                                                
** Invoke environment (first_time)                                                                                                                                                                                   
** Execute environment                                                                                   
** Execute db:load_config                                                                                                                                                                                            
** Execute db:prepare                                                                                                                                                                                                
bin/rails aborted!                                                                                                                                                                                                   
ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory (ActiveRecord::ConnectionNotEstablished)                                
        Is the server running locally and accepting connections on that socket?                                                                                        
```

Some ENV:

```
DATABASE_URL=postgresql://myapp:changeme@db:5432
RAILS_ENV=production
```

`database.yml` is the default from the generator

```
$ bin/rails db -p
psql (15.13 (Debian 15.13-0+deb12u1), server 16.9 (Debian 16.9-1.pgdg120+1))
WARNING: psql major version 15, server major version 16.
         Some psql features might not work.
Type "help" for help.

myapp_production=#
```

deploy.yml
```
accessories:
  db:
    service: db
    image: postgres:16
    host: <%= ENV["SITENAME"] %>
    port: 5432
    env:
      clear:
        POSTGRES_DB: psshim_production
        POSTGRES_USER: psshim
      secret:
        - POSTGRES_PASSWORD
    directories:
      - database:/var/lib/postgresql/data
```
