### ISSUE TITLE
Error: proxy: should be a hash

### ISSUE THREAD

**Issue by abuisman** [basecamp/kamal#1556]
Hi, 

I've upgraded to kamal 2.6 and now I can't start a console because I get the following error:

`ERROR (Kamal::ConfigurationError): proxy: should be a hash`

My `deploy.yml` config for the proxy looks like this:

```yaml
servers:
  web:
    hosts:
      - ....
  jobs:
    hosts:
      - ...

proxy: false
```

The docs say that it should be that way: https://kamal-deploy.org/docs/configuration/proxy/ or at least that is how I've interpreted the config and how it has worked fine up until now.

Is this the new way?:

```yaml
servers:
  web:
    hosts:
      - ....
    proxy: false
  jobs:
    hosts:
      - ...

```
