### ISSUE TITLE
Allow passing docker volume flags for additional use cases (SELinux)

### ISSUE THREAD

**Issue by bianchidotdev** [basecamp/kamal#1575]
Hey hey. Trying out Kamal to deploy some things and I'm running into issues with SELinux. Specifically, I typically pass a `:z` suffix to volume mounts to automatically configure SELinux rules for the docker mount.

Example in an accessory:
```yml
accessories:
  example:
    service: example
    image: example
    hosts:
      - example.com
    files:
      - ./example.conf:/etc/example/example.conf:z

    proxy: false
```

However, when running with Kamal, this flag is stripped off instead of passed through to the `docker run` command. I'm not sure if other flags are supported too (like `ro`), but these volume mount flags are usually pretty useful and necessary for certain linux setups.

**Comment by bianchidotdev** [comment]
For anyone else running into this issue, I kind of hacked around it by using the special `options` syntax, which I only knew how to do since I was also needing to publish multiple ports

```yml
    files:
      - ./example.conf:/etc/example/tmp.conf
    options:
      publish:
        - "8080:8080"
        - "8081:8081"
      volume: "${PWD}/example/etc/example/tmp.conf:/etc/example/example.conf:z"

```
