### ISSUE TITLE
TailwindCSS 4 assets not compiling correctly after deployment with Kamal 2.7

### ISSUE THREAD

**Issue by DaniG2k** [basecamp/kamal#1597]
I've been bashing my head all day trying to set up Kamal to deploy my application to a simple DigitalOcean VPS. My setup is a very vanilla Rails 8 app, using Bun for JavaScript bundling and TailwindCSS 4. After deploying, the assets are not being compiled correctly, and I’m not seeing any errors, which makes it tough to figure out what’s going wrong.

Here’s my `config/deploy.yml` configuration, stripped of comments and with sensitive details replaced:

```yml
service: myapp
image: mydockerhubuser/myapp
servers:
  - 123.45.67.89
proxy:
  ssl: true
  host: myapp.123-45-67-89.nip.io
registry:
  server: registry.hub.docker.com
  username: mydockerhubuser
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
    - MYAPP_DATABASE_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: myapp-db
    RAILS_ENV: production
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
ssh:
  user: deploy
accessories:
  db:
    image: postgres:17
    roles:
      - web
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: myapp
        POSTGRES_DB: myapp_production
      secret:
        - MYAPP_DATABASE_PASSWORD
        - POSTGRES_PASSWORD
    directories:
      - myapp_pg_data:/var/lib/postgresql/data
volumes:
  - "myapp_storage:/rails/storage"
asset_path: /rails/public/assets
builder:
  arch: amd64
```
I’ve followed the Kamal documentation and double-checked my setup, but the assets still aren’t compiling as expected after deployment. 

the Dockerfile is nothing fancy:

```
# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.4.4
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV RAILS_ENV="production" \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="development"

FROM base AS build

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev libyaml-dev pkg-config unzip && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUN_INSTALL=/usr/local/bun
ENV PATH=/usr/local/bun/bin:$PATH
ARG BUN_VERSION=1.2.17
RUN curl -fsSL https://bun.sh/install | bash -s -- "bun-v${BUN_VERSION}"

COPY Gemfile Gemfile.lock ./
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile --gemfile

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

RUN bundle exec bootsnap precompile app/ lib/

RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile

FROM base

COPY --from=build "${BUNDLE_PATH}" "${BUNDLE_PATH}"
COPY --from=build /rails /rails

RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
    chown -R rails:rails db log storage tmp
USER 1000:1000

ENTRYPOINT ["/rails/bin/docker-entrypoint"]
EXPOSE 80
CMD ["./bin/thrust", "./bin/rails", "server"]
```

I saw that this could be related to Docker and Rosetta compilation for x86_64/amd64 on Apple Silicon. I disabled that option to no avail (btw I'm running MacOS 15.5)

My `application.tailwind.css` file (this seems to be the way to do it in Tailwind 4):

```css
@import "tailwindcss";
```

The app gets deployed but the Tailwind assets don't get delivered properly. Any idea why the assets wouldn't be compiling correctly? Would really appreciate any guidance here.
Thanks in advance!
