### ISSUE TITLE
Kamal accessory boot is not passing secret in cmd

### ISSUE THREAD

**Issue by jvillegasd** [basecamp/kamal#1598]
I'm trying to setup a password for my Redis accessory; due to the way the official Redis docker image is set up, I need to pass in a `"/bin/sh -c 'redis-server --requirepass $REDIS_PASSWORD'"`. In my Kamal deploy.yml, I have the following block:

````
accessories:
  redis:
    image: redis:8.0
    host: A.B.C.D
    cmd: bash -c "redis-server --requirepass $REDIS_PASSWORD"
    env:
      secret:
        - REDIS_PASSWORD
    directories:
      - data:/data
```

I don't think putting the raw password inside `deploy.yml` is the right approach here so that's why I'm trying to insert a secret in the `cmd`.

I already tried the solution in this `issue`: https://github.com/basecamp/kamal/issues/525 but it didn't work
