### ISSUE TITLE
Health check endpoint is disabled for Traefik

### ISSUE THREAD

**Issue by kimrgrey** [basecamp/kamal#228]
Traefik has it's own health check endpoint called "ping". Here is a documentation: https://doc.traefik.io/traefik/operations/ping/. By default this endpoint connects to the entrypoint "traefik" (port 8080). But when traefik is started by mrsk this endpoint is not exposed, which means that external load balancer can not be configured to check if traefik is actually alive. Should we enable ping by default and expose port 8080?

At the moment it is possible to achieve it by adding following config:

```yaml
traefik:
  args:
    accesslog: true
    ping: true
  options:
    publish:
      - 8080:8080
```

But IMHO it could be a reasonable default behavior. Possible concern here is that not only 80 (main HTTP), but also 8080 (technical) will be exposed from server.
