### ISSUE TITLE
[Feature] Allow add extra traefik middewares in role config

### ISSUE THREAD

**Issue by xiaohui-zhangxh** [basecamp/kamal#300]
Now, traefix  middlewares is hardcoded as `#{traefik_service}-retry@docker`, if I need add extra middlewares, I have to know what `#{traefik_service}` is, from different destination `traefik_service` have different values, then have to set this extra middlewares in all destination config files.

https://github.com/mrsked/mrsk/blob/a7d869ad40b2a39286139f5c110d679602ba160d/lib/mrsk/configuration/role.rb#L96

```ruby
    def traefik_labels
      if running_traefik?
        {
          # Setting a service property ensures that the generated service name will be consistent between versions
          "traefik.http.services.#{traefik_service}.loadbalancer.server.scheme" => "http",

          "traefik.http.routers.#{traefik_service}.rule" => "PathPrefix(`/`)",
          "traefik.http.middlewares.#{traefik_service}-retry.retry.attempts" => "5",
          "traefik.http.middlewares.#{traefik_service}-retry.retry.initialinterval" => "500ms",
          "traefik.http.routers.#{traefik_service}.middlewares" => "#{traefik_service}-retry@docker"
        }
      else
        {}
      end
    end
```

What if we could define extra middlewares in `config/deploy.yml` like this:

**before**

```yaml
# config/deploy.yml

service: myapp
servers:
  web:
    hosts:
      - 192.168.2.5
    labels:
      traefik.http.routers.myapp-web.middlewares: myapp-web-retry,cloudflarewarp
```

```yaml
# config/deploy.staging.yml

service: myapp
servers:
  web:
    hosts:
      - 192.168.2.5
    labels:
      traefik.http.routers.myapp-web.middlewares: myapp-web-staging-retry,cloudflarewarp
```

**after**

```yaml
servers:
  web:
    hosts:
      - 192.168.2.5
    traefik:
      middlewares:
      - cloudflarewarp
```

**Comment by Novtopro** [comment]
@xiaohui-zhangxh As a workaround, you could just define another router with higher priority and configure the middlewares you want.

<img width="1432" alt="1" src="https://github.com/mrsked/mrsk/assets/7251140/16ad1f48-d9fc-4861-b664-4ec20fb856fe">

```
servers:
  web:
    hosts:
      - 1.1.1.1
    options:
      network: sourcingforce
    labels:
      traefik.http.middlewares.ratelimit.ratelimit.average: 100
      traefik.http.middlewares.ratelimit.ratelimit.burst: 50
      traefik.http.middlewares.retry.retry.attempts: 5
      traefik.http.middlewares.retry.retry.initialinterval: 100ms
      traefik.http.routers.web.rule: Host(`sourcingforce.shop`) && PathPrefix(`/`)
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.web.tls.certresolver: letsencrypt
      traefik.http.routers.web.middlewares: ratelimit,retry
```
