### ISSUE TITLE
ENV variable overloading

### ISSUE THREAD

**Issue by Zeko369** [basecamp/kamal#346]
### My idea of how this should work

Assuming this is my config, I'd want it to override the APP_NAME with "Foobar" in staging
```yml
# deploy.yml
env:
  secret:
    - APP_NAME

# deploy.staging.yml
env:
  clear:
    APP_NAME: "Foobar"
```

### How it works

It throws and says "APP_NAME" is missing, since it wasn't loaded in ENV by mrsk before being called  and not complain about the missing ENV variable [here](https://github.com/mrsked/mrsk/blob/9a501867b438761239b32c9a8ae7c750aa4d12c6/lib/mrsk/utils.rb#L21-L27)

Is it a bug that this throws or intentional?

PS: I'd love to PR a fix that would load the clear envs before trying to fetch secrets this
