### ISSUE TITLE
Forward multiple ports for the accessory

### ISSUE THREAD

**Issue by bohdan-shulha** [basecamp/kamal#347]
Hi team. :)

Yet another approach to mrsk.

This time, I have an issue setting up rabbitmq.

I need to forward (at least) two ports to the host machine and one port to the internet: one for consumers connection, second one for the management console.

I've tried to set it up intuitively, but this one, obviously, didn't work.
```
accessories:
  port:
    - 5672
    - 15672
```
```
docker run --name app-rabbitmq --detach --restart unless-stopped --log-opt max-size="10m" --publish [5672, 15672]:[5672, 15672] -e RABBITMQ_USERNAME="root" -e RABBITMQ_PASSWORD="root" --label service="app-rabbitmq" bitnami/rabbitmq:latest on 1.1.1.1
```

This is the example how it could work:
```
accessories:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    host: 1.1.1.1
    ports:
      - 5672:5672
      - 15672:15672
    env:
      clear:
        RABBITMQ_USERNAME: "root"
        RABBITMQ_PASSWORD: "root"
```

**Comment by bohdan-shulha** [comment]
@dhh , would it be possible to release this one as 14.1? I'd love to switch our staging environment from kube-hell to mrsk and it seems to be the single blocker for me.

**Comment by scart88** [comment]
This already works with the publish option. Here is a working example.

```yaml
accessories:
  questdb:
      image: questdb/questdb:7.3
      options:
        publish:
          - "9000:9000"
          - "9003:9003"
          - "9009:9009"
          - "8812:8812"
      host: 10.1.0.16
      add-host: 10.1.0.16
      directories:
        - questdb:/var/lib/questdb
```
