### ISSUE TITLE
Create repository of MRSK example configurations

### ISSUE THREAD

**Issue by Nezteb** [basecamp/kamal#355]
I'm loving MRSK so far, and [the configuration docs are solid](https://mrsk.dev/docs/configuration), but I'm having trouble finding any full application config to use as examples that I can learn from.

I'm thinking of something similar to:
- https://github.com/kubernetes/examples
- https://github.com/ContainerSolutions/kubernetes-examples
- https://github.com/ansible/ansible-examples

Some ideas / example apps:
- [ ] [Rails + SQLite3](https://guides.rubyonrails.org/getting_started.html#hello-rails-bang)
- [ ] [Elixir/Phoenix + Postgres](https://hexdocs.pm/phoenix/up_and_running.html)
- [ ] [WordPress + MySQL + nginx](https://developer.wordpress.org/advanced-administration/before-install/howto-install/)
- [ ] [PHP + Redis](https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook)

**Comment by Nezteb** [comment]
Initial search for existing MRSK configs on GitHub: https://github.com/search?q=path:/deploy.yml$/+/^servers:/+/^image:/+(NOT+repo:mrsked/mrsk)+(NOT+is:fork)&type=code

**Comment by Zeko369** [comment]
There is also this great guide from @huksley for deploying next.js https://medium.com/@ruslanfg/deploying-nextjs-using-mrsk-819aa9eb83ba

**Comment by huksley** [comment]
thanks @Zeko369  here also some example configurations https://gist.github.com/huksley/70c8615f41c7871700c1dafbf518654c

**Comment by igor-alexandrov** [comment]
There is also my article about deploying Rails on AWS with GitHub Actions: https://jetrockets.com/blog/how-to-use-basecamp-s-mrsk-with-aws-and-github

**Comment by scart88** [comment]
HA Redis with Sentinel support here: https://github.com/mrsked/mrsk/discussions/382

**Comment by scart88** [comment]
Add these to your `package.json` file and you will save some time ...

```json
"scripts": {
    "logs": "mrsk app logs --follow",
    "console": "mrsk app exec -i 'bin/rails console'",
    "migrate": "mrsk app exec -i 'bin/rails db:migrate'",
    "release": "mrsk lock release",
    "bash": "mrsk app exec -i bash",
}
```

```
$: yarn run console
❯ yarn run console
yarn run v1.22.19
$ mrsk app exec -i 'bin/rails console'
Get most recent version available as an image...
Launching interactive command with version latest via SSH from new container on
Loading production environment (Rails 7.0.6)
irb(main):001:0> 
```

**Comment by scart88** [comment]
If you need a time series database, QuestDB is really cool and pretty easy to use:

```yaml
accessories:
  questdb:
    image: questdb/questdb:7.2.1
    options:
      publish:
        - "9000:9000"
        - "9003:9003"
        - "9009:9009"
        - "8812:8812"
    host: 10.0.0.1
    add-host: 10.0.0.1
    directories:
      - questdb:/var/lib/questdb
```

```
$: mrsk accessory boot questdb
```

**Comment by scart88** [comment]
A simple hourly PostgreSQL Backup solution using pg_dump

### Hourly backups
```yaml
pg_backup:
    image: prodrigestivill/postgres-backup-local
    host: 10.0.0.1
    port: "10.0.0.1:5400:5400"
    add-host: 10.0.0.1
    directories:
      - pg_backup:/backups
    env:
      clear:
        SCHEDULE: '@hourly'
        POSTGRES_BACKUP_ALL: "false"
        POSTGRES_HOST: <%= ENV["DB_HOST"] %>
        POSTGRES_DB: <%= ENV["DB_NAME"] %>
        POSTGRES_USER: <%= ENV["DB_USER"] %>
        POSTGRES_PASSWORD: <%= ENV["DB_PASSWORD"] %>
        POSTGRES_EXTRA_OPTS: '-Z6 --superuser=postgres/your-user --no-owner --schema=public --blobs'
        BACKUP_KEEP_DAYS: 7
        BACKUP_KEEP_WEEKS: 4
        BACKUP_KEEP_MONTHS: 1
        HEALTHCHECK_PORT: 5401
```

### Restore to a new PSQL host:
```yaml
$: PRIMARY_POSTGRES_PASSWORD=your_pg_password
$: zcat /root/[your-container-directory]/backups/last/[backup-file].sql.gz | PGPASSWORD=$PRIMARY_POSTGRES_PASSWORD psql --host=$DB_HOST --port=$DB_PORT --username=$DB_USER --dbname=$DB_NAME
```

### Manual Backup:
Add this line to your `package.json` file

```json
"scripts": {
    "start_backup": "mrsk accessory exec pg_backup -i /backup.sh",
    "view_backups": "ssh root@10.0.0.1 ls -lsh /root/[your-container-directory]/backups/last/"
}
```

```bash
$: yarn run start_backup # start backup
$: yarn run view_backups # view all backups inside the latest backups directory
```
