### ISSUE TITLE
Сan I run accessories with virtual hostname? 

### ISSUE THREAD

**Issue by OlexanderKulyk** [basecamp/kamal#363]
Can i run accessories with a virtual hostname?  for example:

hostname: postgres_container

**Comment by djmb** [comment]
Sorry, very late to answering this, but yes you can do this be specifying accessory options which are passed to the `docker run` command:

So something like:
```
accessories:
  busybox:
    service: custom-busybox
    image: registry:4443/busybox:1.36.0
    cmd: sh -c 'echo "Starting busybox..."; trap exit term; while true; do sleep 1; done'
    options:
      hostname: foo
    roles:
      - web
```

That starts the container with:

```
$ docker run --name custom-busybox --detach --restart unless-stopped --log-opt max-size="10m" --env-file .kamal/env/accessories/custom-busybox.env --label service="custom-busybox" --hostname "foo" registry:4443/busybox:1.36.0 sh -c 'echo "Starting busybox..."; trap exit term; while true; do sleep 1; done'
```

If you start that accessory and then on the host run this, you'll see:
```
$ docker exec -it custom-busybox hostname
foo
```
