### ISSUE TITLE
hosts delegated to accessory_config.hosts, but accessory_config is nil

### ISSUE THREAD

**Issue by clwy-cn** [basecamp/kamal#424]
My deploy.yml 

```yml
  accessories:
    db:
      image: mysql:8.0
      host: 10.0.0.35
      port: 3306
      env:
        clear:
          MYSQL_ROOT_HOST: '%'
        secret:
          - MYSQL_ROOT_PASSWORD
      files:
#        - config/mysql/production.cnf:/etc/mysql/my.cnf
        - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
      directories:
        - data:/var/lib/mysql
```

then I run `mrsk accessory start db`

<img width="1655" alt="image" src="https://github.com/basecamp/kamal/assets/57120683/bcd62696-c64d-46ea-8c6c-dd79f95e344b">
