### ISSUE TITLE
Kamal is not recognizing the service as healthy

### ISSUE THREAD

**Issue by AliOsm** [basecamp/kamal#474]
I'm trying to use Kamal to deploy a FastAPI application on the same server that is running my Ruby on Rails application. The server currently is running Ruby on Rails application using Caddy. Caddy is using port 80 and the Rails app is using port 9000.

For the FastAPI application, I created the following Dockerfile:

```dockerfile
FROM python:3.11 as requirements-stage

WORKDIR /tmp
RUN pip install poetry
COPY ./pyproject.toml ./poetry.lock* /tmp/
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim

ENV MODULE_NAME=src.baheth_ss.main
ENV WEB_CONCURRENCY=2
ENV PORT=3000
ENV TIMEOUT=1500
ENV GUNICORN_CMD_ARGS="--preload"

WORKDIR /code
COPY --from=requirements-stage /tmp/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./ /code/

EXPOSE 3000
```

And the following Kamal deploy.yml config:

```yml
service: baheth_ss
image: ieasybooks/baheth_ss
servers:
  web:
    hosts:
      - x.x.x.x
    options:
      cpus: 2.0
      memory: 5g
registry:
  username: ieasybooks
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - USE_ONNX_RUNTIME
    - HF_ACCESS_TOKEN
    - HF_MODEL_ID
    - HADITHS_DATA_FILE_PATH
    - HADITHS_DATA_FILE_URL
traefik:
  host_port: 81
healthcheck:
  path: /are_you_healthy
  port: 3000
  max_attempts: 25
```

I'm using `host_port: 81` for Traefik as Caddy is using port 80 as mentioned before. When I run `kamal deploy` it fails with exception `container not ready`, but while the deployment is running (Before Kamal stops the container), I tried to run curl commands against the container like this:

```bash
curl 127.0.0:3000/are_you_healthy
```

Which outputs:

```bash
curl: (7) Failed to connect to 127.0.0.1 port 3000 after 0 ms: Connection refused
```

While running:

```bash
curl 127.0.0:3999/are_you_healthy
```

Returns "Yes" as expected.

The deployment logs are not showing any errors, the gunicorn server is running and I can see:

```
[2023-09-17 05:59:08 +0000] [15] [INFO] Application startup complete.
[2023-09-17 05:59:08 +0000] [14] [INFO] Application startup complete.
```

From the 2 workers.

Am I missing something in the Dockerfile or Kamal configs?
