### ISSUE TITLE
Env vars not loading for non-ruby project

### ISSUE THREAD

**Issue by fritzblue** [basecamp/kamal#489]
In a non-ruby project, with the following `registry` block in `deploy.yml`:

```
registry:
  server: ghcr.io
  username: myuser
  password: ["KAMAL_REGISTRY_PASSWORD"]
```

and the following in `.env`:

```
KAMAL_REGISTRY_PASSWORD=the_password
```

I get the following when running `kamal registry login`:

```
  ERROR (SSHKit::Command::Failed): docker exit status: 256
docker stdout: Nothing written
docker stderr: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get "https://ghcr.io/v2/": denied: denied
```

However, if I inline the env var like this: `KAMAL_REGISTRY_PASSWORD=the_password kamal registry login` then it logs in successfully.

So it appears that for some reason it's not auto-loading the vars in the `.env`.

Do I need to do anything special to get dotenv to load the file?

**Comment by djmb** [comment]
Hi @fritzblue, I think you need `<%= ENV["BASECAMP_REGISTRY_PASSWORD"] %>` rather than `["KAMAL_REGISTRY_PASSWORD"]`

**Comment by nickhammond** [comment]
This format sets the password as-is instead of loading from .env:

```
password: ["KAMAL_REGISTRY_PASSWORD"]
```

You want something like this. If you only need the one username then you can keep that like you have but the password part should be structured like this to load from .env. 

```
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
```

**Comment by lethunder** [comment]
heys guys,
having the same problem

 ERROR (SSHKit::Command::Failed): docker exit status: 256
docker stdout: Nothing written
docker stderr: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF

when running kamal setup

**Comment by terales** [comment]
This happens to me when using a non-root user.
These commands that I've manually run helped ([source](https://stackoverflow.com/a/48957722)):
```bach
# no need to add a docker group, it's already exists
# sudo groupadd docker

sudo usermod -aG docker $USER
newgrp docker
```

**Comment by williamkennedy** [comment]
Hey Folks,

I had the same problem as @lethunder 

```
ERROR (SSHKit::Command::Failed): docker exit status: 256
docker stdout: Nothing written
docker stderr: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF
```

It turned out it was because docker was not running. I turned on docker via the Desktop app on my m2 Mac

**Comment by erichstark** [comment]
@williamkennedy thanks for this comment! It worked for me to just open docker 😏

**Comment by buncis** [comment]
this error message also could be ur GITHUB token is expired or wrong

**Comment by yobfountain** [comment]
I also ran into this issue. I changed the variable from a string to an array:

```YAML
# what kamal generated
password:  KAMAL_REGISTRY_PASSWORD

# what I needed
password: 
    - KAMAL_REGISTRY_PASSWORD 
```
