### ISSUE TITLE
Skip building an deploy some public docker image (listed at Docker Hub)

### ISSUE THREAD

**Issue by meglio** [basecamp/kamal#497]
I could not find where the documentation explains how to make Kamal skip the "build" step and just deploy some docker image found at the public Docker Hub.

![image](https://github.com/basecamp/kamal/assets/282177/c29d0a7f-680a-45f7-925f-8209039775be)

**Comment by meglio** [comment]
I think I found it in the Config section:

<img width="1188" alt="image" src="https://github.com/basecamp/kamal/assets/282177/68bee653-c6bc-49be-9f0e-811bf27675f5">

**Comment by meglio** [comment]
Still, it is looking for some Dockerfile. Can it do without it and just use the public docker image?

<img width="687" alt="image" src="https://github.com/basecamp/kamal/assets/282177/f8393b82-e2df-43d1-9758-ab8460b6cc42">

**Comment by akoskovacs** [comment]
This would be really helpful even, when you already have a built private image (from the same `ghcr.io` registry that you use in `deploy.yml`).

I would image the `deploy.yml` having something this as an option:
```yml
builder:
  disable: true
```

**Comment by n1xn** [comment]
I'm in the same boat and also need to skip the builder step. As my workflow requires to run rails tests and linters successfully before pushing it to ghcr registry. With the current solution I would build the image twice. 

```
on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build & cache Docker image
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: ${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: run Rails tests & linter
        run: docker-compose -f docker-compose.ci.yml up --abort-on-container-exit

      - name: log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

  #__DEPLOY
```

**Comment by Intrepidd** [comment]
I'm also trying to deploy a public image with kamal and encounter some of the same issues.

Even with `kamal deploy -P`, kamal will try to get an image that has been tagged with the current commit sha.
Even with `kamal deploy -P --version=v0.48.1`, kamal will fail because the image does not have the `service` label

I think I'll have to create a one-line Dockerfile that is just a `FROM some/publicimage` to bypass this but it would be so so great to be able to easily release any public docker image with kamal

**Comment by flozano** [comment]
I am evaluating kamal for my use-case but I'm having the same problem. My build process generates an image already, I just want to release it. Making the build process optional for the entire workflow would be great.

**Comment by spryffee** [comment]
Same issue for me. Not having the ability to skip build step makes Kamal nearly useless for public images

**Comment by RyanMcCoskrie** [comment]
This is a feature Kamal is desperately missing.

I have made an open source rails app and have been trying to figure out how to best simplify deployment for other people. At present using DockerHub + Kamal would require sharing my password with the entire world.

Please add a no-login option.

**Comment by sulo1337** [comment]
What I'm doing currently is creating a dummy busybox container for a placeholder in the service so I can deploy public docker images as an accessory. 

Dockerfile example:
```Dockerfile
FROM busybox:1.36.1

CMD ["tail", "-f", "/dev/null"]
```
kamal-config example:
```yaml
# Name of your application. Used to uniquely configure containers.
service: kamal-test

# Name of the container image.
image: <registry-username>/kamal-test

servers:
  - 1.1.1.1

registry:
  username: <registry-username>
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: <ssh-user>

accessories:
  app:
    image: nginx:1.24.0
    host: 1.1.1.1
    port: 127.0.0.1:8080:80
    files:
      - nginx.conf:/etc/nginx/nginx.conf

# Since the dummy service is not serving anything, healthcheck is set to true.
# probably there are other ways to optimize this to get true healthcheck (proxying healthcheck to "app" accessory)
healthcheck:
  cmd: /bin/true
```

**Comment by benbonnet** [comment]
Would indeed be great to just update the `config/deploy.yaml` with an already built image.
A `--skip-build` would be so great.

As `primary_role` looks required, and by assuming the following (an extra "image" key containing the already built image) :
```
...
primary_role: web

servers:
  web:
    hosts:
      - 65.21.1.164
    image: "tagged_imge_name" # <<<--- does not exists (yet) ?
...
```

it looks doable with a [very minimal update here](https://github.com/basecamp/kamal/blob/aea55480adcaf61e3eebfd49f2b8c039207ad0de/lib/kamal/configuration.rb#L115) :
 
```
def absolute_image
  raw_config.servers.dig(raw_config.primary_role, "image") ||
    "#{repository}:#{version}"
end
```
(This single modification provide the expected behaviour when using `--skip-push`)

**Comment by benbonnet** [comment]
Kamal is a wonderful tool, too bad it does not provide this capacity yet

While using --skip-push, a [very minimal change here](https://github.com/basecamp/kamal/blob/aea55480adcaf61e3eebfd49f2b8c039207ad0de/lib/kamal/configuration.rb#L115) would make it all work. 

It could just accepts something from the cli (like `--image xyz:latest`) and skip the build

**Comment by acidtib** [comment]
> Kamal is a wonderful tool, too bad it does not provide this capacity yet
> 
> While using --skip-push, a [very minimal change here](https://github.com/basecamp/kamal/blob/aea55480adcaf61e3eebfd49f2b8c039207ad0de/lib/kamal/configuration.rb#L115) would make it all work.
> 
> It could just accepts something from the cli (like `--tagged-image xyz:latest`) and skip the build

please make a pull request!

**Comment by benbonnet** [comment]
@acidtib I did a very simple hack [in a fork here](https://github.com/benbonnet/kmlrb/commit/06c2a91a6570a21dc661ceaa339126debd7c8a6f). Passing a new arg requires more work.

To be honest, by looking at the code, the "deploying local code only" is deeply rooted. Coupled with the fact that each elements in the `servers:` block use the same image

IMHO a clean fix (rework) would be to prioritize the requirement discussed here, and falling back to the current behaviour (local code build/push)

**Comment by joelcogen** [comment]
Seems like you can achieve this with the `VERSION` env var combined with `-P`. This is the command I use to deploy the latest image (already built for staging) to production:

    VERSION=latest kamal deploy -P -d production

**Comment by djmb** [comment]
Kamal requires that images are labeled with the service, so that it can identify them when pruning.

So right now you can't deploy arbitrary public images. If you have an external image that you've built yourself with the service label, then you can either also tag it with the appropriate git SHA or use @joelcogen's suggestion to override the version.

**Comment by djmb** [comment]
@gregjotau - does it work if you remove the `;` after `VERSION=latest`?

**Comment by djmb** [comment]
That's a requirement of Kamal, you'll need to add a label called "service" to your image. The value should be the same as the service in your Kamal configuration.

**Comment by JUVOJustin** [comment]
Was anybody able to make this work with kamal2? Tried adding the label, and deploying with `kamal deploy -P`.

Part of my deploy.yml:
```
service: gotenberg

image: gotenberg/gotenberg:8

labels:
  service: gotenberg
```

Kamal still tries to log in to the registry every time.

**Comment by denisorehovsky** [comment]
This still hasn’t been fixed after a year? I build an image using GitHub Actions and then push it to GitHub’s registry. I don’t want Kamal to build anything. It’s strange that I can’t skip this step.

**Comment by jdelStrother** [comment]
> Seems like you can achieve this with the `VERSION` env var combined with `-P`. This is the command I use to deploy the latest image (already built for staging) to production:
> 
> ```
> VERSION=latest kamal deploy -P -d production
> ```

Thanks, this was useful. I've been trying for ages to build an image in Github Actions and then deploy it from my Macbook without having to rebuild it locally.  I ended up with `VERSION=$(git rev-parse HEAD) kamal deploy -P`.

**Comment by isteel** [comment]
Proving impossible to deploy pihole/pihole image to a local Pi using kamal2.
From reading these posts it seems that I need to build my own image of pihole, label it to match the service, push it back to dockerhub and then deploy.
But the issue then is that the sha1 from my local git repository (which I had to create as kamal2 insists on using git to determine the latest version) doesn't match the tag on dockerhub.

Am I going down the completely wrong rabbit hole with this? It doesn't feel natural.

**Comment by djmb** [comment]
It's a hard requirement of Kamal right now that images have the `service` label, so we can identify them when pruning. 

We could switch that to filtering by reference instead and drop the requirement, then we could deploy any image which would definitely be nice to be able to do. 

Not completely straightforward though. If someone is deploying multiple apps to a server using the same image, we'd need to make sure app A doesn't try to prune images used by app B.

**Comment by juliusv** [comment]
@djmb Instead of trying to change the behavior for the main app config, would it maybe be easier to make the main app completely optional and run an accessory-only setup? Like in https://github.com/basecamp/kamal/issues/497#issuecomment-1937844494, but without the requirement of creating a dummy container.

**Comment by djmb** [comment]
Good idea @juliusv! I've implemented that in #1501. Works well now you can use kamal-proxy with accessories.

**Comment by juliusv** [comment]
@djmb Nice, thanks!

**Comment by lexcao** [comment]
Hi @djmb 
I'm excited this feature is included in the new version of Kamal.
I'm using it with the latest main branch of Kamal on my local machine.
I found the accessory-only option might not suit my needs.
My attempt failed because of a Docker registry login issue.
I don't want to log in to the Docker registry since I only want to deploy a public image from a public registry.

Here is the error logs 
```
➜ kamal setup
  INFO [65fceba8] Running /usr/bin/env mkdir -p .kamal on [example.com]
  INFO [65fceba8] Finished in 2.486 seconds with exit status 0 (successful).
Acquiring the deploy lock...
Ensure Docker is installed...
  INFO [db5228d2] Running docker -v on keycloak.lexcao.io
  INFO [db5228d2] Finished in 0.372 seconds with exit status 127 (failed).
  INFO [9d17b728] Running [ "${EUID:-$(id -u)}" -eq 0 ] || command -v sudo >/dev/null || command -v su >/dev/null on [example.com]
  INFO [9d17b728] Finished in 0.436 seconds with exit status 0 (successful).
  INFO Missing Docker on [example.com]. Installing…
  INFO [b34249c4] Running /usr/bin/env sh -c 'curl -fsSL https://get.docker.com || wget -O - https://get.docker.com || echo "exit 1"' | sh on [example.com]
  INFO [b34249c4] Finished in 36.245 seconds with exit status 0 (successful).
Build and push app image...
  INFO [c53fef2c] Running docker --version && docker buildx version as localhost
  INFO [c53fef2c] Finished in 0.727 seconds with exit status 0 (successful).
  INFO [0fe47e42] Running docker login -u [REDACTED] -p [REDACTED] as localhost
  Finished all in 3.4 seconds
Releasing the deploy lock...
  Finished all in 43.0 seconds
  ERROR (SSHKit::Command::Failed): docker exit status: 256
docker stdout: Nothing written
docker stderr: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
```

The following is my kamal.yml file
```
service: lex
image: dummy-image

registry:
  username: dummy
  password: dummy

proxy:
  ssl: true
  host: [example.com]

accessories:
  app:
    image: [example image]
```

Is there a better way to deploy the public image without login to the Docker registry?
Can we add `registry.disabled=true` to disable this?

The last thing is the `image` should be optional as well if we use the accessory-only.
