### ISSUE TITLE
Passing a secret to accessory options.

### ISSUE THREAD

**Issue by ejamesc** [basecamp/kamal#525]
I'm trying to setup a password for my Redis accessory; due to the way the official Redis docker image is set up, I need to pass in a `cmd: --requirepass MY_SECRET_PASSWORD` flag. In my Kamal deploy.yml, I have the following block:

```yaml
accessories:
  redis:
    image: redis:7.2.1-alpine
    host: 1.2.3.4
    port: 6379:6379
    cmd: "--requirepass ${REDIS_PASSWORD}"
    env:
      secret:
        - REDIS_PASSWORD
    directories:
      - data:/data
```

Because ideally I would like to have the password be passed to cmd without revealing it. 

This does not work because REDIS_PASSWORD isn't loaded to the host where redis will run (in this example the server 1.2.3.4). REDIS_PASSWORD, in this case, only exists inside the redis container. 

What currently works: doing `cmd: --requirepass MY_SECRET_PASSWORD` in plain text, inside the deploy.yml file. 

I'm not sure if this should be a feature request — should all secrets be loaded into the local env? I'm all ears if you have suggestions for a workaround for this specific problem. Thanks in advance!

**Comment by benbonnet** [comment]
The following does interpolates `REDIS_PASSWORD` env var :

```
accessories:
  redis:
    image: redis:latest
    host: X.X.X.X
    cmd: "/bin/sh -c 'redis-server --requirepass $REDIS_PASSWORD'"
    env:
      secret:
        - REDIS_PASSWORD
    port: "36379:6379"
    volumes:
      - /var/lib/redis:/data
```
