### ISSUE TITLE
Envify command not adhereing to separate yml config files with different hosts

### ISSUE THREAD

**Issue by eminkel** [basecamp/kamal#529]
I'm running into an issue when I run `kamal envify -d staging` envify will try to attempt an SSH connection to push the env file to a service in my deploy.yml that doesn't appear in my deploy.staging.yml.

deploy.yml
```
backup:
    image: pg-backup
    host: PRODIP
    env:
      clear:
        SCHEDULE: '@midnight'
        BACKUP_KEEP_DAYS: 14
      secret:
        - S3_REGION
        - S3_ACCESS_KEY_ID
        - S3_SECRET_ACCESS_KEY
        - S3_BUCKET
        - S3_PREFIX
        - POSTGRES_HOST
        - POSTGRES_DATABASE
        - POSTGRES_USER
        - POSTGRES_PASSWORD
```

My deploy.staging.yml doesn't contain any reference to the above server or service.

Here is some output of it attempting to connect:
 ```
INFO [4d9a03a2] Running /usr/bin/env mkdir -p .kamal/env/accessories on STAGEIP
INFO [fc9a2f9b] Running /usr/bin/env mkdir -p .kamal/env/accessories on PRODIP
INFO [4d9a03a2] Finished in 0.276 seconds with exit status 0 (successful).
```

Any guidance is much appreciated.
