### ISSUE TITLE
Accessory reboot all

### ISSUE THREAD

**Issue by dmitrytrager** [basecamp/kamal#537]
According to command list, this should work without additional changes:
`kamal accessory reboot all` should work and reboot every accessory.

Result:
`ERROR (Module::DelegationError): Kamal::Commands::Accessory#hosts delegated to accessory_config.hosts, but accessory_config is nil: #<Kamal::Commands::Accessory:0x0000000104591f78 ...`

Version 1.0.0

**Comment by jmarchello** [comment]
@dmitrytrager Could you provide a snippet showing the accessories sections of your deploy.yml?

**Comment by dmitrytrager** [comment]
@jmarchello 
```
accessories:
  db:
    image: postgres:14.8
    host: <ip>
    port: 5432
    env:
      clear:
        POSTGRES_USER: <user>
        POSTGRES_DB: <db_name>
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    host: <ip>
    port: 6379
    directories:
      - data:/data
```
By the way, when I reboot them one by one, it works smoothly
