### ISSUE TITLE
Serving default certificate TLS issue with traefik

### ISSUE THREAD

**Issue by RailsCod3rFuture** [basecamp/kamal#551]
Having an issue where traefik is using the default certificate for the request instead of the real one. Seems that its a TLS handshake error (shown below)

```
time="2023-10-26T01:50:45Z" level=debug msg="http: TLS handshake error from IP:49651: remote error: tls: unknown certificate"
time="2023-10-26T01:50:45Z" level=debug msg="Serving default certificate for request: \"coolwebsite.com\""
```

I updated my dns records, recently on namecheap, but this is my first time working with traefik. I'm also using the configuration below. I utilized the command for mkdir -p /letsencrypt && touch /letsencrypt/acme.json && chmod 600 /letsencrypt/acme.json to add letsencrypt to the server that the rails app and traefik container live on. I need further instruction for setting this up correctly. I also have questions about the httpchallenge and how to handle that on my server.

```
servers:
  web:
    hosts:
      - IP
    options:
      "add-host": host.docker.internal:host-gateway
    labels:
      traefik.http.routers.app.rule: Host(`coolwebsite.com`)
      traefik.http.routers.app.entrypoints: websecure
      traefik.http.routers.app.tls.certresolver: letsencrypt

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls: true
    entrypoints.websecure.http.tls.domains[0].main: "coolwebsite.com"
    certificatesResolvers.letsencrypt.acme.email: "owner@hotmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
```
