### ISSUE TITLE
How to setup Traefik behind Hetzner Load Balancer to trust X-Forwarded-For?

### ISSUE THREAD

**Issue by liamvdv** [basecamp/kamal#576]
Hey, I'm seeing incorrect X-Forwarded-For headers in my FastAPI Application. This is due to Traefik not trusting the X-Forwarded-For headers send by the Hetzner Load Balancer. 
**How to setup Traefik correctly behind Hetzner Load Balancer?**

```
traefik:
  args:
    accesslog: "true"
    log.level: "ERROR"
    # does not work:
    # entryPoints.http.forwardedHeaders.insecure: "true"
    # does not work:
    # LOAD_BALANCER_IP
    # entrypoints.http.forwardedHeaders.insecure: "127.0.0.1/32,LOAD_BALANCER_IP"
  ```

**Comment by northeastprince** [comment]
```
traefik:
  args:
    entrypoints.web.forwardedHeaders.trustedIPs: 10.0.0.0/8
```

**Comment by liamvdv** [comment]
Hey Matt Almeida,
thank you for your response. I'm afraid that doesn't work for me. Can someone reproduce / describe their setup if they face the same problem?

**Comment by northeastprince** [comment]
Our repo is open-source, so feel free to look at [the full file](https://github.com/hackclub/hackathons-backend/blob/main/config/deploy.yml). Our Hetzner load balancer is on 10.x.x.x so that's why it works:

![image](https://github.com/basecamp/kamal/assets/55164724/5f716583-84e9-4115-a1a5-298cb245652a)

**Comment by liamvdv** [comment]
Hey @northeastprince I have taken a look. Is your LB & server running in a Private Network? I currently refer to it via it's public IP as my server is also running with a public IPv4.

**Comment by northeastprince** [comment]
Yes, it's on the same private network as the LB.

**Comment by eminkel** [comment]
Working through a similar issue with forwardedHeaders not functioning properly. 

@liamvdv Did you get this working?

What I'm trying to solve for is I have Traefik as main reverse proxy, that manages routing to a Kamal deployed app (with the traefik-in-container). Each time I use the traefik args with entrypoints (and no other traefik config) my app redirects to https and is non functional.

I've debugged with turning on the Dashboard, noticed Kamal manages the http entrypoint as default, tried `entrypoints.http.forwardedHeaders.trustedIPs` but making no progress.

Furthermore, I realized that Kamal utilizes docker as a provider in traefik which would mean passing labels as configuration should be picked up as detailed: https://doc.traefik.io/traefik/routing/providers/docker/#routers

**Comment by liamvdv** [comment]
Hey @eminkel
no sadly not. It is still on our plate, yet other challenges have kept us busy. @dhh any idea as to why? 
@eminkel if you figure it out, please come back here, we've easily sunken 6h+ into this...

**Comment by eminkel** [comment]
@liamvdv, I just successfully got it working. This feels a bit clunky compared to the Kamal documentation of how this should work, but here it goes:

For your main web role hosts you'll want to add a label:

``` yaml
labels:
  traefik.http.routers.your-service.entrypoints: web
  ```
  
  For the traefik config in your Kamal yaml file you'll then want to be sure to have the following set:
  
  ```yaml
  traefik:
     args:
       entrypoints.web.address: ':80'
       entrypoints.web.forwardedHeaders.trustedIPs: 127.0.0.1,10.0.0.0/24
   ```
   
   Once you have this set, blast away your traefik container with `kamal traefik reboot`, then `kamal deploy`. 
   
  Hope this helps get you up and going. I'm finally passing the proper IP in the logs in the Rails App.
