### ISSUE TITLE
Healthcheck publishes 3999 on the container

### ISSUE THREAD

**Issue by alokshenoy** [basecamp/kamal#581]
Hi all, I'm attempting to use Kamal to develop a Django based application.

Django by default runs on 8000 (and my Dockerfile does expose 8000).

However, when I run `kamal setup`, I see that kamal runs the app and publishes 3999:8000, and attempts to curl against 8000 after that. This inevitably fails. What am I getting wrong?

`docker run --detach --name healthcheck-test-page-a95c8e27d96f9d7d984d04fb93a9f3ee8cdc459a_uncommitted_78f94c8fe33f549f --publish 3999:8000 --label service=healthcheck-test-page -e KAMAL_CONTAINER_NAME="healthcheck-test-page" --env-file .kamal/env/roles/test-page-web.env --health-cmd "curl -f http://localhost:8000/up || exit 1" --health-interval "5s"`

Relevant section of Dockerfile:

```
EXPOSE 8000


ENTRYPOINT ["python3"]
CMD ["manage.py", "runserver"]
```

Relevant section of Kamal config:

```
# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /up
  port: 8000
  interval: 5s
```

Locally, when running the application - curling against `http://localhost:8000/up` returns a 200, whether I'm running it inside a docker container or outside.
