### ISSUE TITLE
Feature pitch: Support defining of custom CLI commands through deploy.yml

### ISSUE THREAD

**Issue by dhnaranjo** [basecamp/kamal#639]
Hey, hi! I think it'd be handy to be able to define aliases in my config file to clean up repetitive commands I might want used across my team. For example allowing me to run `kamal app console` to get to my Rails console with the following config.

```
alias:
  app:
    console: app exec -i "bin/rails c --sandbox"
    angry_console: app exec -i "bin/rails c"
```

We might not want to pollute the cli with custom commands using names that might conflict with future features, so maybe it's all under `kamal alias` or `kamal run` or whatever.

If y'all are interested I'd be happy to knock together a PR for it.
