### ISSUE TITLE
tailwind styles do not update with latest tag

### ISSUE THREAD

**Issue by n1xn** [basecamp/kamal#641]
When using a single tag for the container image new introduced tailwindcss styles do not apply / get added to the styles.
Using sha fixes this issue. 

**Dockerfile**
```
RUN bundle exec bootsnap precompile app/ lib/
RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile

FROM base
```

**config/deploy.yml**
```
asset_path: /rails/public/assets
```

**.github/workflows/ci.yml**
```
      - name: build & push docker image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: ./rails
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: deploy with Kamal
        working-directory: ./rails
        run: kamal deploy --skip-push -vvvv
        env:
          GITHUB_CONTAINER_REGISTRY_TOKEN: ${{ github.token }}
          VERSION: ${{ github.sha }} # -> latest doesn't update assets properly
```
