### ISSUE TITLE
Customize init command with optional arguments

### ISSUE THREAD

**Issue by hschne** [basecamp/kamal#658]
When running `kamal init` a `deploy.yml` file with hard-coded values for repository, user, etc. is created. Users have to modify this file to suit their needs manually. 

```yml
service: my-app # <<<

image: user/my-app # <<<

servers:
  - 192.168.0.1 # <<<

registry:
  username: my-user # <<<
```

## Proposition 

These hard-coded values could either be inferred from the environment (e.g. username, directory...) or at least be customizable in the `kamal init` command. For example:

```bash
kamal init --service app-name --user user-name --server 192.168.0.1
```

I'd be happy to work on this. What do you think?
