### ISSUE TITLE
Certificate is not valid, Common Name (CN) TRAEFIK DEFAULT CERT

### ISSUE THREAD

**Issue by dorianmariefr** [basecamp/kamal#667]
I'm trying to get SSL to work on https://code.dorianmarie.com

I'm getting Common Name (CN)	TRAEFIK DEFAULT CERT

I'm using this `config/deploy.yml`:

```yaml
service: code
image: dorianmariefr/code
servers:
  web:
    hosts:
      - 165.232.149.13
    labels:
      traefik.http.routers.blog.entrypoints: websecure
      traefik.http.routers.blog.rule: Host(`code.dorianmarie.com`)
      traefik.http.routers.blog.tls.certresolver: letsencrypt

registry:
  username: dorianmariefr
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "dorian@dorianmarie.fr"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
```

![Screenshot 2024-02-02 at 16 39 18](https://github.com/basecamp/kamal/assets/58794487/d5d07a74-21ef-41f6-8765-169719b8cee3)

![Screenshot 2024-02-02 at 16 39 22](https://github.com/basecamp/kamal/assets/58794487/73e41ee5-6f6f-417b-85ba-a7bb412327f8)
