### ISSUE TITLE
(ArgumentError): invalid slice size

### ISSUE THREAD

**Issue by Kaakati** [basecamp/kamal#681]
```
boot:
  limit: "50%"
  wait: 2
servers:
  web:
    - x.x.x.x
```

The deploy fails the lock doesn't release if you have only one server only and raising "(ArgumentError): invalid slice size", maybe handling this case to prevent the deploy from failing.
