### ISSUE TITLE
`kamal app exec -i "bin/rails dbconsole"` requires some password

### ISSUE THREAD

**Issue by dorianmariecom** [basecamp/kamal#684]
I tried `kamal app exec -i "bin/rails dbconsole"` but it requires some kind of authentication:

```
~/s/code> kamal app exec -i "bin/rails dbconsole"
Get most recent version available as an image...
Launching interactive command with version latest via SSH from new container on 165.232.149.13...
Password for user code: 
```

And when I enter my database password I get:

```
~/s/code> kamal app exec -i "bin/rails dbconsole"
Get most recent version available as an image...
Launching interactive command with version latest via SSH from new container on 165.232.149.13...
Password for user code: 
psql: error: FATAL:  password authentication failed for user "code"
Connection to 165.232.149.13 closed.
```

**Comment by nickhammond** [comment]
@dorianmariecom Is your database an accessory? What's the accessory config for this in your deploy.yml?

**Comment by dorianmariecom** [comment]
Here is my accessory config:

```
accessories:
  db:
    image: postgres:16.1
    host: 45.55.196.152
    port: 5432
    env:
      clear:
        POSTGRES_USER: code
        POSTGRES_DB: code_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
```
