### ISSUE TITLE
[Solved] GitHub Actions, ECR, `key not found KAMAL_REGISTRY_PASSWORD`

### ISSUE THREAD

**Issue by Kaakati** [basecamp/kamal#685]
I'm using GitHub Actions to Automatically deploy to EC2 & ECR: my workflow contains `kamal envify` then `kamal deploy`, for some reason I was getting `key not found KAMAL_REGISTRY_PASSWORD` on the deployment step, I was able to do a workaround by setting `KAMAL_REGISTRY_PASSWORD ` in a step before Kamal Deploy, then I was able to deploy.

```yaml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region           : AWS-REGION
          mask-aws-account-id  : 'no'

      - name: Login to Amazon ECR
        id  : login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Kamal Lock Release
        id  : kamal-unlock
        run: |
          kamal lock release

      - name: Kamal Envify
        id  : kamal-envify
        env :
          # For some reason this KAMAL_REGISTRY_PASSWORD wasn't working.
          KAMAL_REGISTRY_PASSWORD: ${{ steps.login-ecr.outputs.docker_password_<ECR_ACCOUNT_ID>_dkr_ecr_<ECR_REGION_NAME>_amazonaws_com }} 
          RAILS_ENV: production
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          # .... remaining env
        run: |
          kamal envify
      
     - name: Set and Retrieve Github ENV variables
        shell: bash
        run: |
          # define variables
          KAMAL_REGISTRY_PASSWORD=${{ steps.login-ecr.outputs.docker_password_<ECR_ACCOUNT_ID>_dkr_ecr_<ECR_REGION_NAME>_amazonaws_com }}
          echo "KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD" >> $GITHUB_ENV

      - name: Kamal Deploy
        id: kamal-deploy
        run: |
          kamal deploy
```
