### ISSUE TITLE
ActionCable not working

### ISSUE THREAD

**Issue by k3vout** [basecamp/kamal#693]
Hi guys, I’m so sorry, English is not my first language,

I deployed my app with Kamal but ActionCable (I am using Turbo Broadcast) is not working, any of you went through this?

- This is the Firefox error
<img width="684" alt="image" src="https://github.com/basecamp/kamal/assets/39852288/1f906040-3d67-4cdc-8dc5-14ae20343dbb">

- This is my deploy.yml file
```yml
service: atenas

image: k3vin/atenas

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
    network: "private"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entryPoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "support@atenas.app"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

servers:
  web:
    hosts:
      - 5.78.78.254
    labels:
      traefik.http.routers.atenas-web.entrypoints: websecure
      traefik.http.routers.atenas-web.rule: Host(`atenas.app`)
      traefik.http.routers.atenas-web.tls.certresolver: letsencrypt
    options:
      network: "private"
  job:
    hosts:
      - 5.78.78.254
    cmd: bundle exec sidekiq
    options:
      network: "private"

registry:
  username: k3vin

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    HOSTNAME: atenas.app
    DB_HOST: 5.78.78.254
    RAILS_LOG_TO_STDOUT: true
    REDIS_URL: "redis://atenas-redis:6379/0"
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - SIDEKIQ_USERNAME
    - SIDEKIQ_PASSWORD



accessories:
  db:
    image: postgres:15
    host: 5.78.78.254
    port: 5432
    env:
      clear:
        POSTGRES_USER: "atenas"
        POSTGRES_DB: "atenas_production"
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    roles:
      - web
      - job
    cmd: "redis-server"
    volumes:
      - /var/lib/redis:/data
    options:
      network: "private"
```

Thanks in advance.
