### ISSUE TITLE
bash-3.2$ echo "Image ***/code:a494d90af6f3ed3c08ee4f29d345b3b9d8769722 is missing the `service` label" && exit 1 bash: service: command not found Image ***/code:a494d90af6f3ed3c08ee4f29d345b3b9d8769722 is missing the  label exit

### ISSUE THREAD

**Issue by dorianmariecom** [basecamp/kamal#694]
Here are the logs:

```
INFO [31e9eed9] Running /usr/bin/env mkdir -p .kamal on 164.92.135.114
  INFO [31e9eed9] Finished in 1.234 seconds with exit status 0 (successful).
Acquiring the deploy lock...
Pull app image...
  INFO [6[8](https://github.com/dorianmariecom/code/actions/runs/8037523248/job/21952471653#step:10:9)7d0007] Running docker image rm --force ***/code:a4[9](https://github.com/dorianmariecom/code/actions/runs/8037523248/job/21952471653#step:10:10)4d90af6f3ed3c08ee4f29d345b3b9d8769722 on 164.92.135.[11](https://github.com/dorianmariecom/code/actions/runs/8037523248/job/21952471653#step:10:12)4
  INFO [687d0007] Finished in 0.336 seconds with exit status 0 (successful).
  INFO [1aad45e8] Running docker pull ***/code:a494d90af6f3ed3c08ee4f29d345b3b9d8769722 on 164.92.135.114
  INFO [1aad45e8] Finished in [12](https://github.com/dorianmariecom/code/actions/runs/8037523248/job/21952471653#step:10:13)3.543 seconds with exit status 0 (successful).
  INFO [29d4419a] Running docker inspect -f '{{ .Config.Labels.service }}' ***/code:a494d90af6f3ed3c08ee4f29d345b3b9d8769722 | grep -x code || (echo "Image ***/code:a494d90af6f3ed3c08ee4f29d345b3b9d8769722 is missing the `service` label" && exit 1) on 164.92.[13](https://github.com/dorianmariecom/code/actions/runs/8037523248/job/21952471653#step:10:14)5.1[14](https://github.com/dorianmariecom/code/actions/runs/8037523248/job/21952471653#step:10:15)
Releasing the deploy lock...
  Finished all in 126.4 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host [16](https://github.com/dorianmariecom/code/actions/runs/8037523248/job/21952471653#step:10:17)4.92.135.114: docker exit status: 1
docker stdout: Image ***/code:a494d90af6f3ed3c08ee4f29d345b3b9d8769722 is missing the  label
docker stderr: Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]
```

Basically doing \`service\` is executed within bash:

```
bash-3.2$ echo "Image ***/code:a494d90af6f3ed3c08ee4f29d345b3b9d8769722 is missing the `service` label" && exit 1
bash: service: command not found
Image ***/code:a494d90af6f3ed3c08ee4f29d345b3b9d8769722 is missing the  label
exit
```

**Comment by wenderjean** [comment]
How does your `deploy.yml` look like?

**Comment by dorianmariecom** [comment]
Here it is, hope that helps:

```yaml
service: code
image: dorianmariecom/code
healthcheck:
  cmd: /bin/true
builder:
  remote:
    arch: amd64
    ssh: root@164.92.135.114
servers:
  web:
    hosts:
      - 164.92.135.114
    labels:
      traefik.http.routers.code.rule: Host(`code.dorianmarie.com`)
      traefik.http.routers.code_secure.entrypoints: websecure
      traefik.http.routers.code_secure.rule: Host(`code.dorianmarie.com`)
      traefik.http.routers.code_secure.tls.certresolver: letsencrypt
      traefik.http.routers.code_secure.tls: true
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    HOST: code.dorianmarie.com
    BASE_URL: https://code.dorianmarie.com
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - DATABASE_URL
traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "dorian@dorianmarie.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
accessories:
  db:
    image: postgres:16.1
    host: 164.92.135.114
    port: 5432
    env:
      clear:
        POSTGRES_USER: code
        POSTGRES_DB: code_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
```

**Comment by acidtib** [comment]
hi @dorianmariecom how is the image being generated? using kamal deploy or are you using a github action workflow to build the image and then doing something like `kamal deploy --skip-push --version=${{ github.sha }}` to deploy?

**Comment by dorianmariecom** [comment]
The error was because I didn't have `LABEL service="code"` in my Dockerfile

Dockerfile

```dockerfile
FROM debian:bullseye-slim as base
ENV BUNDLER_VERSION="2.5.5" \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="development" \
    NODE_VERSION="20.11.0" \
    NPM_VERSION="10.4.0" \
    RAILS_ENV="production" \
    RUBY_INSTALL_VERSION="0.9.3" \
    RUBY_VERSION="3.3.0" \
    YARN_VERSION="1.22.19"

ENV PATH="/opt/rubies/ruby-${RUBY_VERSION}/bin:/usr/local/node/bin:${PATH}"

RUN apt-get update && \
    apt-get install -y \
        autoconf \
        build-essential \
        curl \
        fish \
        git \
        libpq-dev \
        libvips \
        pandoc \
        pkg-config \
        postgresql-client \
        vim \
        wget

RUN wget "https://github.com/postmodern/ruby-install/releases/download/v${RUBY_INSTALL_VERSION}/ruby-install-${RUBY_INSTALL_VERSION}.tar.gz"
RUN tar -xzvf "ruby-install-${RUBY_INSTALL_VERSION}.tar.gz"

WORKDIR "ruby-install-${RUBY_INSTALL_VERSION}"

RUN make install
RUN ruby-install -p https://github.com/ruby/ruby/pull/9371.diff ruby "${RUBY_VERSION}"

WORKDIR /rails

RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/
RUN /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node
RUN npm install -g "yarn@${YARN_VERSION}"

COPY Gemfile Gemfile.lock ./

RUN gem install bundler -v "${BUNDLER_VERSION}"
RUN bundle install

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN HOST=example.com \
    BASE_URL=https://example.com \
    RAILS_MASTER_KEY_DUMMY=1 \
    SECRET_KEY_BASE_DUMMY=1 \
    ./bin/rails assets:precompile

ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3000
CMD ["./bin/rails", "server"]
LABEL service="code"
```

.github/workflows/ci.yml

```yaml
name: CI
on: push
jobs:
  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: sudo apt-get install -y pandoc
      - run: bin/brakeman -A -q --color
  bundler-audit:
    name: Bundler Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/bundler-audit
  importmap-audit:
    name: Importmap Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/importmap audit
  importmap-outdated:
    name: Importmap Outdated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/importmap outdated
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_MASTER_KEY: ${{secrets.TEST_RAILS_MASTER_KEY}}
    services:
      postgres:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable --ignore-engines
      - run: sudo apt-get -yqq install libpq-dev pandoc
      - run: bin/rails db:create db:schema:load
      - run: bin/rails assets:precompile
      - run: bin/rspec
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/rubocop
  yarn-audit:
    name: Yarn Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn audit
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - brakeman
      - bundler-audit
      - importmap-audit
      - importmap-outdated
      - rspec
      - rubocop
      - yarn-audit
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{secrets.KAMAL_REGISTRY_USERNAME}}
          password: ${{secrets.KAMAL_REGISTRY_PASSWORD}}
      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{github.repository}}:${{github.sha}}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - run: gem install kamal
      - run: kamal lock release
        if: github.ref == 'refs/heads/main'
      - run: kamal deploy --skip-push
        env:
          KAMAL_REGISTRY_USERNAME: ${{secrets.KAMAL_REGISTRY_USERNAME}}
          KAMAL_REGISTRY_PASSWORD: ${{secrets.KAMAL_REGISTRY_PASSWORD}}
          RAILS_MASTER_KEY: ${{secrets.PRODUCTION_RAILS_MASTER_KEY}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        if: github.ref == 'refs/heads/main'
```

**Comment by wenderjean** [comment]
@dorianmariecom It should be working now but you can also label your image during image build with `docker build --label "service=code"` avoiding the need of adding this dependency to your Dockerfile. It should be possible to do a similar thing using `docker/setup-buildx-action`

**Comment by dorianmariecom** [comment]
The issue is that when the service is not found, it will execute the command `service`

**Comment by acidtib** [comment]
@dorianmariecom 

```
        - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          labels: service=code
          tags: dorianmariecom/code:latest,dorianmariecom/code:${{ github.sha }}
          secrets: |
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
```
