### ISSUE TITLE
Incorrect IP address when using remote builder with proxy

### ISSUE THREAD

**Issue by JoeKaldas** [basecamp/kamal#714]
I'm trying to deploy on Hetzner. My setup has 2 servers, one for app and one for postgres.
They talk to each other internally. Have a network setup on Hetzner for that.

Here's a screenshot of my 2 servers.
![0o3_SQJ-](https://github.com/basecamp/kamal/assets/6186940/226c43e1-42f8-40b4-a8a8-ecd341db5db1)

If I try deploying using `Using remote builder for single-arch`,  I get the following error. It's trying to connect to `5.75.252.76` which isn't even one of my IP addresses. I tried using `10.0.0.2` in my builder host but same issue.

![LKHFHygY](https://github.com/basecamp/kamal/assets/6186940/eab36961-e501-4be3-9f61-f8033c9e01e7)

Here's my `deploy.yml`

```yml
service: j-h

image: joekaldas/j-h

ssh:
  proxy: "5.75.253.249"

servers:
  web:
    hosts:
      - 10.0.0.2
  solid-queue:
    hosts:
      - 10.0.0.2
    cmd: bundle exec rake solid_queue:start

registry:
  username: joekaldas

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    POSTGRES_USER: postgres
    POSTGRES_HOST: 10.0.0.3
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

builder:
  remote:
    arch: amd64
    host: ssh://root@5.75.253.249

accessories:
  pg-16.2:
    image: postgres:16.2
    host: 10.0.0.3
    port: "5432:5432"
    env:
      clear:
        POSTGRES_USER: postgres
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/init.sql:/docker-entrypoint-initdb.d/setup.sql
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
```
