### ISSUE TITLE
non-ASCII in env file

### ISSUE THREAD

**Issue by zhongsheng** [basecamp/kamal#724]
The env value been dumped when I push env to my server.

```yml
env:
  clear:
    ENV_TEST: 中个
```

In server env file I got this:
```bash
ENV_TEST: \u4E2D\u4E2A
```

The value been dumped at   lib/kamal/env_file.rb:39
