### ISSUE TITLE
Improvement request: add support for volumes-from for sharing data between docker containers

### ISSUE THREAD

**Issue by KeithP** [basecamp/kamal#791]
Hi. We need the web container to have access to the letsencrypt certificate generated by traefik. In our case in order to perform server to server mTLS. The broader question is How To Share Data between Docker Containers using Kamal.

So on the web container we need to fix this:
`No such file or directory @ rb_sysopen - letsencrypt/acme.json`

I'm fairly new to Kamal and Docker but the way forward seems to be via a volumes-from argument like this:

`$ docker run -ti --name=Container6 --volumes-from Container4:ro ubuntu`

Could Kamal be expanded to support volumes-from?

```
# deploy.yml

servers:
  web:
    ...
    volumes:    
      - "storage:/rails/storage" 
      from:
        - "traefik:ro"
```
or
		
```
# deploy.yml

servers:
  web:
    ...
    volumes:    
      - "storage:/rails/storage" 
    volumesFrom:
      - "traefik:ro"
```
