### ISSUE TITLE
Getting an error when using a destination with no corresponding deploy yml file

### ISSUE THREAD

**Issue by jeromedalbert** [basecamp/kamal#809]
### Problem

When using `-d destination`, at the moment you have to have a `deploy.destination_name.yml` file (along with a `deploy.yml` file), or you get a `ERROR (RuntimeError): Configuration file not found` error.

Conversely, when using `-d destination`, at the moment you have to have a `deploy.yml` file (along with a `deploy.destination_name.yml` file), or you also get a `ERROR (RuntimeError): Configuration file not found` error.

I don't think it should error out. I think only one yml file can be enough, because you can make a deploy.yml file that works for all destinations.

### Example

The following `deploy.yml` file works for all destinations:

```
service: myapp
image: myuser/myapp

servers:
  web:
  - <%= ENV['SERVER_IP'] %>

registry:
  username: myuser
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - SERVER_IP
```

Because the IP comes from an environment variable, like `.env.production` or `.env.staging`, I don't have anything to add in a `deploy.production.yml` file or `deploy.staging.yml` file. One `deploy.yml` file is enough, but this won't work in Kamal at the moment.

The only way to work around this is to create a dummy `deploy.production.yml` file with a dummy key in it. The yml file has  has to have a dummy key at the moment, because if it is empty you get a `ERROR (NoMethodError): undefined method `symbolize_keys' for false` error) error.
