### ISSUE TITLE
Reuse same accessory across multiple kamal application deploy configs

### ISSUE THREAD

**Issue by chekkan** [basecamp/kamal#829]
Is there a way to reuse an accessory, such as mysql, or prometheus across multiple kamal application deployments?

So that I can share a mysql server, or a prometheus server across multiple applications?

At the moment, the docker container name for the accessory has the service's name as its prefix. 

```yaml
# app-a/config/deploy.yml
service: app-a
image: foo/app-a
accessories:
  db:
    image: mysql:5.7
    host: 1.1.1.3
    port: 3306
    
# app-b/config/deploy.yml
service: app-b
image: foo/app-b
accessories:
  db:
    image: mysql:5.7
    host: 1.1.1.3
    port: 3306
```

![image](https://github.com/basecamp/kamal/assets/217568/7598668f-94d6-4fc8-86a4-aa9aae37a131)

**Comment by djmb** [comment]
You can set `service` on the accessories, does that work?

```
# app-a/config/deploy.yml
service: app-a
image: foo/app-a
accessories:
  db:
    service: shared-mysql
    image: mysql:5.7
    host: 1.1.1.3
    port: 3306
    
# app-b/config/deploy.yml
service: app-b
image: foo/app-b
accessories:
  db:
    service: shared-mysql
    image: mysql:5.7
    host: 1.1.1.3
    port: 3306
```
