### ISSUE TITLE
My app is not starting as its depend upon accessories (Redis). How we can start accessories first?

### ISSUE THREAD

**Issue by Tekchanddagar** [basecamp/kamal#881]
Hello Team,
We are testing our deployment using kamal and below is my kamal `config/deploy.yml` file:

```
# Name of your application. Used to uniquely configure containers.
service: idp-app

# Name of the container image.
image: idp-app 
# Deploy to these servers.
servers:
 web:
   hosts:
     - 17.9.4.6
   labels:
     traefik.enable: true

accessories:
  nginx:
    image: nginx:latest  # Use the official Nginx image
    roles:
      - web
    volumes:
      - /data/nginx/idp-nginx.conf:/etc/nginx/conf.d/idp-nginx.conf:ro  # Mount your custom Nginx configuration
    options:
      publish:
        - "3600:3600"  # Expose Nginx port 3600 to the host machine
  redis:
    image: redis:latest  # Use the official Redis image
    roles:
      - web
    options:
      publish:
        - "6379:6379"  # Expose Redis port 6379 to the host machine (default Redis port)

```
As you can see we have one app i.e `idp-app` and its works fine if we keep app, nginx and redis inside one image and deploy using kamal.

But we are looking to keep app, redis and nginx on different container. 
**But we are facing one issue i.e our application is depend upon redis and it will not come up untill redis is not running.**

We have tried to find out option like `depends_on` in docker-compose but didn't found anything.

Is there any way in Kamal where we can start Redis (accessories) first then app?

Any help or guidance will be appriciated.

Thank You
