### ISSUE TITLE
Wrong permissions on volumes

### ISSUE THREAD

**Issue by alec-c4** [basecamp/kamal#897]
Hey!
There are problem with permissions in kamal. I've added volume

```yaml
ssh:
  user: alec

####################

volumes:
  - ./storage:/rails/public/uploads:rw
```

in my `deploy.yml` file and got a problem with permissions:

<img width="503" alt="SCR-20240730-bilf" src="https://github.com/user-attachments/assets/1384f092-92de-4f14-9a9c-7ab9c903e069">

As you see - I've configured kamal to use user `alec`, but volume was created by/for `root`. It cause problems like this:

<img width="778" alt="SCR-20240730-bjkb" src="https://github.com/user-attachments/assets/78eb03f6-faab-4bd4-8658-a67e47a51d36">
