### ISSUE TITLE
Problem with LetsEncrypt

### ISSUE THREAD

**Issue by alec-c4** [basecamp/kamal#898]
As an addition to my previous issue https://github.com/basecamp/kamal/issues/897 there one more problem with permissions. If you have user other than root in your `deploy.yml` file

```yml
ssh:
  user: alec
```

and traefik is configured to use letsencrypt

```yml
traefik:
  options:
    network: "private"
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json" # <------
  args:
    accesslog: true
    log.level: DEBUG
    accesslog.format: json

    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"

    entryPoints.web.http.redirections.entryPoint.to: websecure 
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true

    certificatesResolvers.letsencrypt.acme.email: "info@example.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json" # <------
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web 
```

you'll be unable to store cert locally, because of insufficient permissions (`/letsencrypt` will be owned by root). 

I've tried to follow recommendations from this issue https://github.com/basecamp/kamal/issues/667  but it doesn't work. I've tried
- `chown` on `/letsencrypt`
- create `./letsencrypt` in home directory + configure `deploy.yml`

Any idea how to fix it?
