### ISSUE TITLE
Running setup on a specific role shouldn't setup accessories

### ISSUE THREAD

**Issue by nickhammond** [basecamp/kamal#935]
The use case for this is to be able to bring a new server online with an existing kamal deployed setup.

Given I have one web role, one accessory:

```
servers:
  web:
    host: 123.456.78.9
accessories:
  db:
    host: 123.456.78.9
```

And I want to add another web server into the mix so `servers` becomes:

```
servers:
  web:
    host: 123.456.78.9
  web_new:
    host: 111.222.333.444
accessories:
  db:
    host: 123.456.78.9
```

To bring the server online you'd need to run `kamal setup -r web_new` so that it pushes up your env files first but that fails with:
```
docker stderr: docker: Error response from daemon: Conflict. The container name "/hey-db" is already in use by container "7939d26efb157e547d6a70bf0e713a5ccc9079a016ca8261518dbfd6323da5cc". You have to remove (or rename) that container to be able to reuse that name.
```

I understand that `hey-db` has already been provisioned and you can work around this by just running `kamal deploy -r web_new` after that first failure but I think it probably shouldn't try to setup any accessories since they're not being targeted. In this example the accessory is also on a different host so it's not a host target.

So currently it's:

```
kamal setup -r web_new
# fails at existing container for accessory
kamal deploy -r web_new
# deploys successfully
```

Thinking we could adjust so that there's a usable server after the setup command finishes running.

**Comment by a3kov** [comment]
IMHO we don't need multiple "app" roles - in your case you should add the server to the `web` role.

**Comment by a3kov** [comment]
Well to support this case Kamal should have explicit app roles configuration. Currently I got the idea that there's one "primary" role that has the app deployed. Otherwise having pure-accessory servers wouldn't be possible. Deploying app to every server simply doesn't make sense

**Comment by nickhammond** [comment]
@a3kov It does, here's an expanded example with role-specific configuration. You can have `hosts` or `host` within each role.

``` yml
servers:
  web:
    host: 123.456.78.9
    env:
      clear:
        DB_POOL: 50
    options:
      memory: "6GB"

  web_new:
    host: 111.222.333.444
    env:
      clear:
        DB_POOL: 10
    options:
      memory: "2GB"

accessories:
  db:
    host: 123.456.78.9
```

Also, the "primary" role is just the one that gets connected to kamal-proxy by default but you can always enable it on additional roles. There's a few commands that specifically run on the primary role.
