### ISSUE TITLE
ERROR (Kamal::ConfigurationError): unknown key: traefik

### ISSUE THREAD

**Issue by dep** [basecamp/kamal#991]
Just started getting this in my github workflows today:

```
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - run: gem install kamal
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.KAMAL_DEPLOY_PRIVATE_KEY }}
      - uses: docker/setup-buildx-action@v3
      - run: kamal lock release
      - run: kamal env push
      - run: kamal deploy
```

the `kamal lock release` step fails with:

```
ERROR (Kamal::ConfigurationError): unknown key: traefik
```

![CleanShot 2024-09-27 at 14 07 03](https://github.com/user-attachments/assets/67b707d3-fc45-43a0-8e7f-53757df6f810)
